AmadeusITGroup/otter

packages/@ama-sdk/core/project.json
packages/@ama-sdk/generator-sdk/project.json
packages/@ama-sdk/swagger-builder/project.json
packages/@ama-terasu/cli/project.json
packages/@ama-terasu/core/project.json
packages/@ama-terasu/schematics/project.json

broken build: https://github.com/AmadeusITGroup/otter/actions/runs/4054005733/jobs/6975306431

fix: broken tsc

---

apps/chrome-devtools/src/app-components/app.component.ts
packages/@o3r/components/src/devkit/inspector/otter-inspector.helpers.ts

chrome inspected window evaluation does not support external functions

fix: chrome devtool component inspector

---

.github/actions/setup-java/action.yml
.github/actions/setup/action.yml
.github/workflows/code-check.yml
.github/workflows/main.yml
.github/workflows/release.yml

3.9.0 faces issues, version needs to be downgraded

fix: explicitely set mvn version

---

.github/CODEOWNERS
apps/chrome-devtools/scripts/sanitize-manifest.cjs

chore: add codeowner for json schema

fix: chrome extension sanitized version

---

.github/pull_request_template.md

feat: add github pull request template

---

.github/workflows/pr-labels.yml

Fix error in case of empty array of labels
- :bug: Fixes #268

fix: pull request label caculation

---

.github/workflows/codeql.yml

Add code analysis (remaining Github security checks)

feat: add code analysis

---

packages/@ama-terasu/cli/src/helpers/module.helper.ts
packages/@ama-terasu/cli/src/helpers/version.helper.ts

Indicate if the Amaterasu module is an "official" one (meaning supported by Otter of affiliated teams)

feat: add official module indicator

---

apps/vscode-extension/src/commands/extract/styling/helpers/regex.helper.ts
apps/vscode-extension/src/commands/extract/styling/helpers/utils.helper.ts
packages/@o3r/dev-tools/src/cli/package-export.ts
packages/@o3r/dev-tools/src/cli/set-version.ts
packages/@o3r/rules-engine/src/components/rules-engine/rule-condition/rule-condition-pres.component.ts
packages/@o3r/schematics/src/utility/gitignore.ts
packages/@o3r/schematics/src/utility/template-property.helper.ts
packages/@o3r/storybook/addon/theme.tsx
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts

Fix divers issue reported by [codeql](https://github.com/AmadeusITGroup/otter/security/code-scanning)

fix: codeql high suggestions

---

packages/@ama-sdk/core/schematics/ng-add/mocks/angular.mocks.json
packages/@ama-sdk/generator-sdk/collection.json
packages/@o3r/components/builders.json
packages/@o3r/components/testing/mocks/angular.mocks.json
packages/@o3r/core/builders.json
packages/@o3r/core/collection.json
packages/@o3r/core/migration.json
packages/@o3r/core/package.json
packages/@o3r/core/schematics/fixture/helpers.ts
packages/@o3r/core/testing/mocks/angular.mocks.json
packages/@o3r/localization/builders.json
packages/@o3r/rules-engine/builders.json
packages/@o3r/schematics/src/utility/loaders.ts
packages/@o3r/styling/builders.json
packages/@o3r/styling/collection.json
packages/@o3r/testing/migration.json
packages/@o3r/testing/schematics/ng-update/v9-0/index.ts
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/angular.mocks.json.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.result.ts.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.ts.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.spec.ts
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.ts
packages/@o3r/testing/src/core/angular/component-fixture.ts
packages/@o3r/testing/src/core/component-fixture.ts
packages/@o3r/testing/src/core/helpers.ts
packages/@o3r/testing/src/core/playwright/component-fixture.ts
packages/@o3r/testing/src/core/protractor/component-fixture.ts
packages/@o3r/testing/testing/mocks/angular.mocks.json
packages/@o3r/testing/tsconfig.json

feat: add promise support to throwOnUndefined

fix: throwOnUndefined to work with playwrigh

---

README.md
docs/core/START_NEW_APPLICATION.md
packages/@o3r/core/schematics/ng-add/schema.json

Fix documentation according to UIS team feedbacks

fix(core): documentation of the ng add

---

CONTRIBUTING.md

Update contributing guidelines.

doc: enhance CONTRIBUTING.md guidelines

---

packages/@o3r/schematics/schematics/ng-add/index.ts

Force installation of the ng-add schematics dependency one by one and provides more context for debuggging.

fix: ng-add run with npm - missing dependencies

---

packages/@o3r/schematics/package.json
yarn.lock

fix: install correct angular-devkit/architect on ng-add

---

packages/@o3r/core/src/store/async/async.operators.ts

Add the capability to not provide callback to effect helpers
- :rocket: Feature #363

feat: add the capability to not provide callback to effect helpers

---

packages/@o3r/testing/src/core/angular/component-fixture.ts
packages/@o3r/testing/src/core/component-fixture.ts
packages/@o3r/testing/src/core/playwright/component-fixture.ts
packages/@o3r/testing/src/core/protractor/component-fixture.ts

Cascading/8.1 into 8.2

---

packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/errors.ts
packages/@ama-sdk/core/src/plugins/core/reply-plugin.ts
packages/@ama-sdk/core/src/plugins/exception/exception.reply.ts

feat: improve error logs format

---

.github/ISSUE_TEMPLATE/6-FEATURE-FORM.yaml

Add context field in feature creation template

chore: add context field in feature creation template

---

README.md
docs/core/START_NEW_APPLICATION.md
packages/@ama-sdk/schematics/project.json
packages/@o3r/create/.eslintrc.js
packages/@o3r/create/.gitignore
packages/@o3r/create/README.md
packages/@o3r/create/package.json
packages/@o3r/create/project.json
packages/@o3r/create/src/index.ts
packages/@o3r/create/tsconfig.build.json
packages/@o3r/create/tsconfig.eslint.json
packages/@o3r/create/tsconfig.json
yarn.lock

Add the support of `npm create @o3r`

feat: add the support of `npm create @o3r`

---

apps/vscode-extension/src/commands/module/add-module.command.ts
packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
packages/@o3r/core/README.md
packages/@o3r/core/collection.json
packages/@o3r/core/schematics/add-modules/index.ts
packages/@o3r/core/schematics/add-modules/schema.json
packages/@o3r/core/schematics/add-modules/schema.ts
packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/core/schematics/rule-factories/module-list/index.ts
packages/@o3r/core/schematics/show-modules/index.ts
packages/@o3r/core/src/modules/index.ts
packages/@o3r/core/src/modules/module.constants.ts
packages/@o3r/core/src/public_api.ts
packages/@o3r/schematics/src/index.ts
packages/@o3r/schematics/src/modules/index.ts
packages/@o3r/schematics/src/modules/modules.constants.ts
packages/@o3r/schematics/src/modules/modules.helpers.ts
packages/@o3r/schematics/src/utility/modules.ts

Add a schematics to facilitate the add of a module to an application/library
- #401 
The PR add the support of private default registry defined in NPM configuration only

feat: add schematic to add a module

---

apps/github-cascading-app/src/cascading/cascading.spec.ts
apps/github-cascading-app/src/cascading/cascading.ts

Changed cascading origin branch to run target branch CI

fix: changed cascading origin branch

---

apps/chrome-devtools/package.json
apps/chrome-devtools/project.json
apps/chrome-devtools/scripts/set-manifest-version.cjs

Fix the manifest version calculation (aligned with the package.json)

fix(chrome-extension): manifest version calculation

---

packages/@o3r/configuration/schematics/configuration-to-component/index.spec.ts
packages/@o3r/configuration/schematics/configuration-to-component/index.ts

fix: check if configuration is already present

---

packages/@o3r/localization/README.md
packages/@o3r/localization/collection.json
packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
packages/@o3r/localization/schematics/add-localization-key/index.ts
packages/@o3r/localization/schematics/add-localization-key/schema.json
packages/@o3r/localization/schematics/add-localization-key/schema.ts
packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
packages/@o3r/localization/schematics/localization-to-component/index.ts
packages/@o3r/localization/schematics/localization-to-component/templates/__name__.localization.json
packages/@o3r/localization/schematics/localization-to-component/templates/__name__.translation.ts.template

Split schematics to add localization key

feat: split schematics localization key

---

packages/@o3r/configuration/src/devkit/configuration-devtools.console.spec.ts
packages/@o3r/testing/package.json
packages/@o3r/testing/schematics/ng-update/v9-0/index.ts
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports-map.ts
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports.spec.ts
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports.ts
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/angular.mocks.json.template
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/my-component-updated.ts.template
packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/my-component.ts.template
packages/@o3r/testing/src/public_api.ts
yarn.lock

Make o3r/localization optional peer dep in o3r/testing

fix: make o3r/localization optional dep in o3r/testing

---

packages/@o3r/core/package.json
packages/@o3r/storybook/src/styling/styling.helpers.ts
packages/@o3r/storybook/src/styling/styling.spec.ts
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/builders/style-extractor/index.ts
packages/@o3r/styling/schemas/style.metadata.schema.json
packages/@o3r/styling/src/core/styles.interface.ts

⚠️ Breaking change ⚠️ 
Modification of the schema for the styling extractor

refactor: breaking-change: modification of the schema for styling extractor

---

packages/@o3r/analytics/schematics/analytics-to-component/index.ts
packages/@o3r/configuration/schematics/configuration-to-component/index.ts
packages/@o3r/core/schematics/context-to-component/index.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/core/schematics/module/index.ts
packages/@o3r/core/schematics/ng-add-create/index.ts
packages/@o3r/localization/schematics/add-localization-key/index.ts
packages/@o3r/localization/schematics/localization-to-component/index.ts
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/testing/schematics/fixture-to-component/index.ts

ci: fix it tests

---

.github/workflows/audit.yml
.github/workflows/codeql.yml
.github/workflows/main.yml

Update the workflows to support Merge queue, when/if we decide to enable it

ci: add merge-group event to workflows

---

.github/workflows/main.yml

ci: fix merge group

---

packages/@ama-sdk/schematics/schematics/code-generator/code-generator.ts
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
packages/@ama-sdk/schematics/schematics/code-generator/swagger-java-generator/swagger-java.options.ts
packages/@ama-sdk/schematics/schematics/java/client-core/index.ts
packages/@ama-sdk/schematics/schematics/java/client-core/schema.json
packages/@ama-sdk/schematics/schematics/java/client-core/schema.ts
packages/@ama-sdk/schematics/schematics/ng-add/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts

fix: ng-add @ama-sdk/schematics and override tree

---

docs/components/PLACEHOLDERS.md
docs/rules-engine/how-to-use/placeholders.md

Enhances localized placeholder documentation.
Provides a guide on how to integrate i18n key translation in placeholders and explains limitations around parameters

feat: add documentation on placeholder dynamic documentation

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts

Fix https://github.com/AmadeusITGroup/otter/issues/524
Cherry-pick https://github.com/AmadeusITGroup/otter/pull/535

fix(component): configuration extractor to extract aliased types

---

.github/workflows/it-report.yml
.github/workflows/test-publish.yml
nx.json
packages/@ama-sdk/create/testing/jest.config.it.js
packages/@ama-sdk/generator-sdk/package.json
packages/@ama-sdk/generator-sdk/testing/jest.config.it.js
packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/testing/jest.config.it.js
packages/@o3r/core/testing/jest.config.it.js
packages/@o3r/localization/testing/jest.config.it.js
packages/@o3r/rules-engine/testing/jest.config.it.js
yarn.lock

ci: improve it-tests reports

---

.github/workflows/test-publish.yml
packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/testing/jest.config.it.js
packages/@ama-sdk/generator-sdk/testing/jest.config.it.js
packages/@ama-sdk/schematics/testing/jest.config.it.js
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/core/testing/jest.config.it.js
packages/@o3r/localization/testing/jest.config.it.js
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/rules-engine/testing/jest.config.it.js

ci: add timeouts for it-tests

---

packages/@o3r/core/schematics/convert-component/index.spec.ts
packages/@o3r/core/schematics/convert-component/index.ts
packages/@o3r/core/schematics/convert-component/schema.json
packages/@o3r/core/schematics/convert-component/schema.ts

add schematic option to select o3r component type

feat: add schematic option to select o3r component type

---

packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.generator.ts
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts

* Support debug for sdk generator
* Add associated documentation

fix: support debug for sdk generator and add doc

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md

* Fix a bug preventing to disable utils.Date usage using the vendor extension
* Add documentation associated

fix: sdk generator - date support and doc

---

packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts

improve metadata extraction warning message

feat: improve metadata extraction warning message

---

tools/github-actions/download-build-output/action.yml

ci: fix publish-pr

---

packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@ama-sdk/schematics/testing/MOCK_swagger.yaml

fix: support multiple type depending on the reponse code

---

.github/workflows/it-report.yml

ci: add support for matrix on it reports

---

.github/workflows/code-check.yml
nx.json
packages/@ama-sdk/generator-sdk/package.json
packages/@ama-sdk/generator-sdk/src/generators/core/index.ts
packages/@ama-sdk/generator-sdk/src/generators/dart-core/index.ts
packages/@ama-sdk/generator-sdk/src/generators/java-client-core/index.ts
packages/@ama-sdk/generator-sdk/src/generators/java-mdk-core/index.ts
packages/@ama-sdk/generator-sdk/src/generators/java-resteasy-client-core/index.ts
packages/@ama-sdk/generator-sdk/src/generators/swift-core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@o3r/core/schematics/component/container/index.ts
packages/@o3r/core/schematics/component/presenter/index.ts
packages/@o3r/core/schematics/page/index.ts
packages/@o3r/dev-tools/package.json
yarn.lock

ci: run unit tests also on windows

---

.github/workflows/it-report.yml

ci: split it report by matrix

---

packages/@o3r/core/package.json
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
packages/@o3r/core/schematics/rule-factories/index.ts
packages/@o3r/core/schematics/rule-factories/monorepo/index.ts
packages/@o3r/core/schematics/rule-factories/o3r-basic-updates/index.ts
packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/core/schematics/shared/presets/basic.preset.ts
packages/@o3r/core/schematics/shared/presets/cms.preset.ts
packages/@o3r/core/schematics/shared/presets/helpers.ts
packages/@o3r/create/src/index.ts
packages/@o3r/schematics/src/index.spec.ts
packages/@o3r/schematics/src/interfaces/angular-workspace.ts
packages/@o3r/schematics/src/utility/collection.spec.ts
packages/@o3r/schematics/src/utility/collection.ts
packages/@o3r/schematics/src/utility/monorepo.ts
yarn.lock

- o3r/create will build a monorepo skeleton

o3r create workspace

---

packages/@o3r/core/schematics/shared/presets/helpers.ts

fix: do nothing when presets modules list is empty

---

packages/@o3r/analytics/schematics/analytics-to-component/index.spec.ts
packages/@o3r/analytics/schematics/analytics-to-component/index.ts
packages/@o3r/configuration/schematics/configuration-to-component/index.spec.ts
packages/@o3r/configuration/schematics/configuration-to-component/index.ts
packages/@o3r/core/package.json
packages/@o3r/core/schematics/context-to-component/index.spec.ts
packages/@o3r/core/schematics/context-to-component/index.ts
packages/@o3r/localization/package.json
packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
packages/@o3r/localization/schematics/add-localization-key/index.ts
packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
packages/@o3r/localization/schematics/localization-to-component/index.ts
packages/@o3r/schematics/src/utility/component.ts
packages/@o3r/testing/package.json
packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
packages/@o3r/testing/schematics/fixture-to-component/index.ts
packages/@o3r/third-party/package.json
packages/@o3r/third-party/schematics/iframe-to-component/index.spec.ts
packages/@o3r/third-party/schematics/iframe-to-component/index.ts
yarn.lock

improve schematic ux by proposing to run schematic when the main failed for a known reason
- :rocket: Feature #480

feat: improve schematic ux by proposing to run schematic when the main failed for a known reason

---

.github/workflows/code-check.yml

ci: increase node memory size for unit tests

---

packages/@o3r/localization/schematics/ng-add/index.ts

fix: setup of @o3r/localization schematics

---

packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
packages/@o3r/localization/schematics/add-localization-key/index.ts
packages/@o3r/schematics/src/utility/index.ts
packages/@o3r/schematics/src/utility/question.ts

fix: question to change localization key name

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/fixture.jest.mustache
packages/@ama-sdk/schematics/testing/MOCK_swagger.yaml

fix: missing status code response when multiple response with same type

---

packages/@o3r/store-sync/src/core/storage-sync.ts

fix: null pointer on this in storage sync

---

apps/vscode-extension/package.json
apps/vscode-extension/src/commands/generate/enrich-component/analytics-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/common.ts
apps/vscode-extension/src/commands/generate/enrich-component/configuration-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/context-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/convert-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/fixture-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/iframe-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/index.ts
apps/vscode-extension/src/commands/generate/enrich-component/localization-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/rules-engine-to-component.commands.ts
apps/vscode-extension/src/commands/generate/enrich-component/theming-to-component.commands.ts
apps/vscode-extension/src/extension.ts

feat(vscode ext): support of new generators

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/ng-add/schema.json
packages/@o3r/core/schematics/ng-add/schema.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.sanity.ts.template
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.ts.template
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/sanity/__sanity@dasherize__.e2e.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/scenarios/__name@dasherize__.e2e-playwright-spec.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/utils/base-scenario.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/utils/index.ts
packages/@o3r/testing/schematics/ng-add/schema.json
packages/@o3r/testing/schematics/ng-add/schema.ts
yarn.lock

The result of `npx @angular/cli@16.2 add @o3r/testing --project-name=my-app` is https://github.com/vscaiceanu-1a/o3r-testing-validation/commit/55283a4b1e17664a5d57aace59346b1c407015e1
- :rocket: Feature https://github.com/AmadeusITGroup/otter/issues/657

feat: playwright install part of o3r/testing

---

packages/@o3r/core/schematics/page/index.spec.ts
packages/@o3r/core/schematics/page/index.ts

fix: add missing routing module in the page module

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/jest.config.js
packages/@o3r/core/package.json
packages/@o3r/core/schematics/sdk/index.ts
packages/@o3r/core/schematics/sdk/templates/jest.config.js.template
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.js.template
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.ut.js.template

- Fixes https://github.com/AmadeusITGroup/otter/issues/602

fix: jest config for o3r/testing schematics

---

packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
packages/@o3r/core/package.json
packages/@o3r/rules-engine/README.md
packages/@o3r/rules-engine/collection.json
packages/@o3r/rules-engine/schematics/facts-service/index.spec.ts
packages/@o3r/rules-engine/schematics/facts-service/index.ts
packages/@o3r/rules-engine/schematics/facts-service/schema.json
packages/@o3r/rules-engine/schematics/facts-service/schema.ts
packages/@o3r/rules-engine/schematics/facts-service/templates/__name__.facts.ts.template

feat: schematic to generate facts service

---

docs/rules-engine/examples/runtime-facts.md
docs/rules-engine/how-it-works/operators.md
docs/rules-engine/how-it-works/rule.md
docs/rules-engine/how-it-works/ruleset.md
docs/rules-engine/operators.md
docs/rules-engine/rule.md
docs/rules-engine/ruleset.md

docs: equals operator typo

---

.github/workflows/code-check.yml

ci: dont run windows ut on branch builds

---

packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
packages/@o3r/rules-engine/README.md
packages/@o3r/rules-engine/collection.json
packages/@o3r/rules-engine/schematics/operator/index.spec.ts
packages/@o3r/rules-engine/schematics/operator/index.ts
packages/@o3r/rules-engine/schematics/operator/schema.json
packages/@o3r/rules-engine/schematics/operator/schema.ts
packages/@o3r/rules-engine/schematics/operator/templates/__name__.operator.ts.template
packages/@o3r/rules-engine/src/engine/operator/operator.interface.ts

feat(generator): schematic to generate an operator

---

packages/@o3r/apis-manager/schematics/ng-add/index.ts
packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/components/schematics/ng-add/index.ts
packages/@o3r/configuration/schematics/ng-add/index.ts
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/ng-add/schema.json
packages/@o3r/core/schematics/ng-add/schema.ts
packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
packages/@o3r/core/schematics/rule-factories/o3r-basic-updates/index.ts
packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
packages/@o3r/core/schematics/rule-factories/playwright/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
packages/@o3r/extractors/schematics/ng-add/index.ts
packages/@o3r/localization/schematics/localization-base/index.ts
packages/@o3r/localization/schematics/ng-add/index.ts
packages/@o3r/mobile/schematics/ng-add/index.ts
packages/@o3r/rules-engine/schematics/ng-add/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/schematics/src/tasks/ng-add/index.ts
packages/@o3r/schematics/src/utility/loaders.ts
packages/@o3r/schematics/src/utility/modules.ts
packages/@o3r/store-sync/schematics/ng-add/index.ts
packages/@o3r/storybook/schematics/ng-add/index.ts
packages/@o3r/styling/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/index.ts

feat: ng add of packages will run depending of project type

---

packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/schematics/src/utility/modules.ts

improvement: reduce number of installs during ng-add

---

.github/workflows/main.yml
tools/github-actions/new-version/readme.md
tools/github-actions/new-version/src/main.ts

setup release branch name regexp
failure if version number cannot be computed

fix(new-version): setup release branch name regexp + failure if version number cannot be computed

---

.github/workflows/audit.yml
.github/workflows/clean-cache.yml
.github/workflows/code-check.yml
.github/workflows/codeql.yml
.github/workflows/documentation.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml
.github/workflows/pr-labels.yml
.github/workflows/publish.yml
.renovaterc.json

feat: add github action in renovate checks
feat: bump github action

feat: bump github action

---

packages/@o3r/core/schematics/component/presenter/index.ts

component style should be wrapped into the component selector

fix(components): component style should be wrapped into the component selector

---

packages/@o3r/apis-manager/schematics/helpers/update-api-deps/index.ts
packages/@o3r/apis-manager/schematics/ng-add/index.ts
packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/components/schematics/cms-adapter/index.ts
packages/@o3r/core/schematics/component/container/index.spec.ts
packages/@o3r/core/schematics/component/presenter/index.spec.ts
packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
packages/@o3r/core/schematics/rule-factories/component/common.ts
packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/core/schematics/shared/presets/helpers.ts
packages/@o3r/core/schematics/shared/presets/preset.interface.ts
packages/@o3r/core/testing/setup-jest.ts
packages/@o3r/extractors/schematics/cms-adapter/index.ts
packages/@o3r/extractors/schematics/ng-add/index.ts
packages/@o3r/localization/schematics/cms-adapter/index.ts
packages/@o3r/localization/schematics/localization-base/index.ts
packages/@o3r/localization/schematics/ng-add/index.ts
packages/@o3r/rules-engine/schematics/cms-adapter/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/schematics/src/utility/file-info.ts
packages/@o3r/schematics/src/utility/modules.ts
packages/@o3r/styling/schematics/cms-adapter/index.ts
packages/@o3r/styling/schematics/ng-add/index.ts
packages/@o3r/styling/schematics/ng-add/theme-files/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/index.ts

fix: ng-add, some files incorrectly generated in the context of monorepo

---

packages/@o3r/core/schematics/component/presenter/index.ts

fix(schematics): return the tree in the schematics

---

packages/@o3r/testing/package.json
packages/@o3r/testing/src/core/playwright/element.ts
yarn.lock

Use @playwright/test instead of playwright
- :bug: Fixes #735

fix(playwright): use @playwright/test instead of playwright

---

packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/create/src/index.ts
packages/@o3r/schematics/src/utility/monorepo.ts

fix: run monorepo setup when no standalone app

---

packages/@o3r/core/README.md
packages/@o3r/core/collection.json
packages/@o3r/core/schematics/application/index.spec.ts
packages/@o3r/core/schematics/application/index.ts
packages/@o3r/core/schematics/application/schema.json
packages/@o3r/core/schematics/application/schema.ts
packages/@o3r/core/schematics/application/templates/package.json.template

feat(schematics): add otter application to monorepo

---

packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/monorepo/index.ts

fix: scripts in package json at monorepo creation

---

packages/@o3r/apis-manager/schematics/ng-add/index.ts
packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/components/schematics/ng-add/index.ts
packages/@o3r/configuration/schematics/ng-add/index.ts
packages/@o3r/core/schematics/component/container/index.ts
packages/@o3r/core/schematics/component/presenter/index.ts
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/page/index.ts
packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
packages/@o3r/core/schematics/store/entity-async/index.ts
packages/@o3r/core/schematics/store/entity-sync/index.ts
packages/@o3r/core/schematics/store/simple-async/index.ts
packages/@o3r/core/schematics/store/simple-sync/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
packages/@o3r/extractors/schematics/ng-add/index.ts
packages/@o3r/localization/schematics/ng-add/index.ts
packages/@o3r/mobile/schematics/ng-add/index.ts
packages/@o3r/rules-engine/schematics/ng-add/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/store-sync/schematics/ng-add/index.ts
packages/@o3r/styling/schematics/ng-add/index.ts
packages/@o3r/test-helpers/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/index.ts
packages/@o3r/testing/schematics/playwright/sanity/index.ts
packages/@o3r/testing/schematics/playwright/scenario/index.ts

fix: missing project-name in ng-add schematics

---

packages/@o3r/core/package.json
packages/@o3r/core/schematics/application/index.ts

`angular.json`
Before:
```json
"my-app": {
"projectType": "application",
"schematics": {
"@schematics/angular:component": {
"style": "scss"
}
},
"root": "/apps/my-app",
"sourceRoot": "/apps/my-app/src",
"prefix": "app",
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:browser",
"options": {
"outputPath": "dist/my-app",
"index": "/apps/my-app/src/index.html",
"main": "/apps/my-app/src/main.ts",
"polyfills": [
"zone.js"
],
"tsConfig": "/apps/my-app/tsconfig.app.json",
"inlineStyleLanguage": "scss",
"assets": [
"/apps/my-app/src/favicon.ico",
"/apps/my-app/src/assets"
],
"styles": [
"/apps/my-app/src/styles.scss"
],
"scripts": []
},
...
```
After:
```json
"my-app-2": {
"projectType": "application",
"schematics": {
"@schematics/angular:component": {
"style": "scss"
}
}, …
```

fix: ng g application schematics needs relative path

---

apps/showcase/project.json
nx.json

fix: showcase build fail on initial setup

---

packages/@o3r/rules-engine/src/services/rules-engine.effect.spec.ts
packages/@o3r/rules-engine/src/services/rules-engine.effect.ts

perf: performance improvement for jsonpath in placeholders

---

packages/@o3r/core/schematics/library/index.ts

fix: library generator correct path and name

---

package.json

adding registry for verdaccio for `@ama-terasu`

fix: verdaccio ama-terasu registry

---

packages/@o3r/core/schematics/sdk/index.ts

- :bug: Fixes 
- :rocket: Feature #784

fix: monorepo - chain shell and core sdk generators

---

packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/generic-updates/index.ts
packages/@o3r/core/schematics/rule-factories/index.ts

fix: git ignore node_modules of monorepo projects

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-class.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component-module.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts
packages/@o3r/components/schemas/component.metadata.schema.json
packages/@o3r/components/src/core/component.output.ts

deprecate unused component metadata 
related to https://github.com/AmadeusITGroup/otter/pull/759

feat(metadata): deprecate unused component metadata properties

---

packages/@o3r/analytics/schematics/index.it.spec.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular-with-o3r-core.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-blank.ts
packages/@o3r/test-helpers/src/utilities/create-with-lock.ts
packages/@o3r/test-helpers/src/utilities/package-manager.ts

Add an IT test with monorepo for o3r/analytics and @o3r/core

ci: draft of it test for monorepo

---

.github/workflows/it-tests.yml

ci: remove internal packages from npm cache for it-tests

---

.github/workflows/it-tests.yml

ci: remove corrupted files when cleaning npm cache

---

apps/showcase/tsconfig.app.json

fix: showcase app build

---

packages/@o3r/core/schematics/store/entity-async/index.ts
packages/@o3r/core/schematics/store/entity-async/templates/__storeName@dasherize__.state.ts
packages/@o3r/core/schematics/store/entity-sync/index.ts
packages/@o3r/core/schematics/store/entity-sync/templates/__storeName@dasherize__.state.ts
packages/@o3r/core/schematics/store/simple-async/index.ts
packages/@o3r/core/schematics/store/simple-sync/index.ts

fix: trim inputs to avoid extra - and spaces in the names

---

apps/showcase/src/app/configuration/configuration.template.html

fix: showcase configuration not working

---

apps/showcase/src/app/app.component.html
apps/showcase/src/app/app.module.ts
apps/showcase/src/components/utilities/index.ts
apps/showcase/src/components/utilities/scroll-back-top/README.md
apps/showcase/src/components/utilities/scroll-back-top/index.ts
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.component.ts
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.spec.ts
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.style.scss
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.template.html

feat: showcase scroll top button

---

.github/workflows/main.yml
.github/workflows/publish.yml

Add [npm provenance](https://docs.npmjs.com/generating-provenance-statements)

feat: npm provenance

---

docs/core/OTTER_ANGULAR_TOOLS.md
packages/@o3r/core/builders.json
packages/@o3r/core/builders/run-script/index.ts
packages/@o3r/core/builders/run-script/schema.json
packages/@o3r/core/builders/run-script/schema.ts
packages/@o3r/core/schematics/sdk/rules/rules.ng.ts

feat: run script builder

---

apps/showcase/src/app/configuration/configuration.template.html
apps/showcase/src/app/dynamic-content/dynamic-content.template.html
apps/showcase/src/app/localization/localization.template.html
apps/showcase/src/app/rules-engine/rules-engine.template.html

feat: showcase - add some explanations before the examples

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template

fix: sdk run clear-index script

---

packages/@o3r/schematics/src/rule-factories/eslint-fix/index.ts
packages/@o3r/schematics/src/tasks/eslint/index.ts

run linter task during schematics

fix: run linter task during schematics

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
yarn.lock

Merge/9.2 9.3

---

packages/@o3r/azure-tools/.compodocrc.json
packages/@o3r/azure-tools/.eslintrc.js
packages/@o3r/azure-tools/.gitignore
packages/@o3r/azure-tools/README.md
packages/@o3r/azure-tools/collection.json
packages/@o3r/azure-tools/jest.config.js
packages/@o3r/azure-tools/package.json
packages/@o3r/azure-tools/project.json
packages/@o3r/azure-tools/schematics/ng-add/index.ts
packages/@o3r/azure-tools/schematics/ng-add/schema.json
packages/@o3r/azure-tools/schematics/ng-add/schema.ts
packages/@o3r/azure-tools/src/cli/comment-pr.ts
packages/@o3r/azure-tools/src/helpers/azure/index.ts
packages/@o3r/azure-tools/src/helpers/azure/pull-requests.service.ts
packages/@o3r/azure-tools/src/helpers/index.ts
packages/@o3r/azure-tools/src/index.spec.ts
packages/@o3r/azure-tools/src/public_api.ts
packages/@o3r/azure-tools/tsconfig.build.json
packages/@o3r/azure-tools/tsconfig.builders.json
packages/@o3r/azure-tools/tsconfig.doc.json
packages/@o3r/azure-tools/tsconfig.eslint.json
packages/@o3r/azure-tools/tsconfig.json
packages/@o3r/azure-tools/tsconfig.spec.json
packages/@o3r/dev-tools/package.json
packages/@o3r/dev-tools/src/cli/comment-pr.ts
tsconfig.base.json
tsconfig.build.json
yarn.lock

create azure-tools package and move script from dev-tools into it

feat: create azure-tools package and move script from dev-tools into it

---

apps/showcase/src/components/showcase/configuration/configuration-pres.config.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
packages/@o3r/components/src/core/component.output.ts
packages/@o3r/core/src/core/interfaces/configuration.ts
packages/@o3r/eslint-config-otter/typescript.cjs
packages/@o3r/extractors/src/utils/config-doc.ts

Add configuration widget support
Related to https://github.com/AmadeusITGroup/otter/pull/705

feat: add configuration widget support

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/core/schematics/ng-add/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@o3r/mobile/src/capacitor/storage/rehydrater.module.ts
yarn.lock

Cherry pick : https://github.com/AmadeusITGroup/otter/pull/870

fix: remove mandatory @o3r/schematics dependency on @ama-sdk/core

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/CONTRIBUTING.md
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/jest.config.js
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/scripts/override-readme.js
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/fixtures/jest/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/helpers/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/tsconfig.build.json
packages/@o3r/core/schematics/application/index.ts
packages/@o3r/core/schematics/library/index.spec.ts
packages/@o3r/core/schematics/library/index.ts
packages/@o3r/core/schematics/library/rules/rules.ng.ts
packages/@o3r/core/schematics/library/rules/rules.nx.ts
packages/@o3r/core/schematics/sdk/index.ts
packages/@o3r/core/schematics/sdk/rules/update-ts-paths.rule.ts

fix: align names on monorepo packages

---

apps/vscode-extension/README.md
apps/vscode-extension/src/extension.ts
apps/vscode-extension/src/intellisense/configuration.ts

add configuration widget intellisense

feat: add configuration widget intellisense

---

packages/@o3r/core/schematics/library/rules/rules.ng.ts
packages/@o3r/core/schematics/sdk/rules/update-ts-paths.rule.ts

follow up on https://github.com/AmadeusITGroup/otter/pull/885

fix: code improvement

---

.github/workflows/publish-pr.yml

fix: missing permission to sign pr npm package publish

---

apps/showcase/.eslintrc.js
docs/linter/eslint-plugin/rules.md
docs/linter/eslint-plugin/rules/o3r-widget-tags.md
packages/@o3r/eslint-config-otter/typescript.cjs
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/o3r-widget-tags/o3r-widget-tags.spec.ts
packages/@o3r/eslint-plugin/src/rules/o3r-widget-tags/o3r-widget-tags.ts
packages/@o3r/extractors/src/index.spec.ts
packages/@o3r/extractors/src/utils/config-doc.spec.ts
packages/@o3r/extractors/src/utils/config-doc.ts

Rule for `@o3rWidget` and `@o3rWidgetParam` tags

feat(eslint): rule for @o3rWidget and @o3rWidgetParam tags

---

apps/showcase/.eslintrc.js
apps/showcase/src/components/showcase/configuration/configuration-pres.config.ts
packages/@o3r/core/package.json

fix(showcase): eslint configuration o3rWidget rule
fix(core): zone.js wrong dependency

fix(showcase): eslint configuration o3rWidget rule

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-class.extractor.ts

include only o3r component class

fix(extractor): include only o3r component class

---

apps/vscode-extension/package.json
apps/vscode-extension/src/intellisense/configuration.ts
yarn.lock

use eslint config for @o3rWidget and @o3rWidgetParam intellisense
https://github.com/AmadeusITGroup/otter/assets/52541061/0b7f5d0a-52c9-4a9b-a3f4-a71e80e68e98

feat(vscode-ext): use eslint config for @o3rWidget and @o3rWidgetParam intellisense

---

package.json
yarn.lock

Add manual resolution for the babel/traverse package to avoid major update on a patch to fix issue on @babel/traverse version
- :bug: Fixes[ #(Audit issue)](https://github.com/AmadeusITGroup/otter/security/dependabot/37)

fix: remove critical dependencies

---

apps/vscode-extension/src/intellisense/configuration.ts

snippets for configuration tags

feat(vscode-ext): snippets for configuration tags

---

tools/github-actions/audit/src/main.ts

fix: npm audit does not detect vulnerabilities

---

.eslintignore
package.json

fix: harmonize fail on windows (command line too long)

---

apps/showcase/src/components/showcase/sdk/sdk-pres.component.ts
apps/showcase/src/components/showcase/sdk/sdk-pres.template.html

fix(showcase): handle error response from the api on sdk page

---

SECURITY.md

Update supported Otter versions

feat: update supported versions in security file

---

packages/@o3r/rules-engine/src/components/rules-engine/rule-condition/rule-condition-pres.component.ts
packages/@o3r/rules-engine/src/components/rules-engine/rule-condition/rule-condition-pres.template.html

fix: remove undefined on rhs for rules overview in debug panel

---

packages/@o3r/store-sync/README.md

Update documentation related to the store smart sync and how to deactivate it.
- :rocket: Feature [Smart Sync](https://github.com/AmadeusITGroup/otter/pull/658)

chore: document smart sync behaviour

---

packages/@o3r/rules-engine/src/engine/debug/engine.debug.ts
packages/@o3r/rules-engine/src/engine/ruleset-executor.ts
packages/@o3r/store-sync/src/sync-storage/storage-sync.ts

fix: rules engine triggers with duplicates

---

packages/@o3r/dev-tools/src/cli/checks/yarn-check.ts

chore: deprecate yarn-check

---

yarn.lock

https://github.com/AmadeusITGroup/otter/security/dependabot/40

fix: crypto-js security issue

---

apps/showcase/project.json

fix(showcase): build fails when localization-metadata are missing

---

packages/@o3r/dev-tools/src/cli/generate-package-exports.ts
packages/@o3r/dev-tools/src/cli/package-export.ts
packages/@o3r/dev-tools/src/cli/peer-dependencies-updater.ts
packages/@o3r/dev-tools/src/utils/check-peer-deps.ts
packages/@o3r/dev-tools/src/utils/is-package-installed.ts
packages/@o3r/dev-tools/src/utils/package-manager.ts
packages/@o3r/dev-tools/src/utils/string.ts
packages/@o3r/dev-tools/src/utils/update-peer-dependencies.ts

chore: deprecate unused scripts

---

.github/ISSUE_TEMPLATE/1-O3R-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/2-AMA-SDK-ISSUE-FORM.yaml

ci: update issues template

---

.github/workflows/deploy-showcase.yml
apps/showcase/src/app/app-routing.module.ts
apps/showcase/src/index.html

https://fpaul-1a.github.io/otter

feat: deploy showcase in github pages

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java

fix: sdk generator issue with empty mime type

---

apps/showcase/src/app/app.component.html
apps/showcase/src/app/home/home.style.scss
apps/showcase/src/app/home/home.template.html
apps/showcase/src/components/showcase/sdk/sdk-pres.style.scss
apps/showcase/src/components/showcase/sdk/sdk-pres.template.html
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.style.scss

fix(showcase): responsive scrolls

---

package.json
tools/@o3r/build-helpers/scripts/prepare-publish.mjs

feat: add homepage to package.json

---

apps/showcase/project.json
packages/@o3r/localization/builders/helpers/localization.generator.ts

fix(localization): extractor considers internal refs as library refs

---

apps/showcase/src/components/showcase/basic/basic-pres.style.scss
apps/showcase/src/components/showcase/configuration/configuration-pres.template.html
apps/showcase/src/components/showcase/dynamic-content/dynamic-content-pres.template.html
apps/showcase/src/components/showcase/localization/localization-pres.template.html
apps/showcase/src/components/showcase/rules-engine/rules-engine-pres.template.html

fix(showcase): fix bubble

---

packages/@o3r/dev-tools/src/cli/aql-artifact-cleaner.ts
packages/@o3r/dev-tools/src/cli/git-release-management.ts
packages/@o3r/dev-tools/src/cli/set-version.ts
packages/@o3r/dev-tools/src/cli/version-harmonize.ts
packages/@o3r/dev-tools/src/helpers/git-release-management/git-release-management.ts

Deprecate unused scripts from dev-tools package

feat(dev-tools): deprecate unused scripts from dev-tools package

---

packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/builders/style-extractor/index.ts
packages/@o3r/styling/builders/style-extractor/schema.json
packages/@o3r/styling/builders/style-extractor/schema.ts

Add option to throw when invalid scss value provided

feat(extractor): add option to throw when invalid scss value provided

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

fix: prevent extra newline in revivers

---

packages/@ama-sdk/core/schematics/ng-add/schema.json
packages/@ama-sdk/schematics/schematics/ng-add/schema.json
packages/@o3r/analytics/schematics/ng-add/schema.json
packages/@o3r/application/schematics/ng-add/schema.json
packages/@o3r/core/schematics/ng-add-create/templates/schematics/ng-add/schema.json.template
packages/@o3r/eslint-config-otter/schematics/ng-add/schema.json
packages/@o3r/eslint-plugin/schematics/ng-add/schema.json
packages/@o3r/extractors/schematics/ng-add/schema.json
packages/@o3r/forms/schematics/ng-add/schema.json
packages/@o3r/logger/schematics/ng-add/schema.json
packages/@o3r/mobile/schematics/ng-add/schema.json
packages/@o3r/routing/schematics/ng-add/schema.json
packages/@o3r/store-sync/schematics/ng-add/schema.json
packages/@o3r/storybook/schematics/ng-add/schema.json
packages/@o3r/testing/schematics/ng-add/schema.json
packages/@o3r/third-party/schematics/ng-add/schema.json
packages/@o3r/workspace/schematics/ng-add/project-setup.ts

Install @ama-sdk/schematics when adding @o3r/core
- :rocket: Feature #1020

feat: install @ama-sdk/schematics when adding @o3r/core

---

packages/@o3r/core/schematics/ng-add/project-setup/index.ts

Install @o3r/ngx-prefetch on app only if dep is present in project package.json
- :bug: Fixes #1019

fix: install @o3r/ngx-prefetch on app only if dep is present in project package.json

---

packages/@ama-sdk/core/.npmignore
packages/@ama-sdk/core/tsconfig.builders.json
packages/@ama-sdk/core/tsconfig.spec.json
packages/@o3r/core/.npmignore
packages/@o3r/core/tsconfig.builders.json
packages/@o3r/core/tsconfig.spec.json

Exclude testing files from the build

fix: exclude testing files from the build

---

packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.spec.ts
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/builders/style-extractor/index.ts
packages/@o3r/styling/scss/theming/_mixins.scss
packages/@o3r/styling/scss/theming/mixins.spec.ts
packages/@o3r/styling/tsconfig.spec.json

fix(styling): update details of variable of null is provided

---

packages/@ama-sdk/create/src/index.ts

fix(sdk): call yarn set version at sdk creation

---

packages/@o3r/core/schematics/sdk/rules/update-ts-paths.rule.ts
packages/@o3r/testing/schematics/ng-add/fixture/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/templates/project/jest.config.js.template

fix: testing config at generation time

---

apps/github-cascading-app/src/cascading/templates/pull-request-content.ejs

fix(cascading): template to integrate the push command

fix(cascading): template to integrate the push command

---

packages/@o3r/core/package.json
packages/@o3r/workspace/schematics/sdk/rules/clean-standalone.rule.ts

fix: remove not used scripts in monorepo sdk

---

packages/@o3r/analytics/schematics/index.it.spec.ts
packages/@o3r/configuration/schematics/index.it.spec.ts
packages/@o3r/core/schematics/component/index.ts
packages/@o3r/core/schematics/component/presenter/index.ts
packages/@o3r/core/schematics/component/presenter/schema.json
packages/@o3r/core/schematics/component/schema.json
packages/@o3r/core/schematics/component/structures.types.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/index.it.spec.ts
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/styling/schematics/index.it.spec.ts
packages/@o3r/testing/schematics/index.it.spec.ts

Generate a simple component by default

feat(component): generate a simple component by default

---

packages/@ama-sdk/core/package.json

fix: package.json in outputs for ama-sdk/core

---

jest.config.it.js

ci: fix it tests reports missing

---

packages/@ama-sdk/schematics/jest.config.js

test: increase timeout for ama-sdk-schematics unit tests

---

docs/linter/eslint-plugin/rules/no-inner-html.md
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/template/no-inner-html/no-inner-html.spec.ts
packages/@o3r/eslint-plugin/src/rules/template/no-inner-html/no-inner-html.ts

New template rule to detect innerhtml
- :rocket: Feature #1086

feat(linter): new template rule to detect innerhtml

---

packages/@o3r/workspace/schematics/application/index.ts

[cascading] from 9.4 to 9.5.0-rc

---

README.md

fix: missing return to line on readme

---

packages/@o3r/logger/package.json
packages/@o3r/logger/src/services/fullstory-logger-client/fullstory-logger-client.ts
yarn.lock

chore: upgrade fullstory major version

---

packages/@o3r/apis-manager/schematics/helpers/update-api-deps/index.ts
packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/core/schematics/page/index.ts
packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/localization/schematics/localization-base/index.ts
packages/@o3r/schematics/src/rule-factories/dev-tools/devtools-registration.ts
packages/@o3r/schematics/src/utility/file-info.ts
packages/@o3r/schematics/src/utility/modules.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular.ts
packages/@o3r/test-helpers/src/utilities/angular.ts
packages/@o3r/workspace/schematics/application/schema.json

feat: support standalone applications

---

packages/@o3r/storybook/package.json
yarn.lock

Update React type definition dependency range to reduce Renovate noice

chore(storybook): bump react dep

---

apps/showcase/project.json
packages/@o3r/components/builders/component-extractor/index.ts
packages/@o3r/localization/builders/helpers/localization.generator.ts
packages/@o3r/localization/builders/localization-extractor/index.ts
packages/@o3r/localization/builders/localization-extractor/schema.json
packages/@o3r/localization/builders/localization-extractor/schema.ts
packages/@o3r/localization/schemas/localization.metadata.schema.json

Validation on localization metadata
- :bug: Fixes #1136

fix(loc): validation on localization metadata

---

packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/plugins/core/fetch-plugin.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

Stop and restart the timeout fetch plugin in case a specific event interrumpts the fetch request.
Add event emitter to pause the timeout if an imperva captcha has been detected.

feat: captcha support on sdk plugins

---

packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/plugins/core/fetch-plugin.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

[cascading] Merge release 8.3 into release 9.5

---

package.json
packages/@o3r/application/package.json
packages/@o3r/core/package.json
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/core/src/utils/deep-fill/deep-fill.ts
packages/@o3r/eslint-plugin/package.json
packages/@o3r/eslint-plugin/project.json
packages/@o3r/schematics/src/tasks/eslint/index.ts
packages/@o3r/schematics/src/utility/matching-peers.ts
packages/@o3r/store-sync/package.json
packages/@o3r/store-sync/src/core/storage-sync.ts
packages/@o3r/store-sync/src/deep-fill/deep-fill.spec.ts
packages/@o3r/store-sync/src/deep-fill/deep-fill.ts
packages/@o3r/stylelint-plugin/.eslintrc.js
packages/@o3r/stylelint-plugin/collection.json
packages/@o3r/stylelint-plugin/package.json
packages/@o3r/stylelint-plugin/project.json
packages/@o3r/stylelint-plugin/schematics/ng-add/index.ts
packages/@o3r/stylelint-plugin/schematics/ng-add/schema.json
packages/@o3r/stylelint-plugin/schematics/ng-add/schema.ts
packages/@o3r/stylelint-plugin/tsconfig.builders.json
packages/@o3r/workspace/project.json
tools/github-actions/setup/action.yml
yarn.lock

Remove dependency to @ama-sdk/core to reduce the postinstall time.
This is resulting to a breaking change on `deepFill` (in implementation, not interface)
Alowing script greatly reducing build time (on Mac)

feat: remove dependency to @ama-sdk/core

---

.renovaterc.json

Tested here on my fork https://github.com/fpaul-1A/otter/pull/7

ci(renovate): update config with ignored packages

---

apps/github-cascading-app/src/cascading/templates/pull-request-content.ejs

Fix cascading Pull Request message content

fix(cascading): the template of the cascading pull request content

---

packages/@o3r/eslint-plugin/src/rules/template/template-async-number-limitation/template-async-number-limitation.ts
packages/@o3r/eslint-plugin/src/rules/typescript/o3r-widget-tags/o3r-widget-tags.ts

Use options from 2nd argument
- :bug: Fixes #1161

fix(1161): use options from 2nd argument

---

.github/workflows/publish.yml
apps/github-cascading-app/src/cascading/templates/pull-request-content.ejs

fix(cascading): publish cascading application on main branch

fix(cascading): publish cascading application on main branch

---

packages/@ama-sdk/core/src/plugins/timeout/readme.md

Enhance documentation on timeout pause behaviour

feat: document timeout pause event

---

nx.json

Remove the dependency inner package builds to increase parallelization

feat: removed the dependency inner package builds

---

jest.config.ut.js
nx.json
packages/@o3r/configuration/.gitignore
packages/@o3r/localization/.gitignore
packages/@o3r/test-helpers/src/utilities/virtual-fs.ts

Fix NX input to re-run correctly the tests

fix: nx input for tests

---

apps/vscode-extension/package.json
apps/vscode-extension/src/extension.ts
apps/vscode-extension/src/intellisense/styling.ts

Intellisense for styling variable
https://github.com/AmadeusITGroup/otter/assets/52541061/4de2350a-6fb8-495b-a569-b7e2e357c822
- :rocket: Feature #718

feat(#718): intellisense for styling variable

---

packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/builders/generate-css/schema.json
packages/@o3r/design/builders/generate-css/schema.ts
packages/@o3r/design/collection.json
packages/@o3r/design/jest.config.js
packages/@o3r/design/package.json
packages/@o3r/design/schematics/ extract-token/index.spec.ts
packages/@o3r/design/schematics/ extract-token/index.ts
packages/@o3r/design/schematics/ extract-token/schema.json
packages/@o3r/design/schematics/ extract-token/schema.ts
packages/@o3r/design/schematics/ng-add/index.ts
packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts
packages/@o3r/design/src/core/design-token/design-token.spec.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-definition.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-updater.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-value.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-definition.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-value.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/sass/design-token-definition.renderers.spec.ts
packages/@o3r/design/src/core/design-token/renderers/sass/design-token-definition.renderers.ts
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/package.json
tsconfig.base.json
tsconfig.build.json
yarn.lock

Provide schematic to generate Design Token from Scss Otter helpers

feat: add schematic to generate design token specification file

---

.github/workflows/main.yml
tools/github-actions/cascading/readme.md
tools/github-actions/cascading/src/helpers.spec.ts
tools/github-actions/cascading/src/helpers.ts
tools/github-actions/new-version/action.yml
tools/github-actions/new-version/readme.md
tools/github-actions/new-version/src/new-version.spec.ts
tools/github-actions/new-version/src/new-version.ts

fix: prerelease tags

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template

fix: unrecognized pattern on generated sdk lint script

---

packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts

Add watch mode design token package task.
- :rocket: Feature #1236

feat(design): register watch mode to design ngAdd

---

packages/@ama-sdk/core/schematics/ng-add/index.spec.ts

fix: unit tests failing when using telemetry

---

.github/workflows/code-check.yml
.gitignore

fix: turn markdown links check optional for publish

---

.renovaterc.json

ci(renovate): remove outdated renovate package rules

---

apps/showcase/package.json
package.json
packages/@ama-sdk/core/package.json
packages/@ama-sdk/showcase-sdk/package.json
packages/@ama-terasu/cli/package.json
packages/@o3r/analytics/package.json
yarn.lock

chore(deps): update minor dependencies (main)

---

.github/workflows/code-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
package.json
packages/@o3r/components/package.json
packages/@o3r/rules-engine/package.json
tools/github-actions/setup/action.yml
yarn.lock

chore(deps): update major dependencies (main)

---

packages/@ama-sdk/create/README.md
packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/README.md
packages/@o3r/create/src/index.ts

fix: allow only npm for create commands

---

docs/design/TECHNICAL_DOCUMENTATION.md
packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/builders/generate-css/schema.json
packages/@o3r/design/builders/generate-css/schema.ts
packages/@o3r/design/schemas/design-token.schema.json
packages/@o3r/design/src/core/design-token/design-token-specification.interface.ts
packages/@o3r/design/src/core/design-token/design-token.spec.ts
packages/@o3r/design/src/core/design-token/parsers/design-token-parser.interface.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-definition.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-value.renderers.spec.ts
packages/@o3r/design/src/core/design-token/renderers/css/design-token-value.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/sass/design-token-definition.renderers.spec.ts
packages/@o3r/design/src/core/design-token/renderers/sass/design-token-definition.renderers.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

Support the case where a Design Token value refer an not existing variable

feat: support missing design token references

---

packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/package.json
packages/@o3r/create/src/index.ts
yarn.lock

Run ngAdd in new project context
- :bug: fixes #1203

fix(create):  run ngAdd in new project context

---

.yarnrc.yml
apps/github-cascading-app/package.json
yarn.lock

chore: upgrade probot

---

apps/showcase/src/components/showcase/component-replacement/component-replacement-pres.component.ts
docs/components/COMPONENT_REPLACEMENT.md
packages/@o3r/components/schematics/ng-update/v10-0/index.spec.ts
packages/@o3r/components/schematics/ng-update/v10-0/index.ts
packages/@o3r/components/src/tools/component-replacement/c11n.directive.ts
packages/@o3r/components/src/tools/component-replacement/c11n.service.ts

The return type of `getPresenter` was incorrect

fix(c11n): change the return type of the operator getpresenter

---

package.json
packages/@ama-sdk/schematics/package.json
yarn.lock

chore: upgrade npm-run-all2

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v10.0/script-removal.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/tsconfig.doc.json

Fix doc:generate command in project generated by ama-sdk/create.

fix(ama-sdk/create): fix doc:generate command

---

docs/configuration/CONFIGURATION_SUPPORTED_EXTRACTOR.md

Update documentation for configuration tag support

chore: update doc for supported configuration tags

---

packages/@o3r/create/src/index.ts

fix: force the minor version of angular when creating new project

---

.yarnrc.yml
package.json
packages/@o3r/schematics/tsconfig.cli.json
yarn.lock

Enforce angular-eslint nx version to remove multiple instance of it

chore: removed multiple nx version deps

---

.eslintrc.js
packages/@o3r/eslint-plugin/package.json
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/json-dependency-versions-harmonize.spec.ts
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/version-harmonize.ts
packages/@o3r/eslint-plugin/src/rules/typescript/no-folder-import-for-module/no-folder-import-for-module.spec.ts
packages/@o3r/eslint-plugin/src/rules/yaml/yarnrc-package-extensions-harmonize/yarnrc-package-extensions-harmonize.spec.ts
packages/@o3r/eslint-plugin/testing/jest.config.ut.js
yarn.lock

test: use virtual filesystem for eslint-plugin tests

---

packages/@o3r/storybook/README.md
packages/@o3r/storybook/package.json

Deprecation of package `@o3r/storybook`

feat: deprecate @o3r/storybook

---

packages/@o3r/eslint-config-otter/package.json

fix: o3r-eslint config is not fully published

---

packages/@ama-sdk/core/package.json

feat(sdk-core): expose missing plugin

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/core/src/plugins/mgw-mdw-auth/mgw-mdw-auth.request.ts
packages/@ama-sdk/core/src/plugins/mgw-mdw-auth/mgw-mdw-auth.spec.ts

Fix SDK Micro-gateway plugin to correctly expose the request header

fix(sdk-core): micro-gateway plugin header set

---

.github/markdown-check-issue-template.md
.github/markdown-external-links.config.json
.github/markdown-links.config.json
.github/workflows/code-check.yml
.github/workflows/md-external-links-check.yml
docs/forms/FORM_ERRORS.md
docs/styling/THEME.md
packages/@ama-sdk/core/README.md
packages/@o3r/eslint-plugin/README.md

The goal is to have a weekly (or manually triggered) Github action that will check external links for all our `.md` files.

feat: weekly check external links 

---

.github/markdown-external-links.config.json
packages/@ama-sdk/schematics/README.md

- :bug: Fixes broken links found in #1347

fix: external links in documentation

---

packages/@ama-sdk/core/src/plugins/mgw-mdw-auth/mgw-mdw-auth.request.ts
packages/@ama-sdk/core/src/plugins/mgw-mdw-auth/mgw-mdw-auth.spec.ts

Fix the way the microgateway token is calculated

fix(sdk-core): microgateway token generation

---

packages/@o3r/testing/src/core/playwright/component-fixture.ts

chore: cleanup playwright component fixture

---

.renovaterc.json

Regroup the upgrade of the dependencies dedicated to Application only

chore: regroup application renovate updates

---

packages/@o3r/localization/builders/localization/index.ts
packages/@o3r/localization/builders/localization/schema.json

fix: support application build in extract localization

---

packages/@o3r/test-helpers/src/prepare-test-env.ts

The goal of this PR is to allow running integration tests locally.

fix: run int tests locally

---

docs/core/UPGRADE_NEW_VERSION.md

doc: migration guide

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/testing/jest.config.ut.builders.js

test: fix random timeouts

---

.yarn/sdks/eslint/package.json
.yarnrc.yml
apps/showcase/tsconfig.app.json
package.json
packages/@ama-sdk/core/tsconfig.spec.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/testing/tsconfig.spec.json
packages/@ama-sdk/showcase-sdk/testing/tsconfig.spec.json
packages/@o3r/eslint-plugin/tsconfig.build.json
tools/github-actions/audit/tsconfig.json
tools/github-actions/cascading/tsconfig.build.json
tools/github-actions/get-npm-tag/tsconfig.json
tools/github-actions/new-version/tsconfig.build.json
yarn.lock

align sub type dependencies to remove type conflicts in case of libCheck

chore: align sub type dependencies

---

apps/showcase/project.json
apps/showcase/src/app/rules-engine/rules-engine.component.ts
apps/showcase/src/assets/rules/rulesets.json
docs/core/UPGRADE_NEW_VERSION.md
migration-guides/10.0.md
migration-guides/README.md
packages/@o3r/eslint-config-otter/rules/typescript/eslint.cjs

chore: migration guide for v10

---

migration-guides/10.0.md
migration-guides/README.md

docs: fix broken links

---

apps/showcase/project.json
nx.json
packages/@ama-sdk/showcase-sdk/project.json

Waiting https://github.com/nrwl/nx/issues/16685 to be fixed to removed these new `namedInputs` and directly apply them.

fix(nx): group named inputs

---

.github/actions/setup-java/action.yml
.github/workflows/audit.yml
.github/workflows/clean-cache.yml
.github/workflows/code-check.yml
.github/workflows/codeql.yml
.github/workflows/deploy-showcase.yml
.github/workflows/documentation.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml
.github/workflows/md-external-links-check.yml
.github/workflows/pr-labels.yml
.github/workflows/publish-pr.yml
.github/workflows/publish.yml
.renovaterc.json
tools/github-actions/download-build-output/action.yml
tools/github-actions/setup/action.yml
tools/github-actions/upload-build-output/action.yml

https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

ci(renovate): pin github action dependencies

---

apps/chrome-devtools/src/app-devtools/config-panel/config-panel-pres.template.html

Fix the configuration tab of the Chrome Devtools

fix(chrome-devtools): fix configuration administration page

---

.github/workflows/audit.yml
.github/workflows/clean-cache.yml
.github/workflows/code-check.yml
.github/workflows/codeql.yml
.github/workflows/documentation.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml
.github/workflows/pr-labels.yml
.github/workflows/publish-pr.yml
.github/workflows/publish.yml
.github/workflows/tests-reporter.yml

The goal of this PR is to provide the minimum token permissions in our workflows

ci: limit token permissions

---

apps/showcase/src/app/design-token/design-token.template.html
apps/showcase/src/app/sdk/sdk.template.html
compodoc-templates/root/partials/menu.hbs

docs: fix compodoc links

---

apps/showcase/src/app/app.component.ts
apps/showcase/src/app/app.module.ts
apps/showcase/src/main.ts
packages/@o3r/localization/src/devkit/localization-devtools.message.service.ts

fix(devtools): activate all devtools on showcase

---

apps/vscode-extension/package.json
apps/vscode-extension/src/extension.ts
apps/vscode-extension/src/intellisense/design-token.ts
package.json
packages/@o3r/design/package.json
yarn.lock

feat(vscode-ext): intellisense for design tokens

---

package.json
tools/@o3r/build-helpers/scripts/prepare-publish.mjs

The issue has blocked the publication of the VsCode extension for Otter v10.

fix(build-helpers): prepare-publish function

---

apps/chrome-devtools/src/app-devtools/app.component.html
apps/chrome-devtools/src/app-devtools/app.component.ts
apps/chrome-devtools/src/app-devtools/component-panel/component-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/config-panel/config-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/debug-panel/debug-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/debug-panel/debug-panel-pres.template.html
apps/chrome-devtools/src/app-devtools/localization-panel/localization-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/localization-panel/localization-panel-pres.template.html
apps/showcase/project.json
docs/dev-tools/chrome-devtools.md
packages/@o3r/localization/src/devkit/localization-devkit.interface.ts
packages/@o3r/localization/src/devkit/localization-devtools.console.service.ts
packages/@o3r/localization/src/devkit/localization-devtools.message.service.ts
packages/@o3r/localization/src/devkit/localization-devtools.service.ts
packages/@o3r/localization/src/devkit/localization-devtools.token.ts
packages/@o3r/localization/src/tools/localization.service.ts

feat(chrome-ext): localization panel

---

nx.json

test: fix nx inputs for it-tests

---

apps/showcase/src/assets/rules/rulesets.json
packages/@o3r/rules-engine/schemas/rulesets.schema.json
packages/@o3r/rules-engine/src/components/rules-engine/ruleset-history/ruleset-history-pres.module.ts
packages/@o3r/rules-engine/src/components/rules-engine/ruleset-history/ruleset-history-pres.template.html

Display error in rule execution in rule panel
- :bug: Fixes resolves #1423

fix(rules-engine): error in rule execution in rule panel

---

packages/@o3r/styling/_otter-theme.scss
packages/@o3r/styling/ng-package.json

fix(styling): correctly export otter-theme scss

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

fix(sdk): logger.debug is possibly undefined

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java

fix(sdk): keep type imports in generated files

---

README.md
SECURITY.md

docs: update security information and readme links

---

apps/showcase/src/app/app-routing.module.ts

Simple change to use Angular Router `title` property to change the title of a page on route change
- :rocket: Feature #1567

feat(showcase): title follows route

---

packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.generator.ts
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts

Possibility of adding `--openapi-normalizer` parameter to the OpenAPI generator CLI
Values possible: https://openapi-generator.tech/docs/customization/#openapi-normalizer

feat: support openapi-normalizer parameter to forward to generator

---

apps/vscode-extension/src/intellisense/design-token.ts

Read design token file patterns from Angular.json if not specified
- :rocket: Feature resolves #1489

feat(vscode): read design token file patterns from Angular.json

---

packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts

chore(ama-sdk): add logs on timeout cancellation/restart

---

docs/components/PLACEHOLDERS.md
docs/rules-engine/how-it-works/placeholders.md
docs/rules-engine/how-to-use/placeholders.md

The goal is to fix some formatting issues for the placeholder documentation.

docs: format rules engine placeholders

---

jest.config.ut.js

test: ignore package.json from src

---

apps/chrome-devtools/package.json
apps/chrome-devtools/project.json

fix(chrome-ext): patch manifest.json with the right version number

---

packages/@o3r/components/src/rules-engine/placeholder.action-handler.ts

Placeholder with rules engine were not displayed because 
- `lang$` was not initialized 
- `DynamicContentService` was not injected correctly

fix(rules-engine): init language + inject correctly service outside constructor

---

.yarn/sdks/typescript/package.json
packages/@o3r/workspace/schematics/application/index.ts

fix(schematics): add support on underscore for application name

---

packages/@o3r/workspace/schematics/sdk/rules/clean-standalone.rule.ts

fix(schematics): do not delete inexisting files

---

tools/renovate/tasks/yarn-pnp.json

fix(renovate): missing install in yarn pnp preset

---

.github/workflows/it-tests.yml
.yarnrc.yml
package.json
packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/src/index.ts
yarn.lock

Remove unnecessary yarn dependency extension

fix: remove yarn dependencies extension unnecessary anymore

---

.github/workflows/it-tests.yml
.yarnrc.yml
package.json
packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/src/index.ts
yarn.lock

cherry-pick from:
https://github.com/AmadeusITGroup/otter/pull/1664

cherry-pick - fix/node on windows

---

apps/chrome-devtools/src/app-components/app.component.ts
apps/chrome-devtools/src/app-devtools/component-panel/component-panel-pres.component.ts
apps/chrome-devtools/src/components/otter-component/otter-component.component.ts
docs/ab-testing/AB_TESTING.md
docs/rules-engine/how-to-use/cms-json-imports.md
docs/rules-engine/how-to-use/dedicated-component-ruleset.md
packages/@o3r/rules-engine/schemas/rulesets.schema.json
packages/@o3r/rules-engine/src/components/rules-engine/ruleset-history/ruleset-history-pres.template.html
packages/@o3r/rules-engine/src/devkit/rules-engine-devtools.console.service.ts
packages/@o3r/rules-engine/src/devkit/rules-engine-devtools.service.ts
packages/@o3r/rules-engine/src/engine/engine.interface.ts
packages/@o3r/rules-engine/src/engine/ruleset-executor.ts
packages/@o3r/rules-engine/src/engine/structure.ts
packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.spec.ts
packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.spec.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.ts
packages/@o3r/rules-engine/testing/mocks/tworulesets-both-ondemand.ts

feat: support linked components in rules engine

---

packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/core/helpers/path-extractor.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/helpers/path-extractor.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
yarn.lock

Cascading/9.6 10.1

---

SECURITY.md

Update supported version

---

.github/workflows/tests-reporter.yml

ci(test-reporter): missing token permissions in workflow

---

packages/@ama-sdk/showcase-sdk/src/spec/api-mock.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.state.ts
packages/@o3r/dev-tools/src/cli/artifact-retriever.ts
packages/@o3r/dynamic-content/src/stores/asset-path-override/asset-path-override.state.ts
packages/@o3r/localization/src/stores/localization-override/localization-override.state.ts
packages/@o3r/testing/src/localization/localization-mock.ts

Less warnings raised by the linter.

chore: eslint autofix warnings

---

packages/@o3r/workspace/schematics/library/index.ts
packages/@o3r/workspace/schematics/library/rules/rules.ng.ts

fix: o3r/core as devDep for new Otter libs

---

packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/eslint-config-otter/project.json
packages/@o3r/eslint-config-otter/rules/typescript/eslint-typescript.cjs
packages/@o3r/eslint-config-otter/schematics/index.it.spec.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/index.ts
packages/@o3r/testing/schematics/ng-add/fixture/index.ts
packages/@o3r/workspace/schematics/rule-factories/project-configs.ts

- :bug: Fixes https://github.com/AmadeusITGroup/otter/issues/1676
- :bug: Fixes https://github.com/AmadeusITGroup/otter/issues/1690

fix: no eslint errors on new apps and libs

---

.github/workflows/tests-reporter.yml

Fix the issue reported on https://github.com/AmadeusITGroup/otter/security/code-scanning/102

fix(github-actions): the security warning the regarding the permissions

---

packages/@o3r/styling/scss/theming/otter-theme/_theme.scss

fix: use material palette when generating theme

---

.renovaterc.json5

Reduce the number of Renovate's PR on Next branch

feat(renovate): exclude non-major upgrade on Next versions

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
packages/@o3r/eslint-config-otter/rules/typescript/eslint.cjs
packages/@o3r/telemetry/src/environment/index.ts

fix(telemetry): ci was always true

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
package.json
packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/swagger-builder/package.json
yarn.lock

Removed `onchange` dependency not used anymore

chore: remove "onchange" dependency

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.ts

fix: make generators optional in openapitools.json

---

packages/@o3r/core/src/store/async/async.operators.ts

Fixed wrong promise handling in async operators

fix(core): async operators

---

apps/chrome-devtools/README.md
apps/chrome-devtools/package.json
docs/dev-tools/chrome-devtools.md

Update Otter DevTools Chrome extension documentation

feat: update chrome devtools documentation

---

packages/@ama-sdk/showcase-sdk/package.json
packages/@ama-sdk/showcase-sdk/project.json
packages/@ama-sdk/showcase-sdk/readme.md

Publish of a new package **@ama-sdk/showcase-sdk** 
The goal is to use the specs file published in this package as input for a repository generated by the _ama-sdk/schematics_ generator and kept up to date with _renovate_

feat: publish showcase-sdk package

---

packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/collection.json
packages/@ama-sdk/schematics/schematics/helpers/is-typescript-project.ts
packages/@ama-sdk/schematics/schematics/migrate/index.ts
packages/@ama-sdk/schematics/schematics/migrate/schema.json
packages/@ama-sdk/schematics/schematics/migrate/schema.ts
packages/@ama-sdk/schematics/schematics/ng-update/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@o3r/schematics/src/utility/index.ts
packages/@o3r/schematics/src/utility/migration/migration.spec.ts
packages/@o3r/schematics/src/utility/migration/migration.ts
tools/renovate/tasks/sdk-regenerate.json

Provide migration schematics to manually apply migration
- :rocket: Feature resolves #1735
- 🍒 Cherry-pick: #1744

Feature: migration schematics

---

package.json
packages/@ama-sdk/core/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@ama-sdk/showcase-sdk/package.json
yarn.lock

Cherry pick from https://github.com/AmadeusITGroup/otter/pull/1831

fix: freeze @swc/core to 1.5.7

---

docs/store-sync/STORE_SYNC.md

Add link to package in store-sync documentation

feat: add package link to store-sync documentation

---

.github/workflows/it-tests.yml
packages/@o3r/test-helpers/src/utilities/package-manager.ts

ci(it-tests): fix random failures due to github cache configuration

---

packages/@ama-sdk/core/src/plugins/session-id/session-id.request.ts

fix: remove breaking in request-id

---

packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

fix: prevent TimeoutPlugin from crashing on string messages

---

.yarn/sdks/eslint/bin/eslint.js
.yarn/sdks/eslint/lib/api.js
.yarn/sdks/eslint/lib/unsupported-api.js
.yarn/sdks/typescript/bin/tsc
.yarn/sdks/typescript/bin/tsserver
.yarn/sdks/typescript/lib/tsc.js
.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/sdks/typescript/lib/typescript.js
packages/@o3r/apis-manager/README.md

fix(apis-manager): documentation example
chore(apis-manager): migrate documentation example to inject()

fix(apis-manager): documentation example

---

packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

Cascading/9.6 10.2

---

.yarnrc.yml
yarn.lock

align missing dependencies sub deps peer

chore: align missing dependencies sub deps peer

---

packages/@o3r/core/schematics/rule-factories/store/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
packages/@o3r/localization/schematics/ng-add/index.ts
packages/@o3r/rules-engine/schematics/ng-add/index.ts
packages/@o3r/schematics/schematics/ng-add/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/ng-add.helpers.ts
packages/@o3r/schematics/src/utility/dependencies.ts
packages/@o3r/store-sync/schematics/ng-add/index.ts
packages/@o3r/stylelint-plugin/schematics/ng-add/index.ts
packages/@o3r/styling/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts

fix: retrieve dep versions also from devDeps

---

packages/@ama-sdk/showcase-sdk/src/api/pet/pet-api.ts
packages/@ama-sdk/showcase-sdk/src/api/store/store-api.ts
packages/@ama-sdk/showcase-sdk/src/api/user/user-api.ts
packages/@ama-sdk/showcase-sdk/src/spec/api-mock.ts

Regenerating the sdk based on the latest templates.

feat: regenerate the showcase sdk

---

.github/workflows/clean-cache.yml
.github/workflows/tests-reporter.yml

fix: set token permission as readonly

---

packages/@ama-sdk/core/src/plugins/perf-metric/perf-metric.fetch.ts
packages/@ama-sdk/core/src/plugins/perf-metric/perf-metric.probe.spec.ts

feat(ama-sdk): enhance performance plugin to report performance mark

---

migration-guides/11.0.md
packages/@o3r/schematics/src/tasks/ng-add/index.ts

remove deprecated  `NodePackageNgAddTask`

chore: remove NodePackageNgAddTask

---

packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-otter-project.ts
packages/@o3r/test-helpers/src/utilities/package-manager.ts

cherry pick of #1899  on release 10.4

test: fix it-tests not running in local

---

tools/renovate/tasks/sdk-regenerate.json

fix: update ama-sdk schematics migrate command in renovate preset

---

tools/renovate/tasks/sdk-regenerate.json

fix: update ama-sdk schematics migrate command in renovate preset - cherry-pick

---

packages/@o3r/design/schemas/design-token.schema.json
packages/@o3r/design/src/core/design-token/design-token-specification.interface.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.spec.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

update Shadow and Gradient rendering according to specifications
cf. https://design-tokens.github.io/community-group/format/

fix(design): update Shadow and Gradient rendering according to specifications

---

apps/vscode-extension/.eslintrc.js
apps/vscode-extension/package.json

Remove invalid dependencies
- :bug: Fixes #1931

fix(vscode-ext): remove invalid deps

---

packages/@ama-sdk/schematics/package.json
packages/@o3r/components/schematics/index.it.spec.ts
packages/@o3r/extractors/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/localization-base/index.ts
packages/@o3r/localization/schematics/localization-base/templates/__empty__.gitignore
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/schematics/src/utility/gitignore.spec.ts
packages/@o3r/schematics/src/utility/gitignore.ts
packages/@o3r/styling/schematics/index.it.spec.ts

Create the assets array if not present
- :bug: Fixes #1758

fix(ng-add localization): create the assets array if not present

---

packages/@ama-sdk/schematics/package.json
packages/@o3r/third-party/project.json
packages/@o3r/third-party/schematics/iframe-to-component/index.spec.ts
packages/@o3r/third-party/schematics/iframe-to-component/index.ts
packages/@o3r/third-party/schematics/index.it.spec.ts
packages/@o3r/third-party/testing/jest.config.it.js

fix: iframe to component template

---

packages/@o3r/design/schematics/index.it.spec.ts
packages/@o3r/design/schematics/ng-add/index.spec.ts
packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts
packages/@o3r/design/schematics/ng-add/register-generate-css/templates/theme.scss.template
packages/@o3r/design/testing/mocks/angular.mocks.json

Fix ngAdd schemtics to correctly add @o3r/design package
- :bug: Fixes #1771

fix(design): ng add angular.json updates and file creation

---

docs/store-sync/STORE_SYNC.md

Update example for store synchronization

docs(store-sync): update example for store synchronization

---

packages/@o3r/styling/scss/theming/otter-theme/_material.scss
packages/@o3r/styling/scss/theming/otter-theme/_theme.scss

Add support for Material Design 3 palettes and theme generation

feat(styling): add support for Material Design 3 palettes

---

packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/core/schematics/page/index.spec.ts
packages/@o3r/core/schematics/page/index.ts
packages/@o3r/core/schematics/page/schema.json
packages/@o3r/core/schematics/page/schema.ts

Try to detect automatically the routes definition
- :bug: Fixes #1873

fix(generator): try to detect automatically the routes definition

---

.vscode/settings.json

add eslint action on save for VsCode

feat: add eslint action on save

---

apps/chrome-devtools/src/app-devtools/app.component.ts
apps/chrome-devtools/src/app-devtools/theming-panel/theming-panel-pres.component.ts
apps/chrome-devtools/src/services/connection.service.ts
apps/chrome-devtools/src/services/localization.service.ts
apps/chrome-devtools/src/services/state.service.ts

Port should be reconnnected after a certain time without interaction
- :bug: Fixes #1686

fix(chrome-ext): port should be reconnnected after a certain time without interaction

---

packages/@o3r/components/builders/metadata-check/index.it.spec.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts
packages/@o3r/localization/builders/metadata-check/index.it.spec.ts
packages/@o3r/styling/builders/metadata-check/index.it.spec.ts
packages/@o3r/test-helpers/src/prepare-test-env.ts

Fix https://github.com/AmadeusITGroup/otter/issues/1982
- :bug: Fixes #1982 

fix(extractors): sanatize input before spawning command

---

packages/@o3r/design/README.md
packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/builders/generate-css/schema.json
packages/@o3r/design/builders/generate-css/schema.ts
packages/@o3r/design/schemas/design-token.schema.json
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.spec.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.ts
packages/@o3r/design/src/core/design-token/renderers/design-token.renderer.interface.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-definition.renderers.spec.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-definition.renderers.ts

Add the capability to not render private token in metadata.

feat(design): add the capability to not render private token in metadata

---

packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/pom.xml
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java

chore: upgrade openapi generator

---

packages/@o3r/testing/package.json
packages/@o3r/testing/src/core/angular-materials/index.ts
packages/@o3r/testing/src/core/angular-materials/slider-material.ts
packages/@o3r/testing/src/core/angular/angular-materials/index.ts
packages/@o3r/testing/src/core/angular/angular-materials/slider-material.ts
packages/@o3r/testing/src/core/angular/elements/index.ts
packages/@o3r/testing/src/core/angular/elements/slider-element.ts
packages/@o3r/testing/src/core/elements/index.ts
packages/@o3r/testing/src/core/elements/slider-element.ts
packages/@o3r/testing/src/core/playwright/angular-materials/index.ts
packages/@o3r/testing/src/core/playwright/angular-materials/slider-material.ts
packages/@o3r/testing/src/core/playwright/elements/index.ts
packages/@o3r/testing/src/core/playwright/elements/slider-element.ts
yarn.lock

Add a slider element
- :rocket: Feature #2045

feat(testing): add a slider element

---

packages/@o3r/styling/builders/metadata-check/helpers/styling-metadata-comparison.helper.ts

Current computing mechanism is not working for styling metadata 
- :bug: Fixes #2061

fix: styling metadata array computing

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
packages/@o3r/components/src/core/component.output.ts
packages/@o3r/core/src/core/interfaces/index.ts
packages/@o3r/core/src/core/interfaces/item-identifier.ts
packages/@o3r/design/src/core/design-token/design-token-specification.interface.ts
packages/@o3r/rules-engine/src/engine/engine.interface.ts
packages/@o3r/rules-engine/src/engine/structure.ts
packages/@o3r/styling/src/core/styles.interface.ts

Create interface ItemIdentifier
- :rocket: Feature #1693

feat(#1693): create interface itemidentifier

---

jest.config.ut.js
packages/@o3r/core/package.json
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.ut.js.template

Correctly parse tsconfig.base.json in UT config to support comments

fix(test): tsconfig.base parsing to support comments

---

packages/@o3r/design/builders/generate-css/index.ts

Add logging to Design Token based CSS generation.

feat(design): add logging to CSS generation

---

packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/ng-add/index.ts
packages/@o3r/workspace/schematics/sdk/index.ts
packages/@o3r/workspace/testing/mocks/easy-spec.yaml

fix: wrong path calculation for sdk spec relative path in monorepo

---

packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-otter-project.ts
packages/@o3r/test-helpers/src/utilities/package-manager.ts

test: speed-up it tests

---

packages/@o3r/testing/src/core/page-fixture.ts
packages/@o3r/testing/src/core/protractor/angular-materials/autocomplete-material.ts
packages/@o3r/testing/src/core/protractor/angular-materials/select-material.ts
packages/@o3r/testing/src/core/protractor/component-fixture.ts
packages/@o3r/testing/src/core/protractor/element.ts
packages/@o3r/testing/src/core/protractor/elements/checkbox-element.ts
packages/@o3r/testing/src/core/protractor/elements/radio-element.ts
packages/@o3r/testing/src/core/protractor/elements/select-element.ts
packages/@o3r/testing/src/core/protractor/group.ts
packages/@o3r/testing/src/core/protractor/groups/radio-group.ts
packages/@o3r/testing/src/core/protractor/page-fixture.ts
packages/@o3r/testing/src/core/protractor/utils.ts
packages/@o3r/testing/src/tools/protractor/fetch-manager/utils.ts
packages/@o3r/testing/src/tools/protractor/post-message-interceptor/core.ts
packages/@o3r/testing/src/tools/protractor/post-message-interceptor/post-message-interceptor.ts

chore: deprecate protractor

---

packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-definition.renderers.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-value.renderers.spec.ts
packages/@o3r/design/src/core/design-token/renderers/metadata/design-token-value.renderers.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

Ignore private references in generated metadata when requested

fix(design): ignore private references in metadata when requested

---

yarn.lock

chore: update path-to-regexp

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/plugins/core/angular-plugin.ts
packages/@ama-sdk/core/src/plugins/core/fetch-plugin.ts
packages/@ama-sdk/core/src/plugins/mock-intercept/index.ts
packages/@ama-sdk/core/src/plugins/mock-intercept/mock-intercept.angular.ts

- Support for Angular ApiClient plugins
- Mock Intercept angular plugin

feat(ama-sdk): create Mock Intercept angular plugin

---

packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/src/core/design-token/design-token-specification.interface.ts

Support for template file dependency path

feat(design): support for template file dependency path

---

.github/workflows/code-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml

chore: update upload-artifact

---

.commitlintrc.json
tools/@o3r/build-helpers/scripts/pr-labels.mjs

Add "deprecate" github tag on message prefix

feat: add "deprecate" github tag on message prefix

---

apps/showcase/scripts/update-screenshots/podman-script.sh

fix: update screenshots script

---

CONTRIBUTING.md
package.json
tools/@o3r/build-helpers/package.json
tools/@o3r/build-helpers/scripts/create-monorepo-scope.mjs
yarn.lock

Script to help to create a new scope in the repository
- :rocket: Feature resolves #2144

feat: script to create a new scope in the repository

---

packages/@o3r/test-helpers/src/utilities/locker.ts

test: prevent race condition failure on it-tests

---

packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/builders/generate-jsonschema/index.ts
packages/@o3r/design/package.json
packages/@o3r/design/schematics/extract-token/index.ts
packages/@o3r/design/schematics/generate-css/index.ts
packages/@o3r/design/schematics/ng-add/index.ts
yarn.lock

Add the missing telemetry wrapper

fix(telemetry): missing telemetry wrapper

---

docs/telemetry/PRIVACY_NOTICE.md
packages/@o3r/extractors/src/core/wrapper.ts
packages/@o3r/schematics/src/utility/wrapper.ts
packages/@o3r/telemetry/README.md
packages/@o3r/telemetry/migration.json
packages/@o3r/telemetry/package.json
packages/@o3r/telemetry/schematics/ng-add/index.ts
packages/@o3r/telemetry/schematics/ng-update/index.ts
packages/@o3r/telemetry/schematics/ng-update/v11.3/index.spec.ts
packages/@o3r/telemetry/schematics/ng-update/v11.3/index.ts
packages/@o3r/telemetry/src/builders/index.ts
packages/@o3r/telemetry/src/environment/index.ts
packages/@o3r/telemetry/src/schematics/index.ts

Add a possibility to override the project name

feat(telemetry): add a possibility to override the project name

---

packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/ng-add/helpers/npm-workspace.ts
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/index.ts
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/templates/__dot__renovaterc.json.template
packages/@o3r/workspace/schematics/ng-add/project-setup.ts

fix(workspace): renovate not being generated

---

docs/renovate/readme.md
tools/renovate/README.md

docs(renovate): enhance renovate documentation

---

packages/@o3r/design/README.md
packages/@o3r/design/builders/generate-css/schema.json
packages/@o3r/design/builders/generate-css/schema.ts

Fix documentation relative to template files input

doc(design): fix documentation relative to template files input

---

packages/@ama-sdk/schematics/migration.json
packages/@ama-sdk/schematics/schematics/migrate/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v11.4/create-gitattributes.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.gitattributes.template

Generate GitAttributes file ignoring generated files

feat(sdk): generate GitAttributes file ignoring generated files

---

packages/@o3r/test-helpers/package.json
yarn.lock

add missing semver dependency to test-helpers

fix(test-helpers): add missing semver dependency

---

packages/@o3r/test-helpers/package.json
yarn.lock

Removed unused `minimist` dependency

fix(test-helpers): removed unused minimist dependency

---

packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md

chore(sdk): enhance sdk documentation

---

packages/@o3r/application/schemas/cms.schema.json

Update CMS schema

---

.vscode/settings.json
packages/@o3r/eslint-config/schematics/ng-add/vscode/index.ts
packages/@o3r/eslint-config/src/rules/typescript/comments.cjs

feat(eslint): change default vscode config

---

package.json
packages/@o3r/components/package.json
packages/@o3r/rules-engine/package.json
yarn.lock

- ⚠️ Security:
- https://github.com/AmadeusITGroup/otter/security/dependabot/81
- https://github.com/AmadeusITGroup/otter/security/dependabot/82
- https://github.com/AmadeusITGroup/otter/security/dependabot/83

fix: upgrade jsonpath-plus dependency

---

.github/workflows/main.yml
tools/github-actions/README.md
tools/github-actions/release/LICENSE
tools/github-actions/release/action.yml
tools/github-actions/release/readme.md

- :rocket: Feature resolves #2258

feat(github-action): create GitHub Release Action

---

docs/linter/eslint-config.md
docs/linter/eslint-plugin/rules/json-dependency-versions-harmonize.md
docs/linter/eslint-plugin/rules/no-inner-html.md
docs/linter/eslint-plugin/rules/yarnrc-package-extensions-harmonize.md
migration-guides/ESLINT_FLAT_CONFIG.md
migration-guides/README.md
packages/@ama-sdk/showcase-sdk/eslint.local.config.mjs
packages/@o3r/eslint-config/README.md
packages/@o3r/eslint-config/src/rules/typescript/comments.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint-angular.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint-typescript.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint.cjs
packages/@o3r/eslint-config/src/rules/typescript/import.cjs
packages/@o3r/eslint-config/src/rules/typescript/jest.cjs
packages/@o3r/eslint-config/src/rules/typescript/jsdoc.cjs
packages/@o3r/eslint-config/src/rules/typescript/stylistic.cjs
packages/@o3r/eslint-config/src/rules/typescript/unicorn.cjs
packages/@o3r/eslint-config/src/rules/utils.cjs

Update documentation for eslint flat config

docs(eslint): update documentation for eslint flat config

---

packages/@o3r/design/builders/generate-style/helpers/style-renderer-options.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.spec.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.ts
packages/@o3r/design/src/core/design-token/renderers/design-token.renderer.interface.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

fix(design): way to sort variable to refer existing variables

fix(design): way to sort variable to refer existing variables

---

docs/components/PLACEHOLDERS.md

Fix Faraday generation on main pipeline
cf: https://github.com/AmadeusITGroup/otter/actions/runs/11383563112/job/31669459265

fix: faraday generation

---

packages/@o3r/design/builders/generate-style/helpers/style-renderer-options.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.spec.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.ts
packages/@o3r/design/src/core/design-token/renderers/design-token.renderer.interface.ts

fix(design): create folder with files when does not exist
fix(design): better sorting by name with grade

fix(design): create folder with files when does not exist

---

apps/showcase/src/style/dark-theme/dark-theme.scss
apps/showcase/src/style/horizon-theme/horizon-theme.scss
apps/showcase/src/style/theme.scss

Regenerate design token in showcase

chore(showcase): regenerate design token

---

apps/showcase/project.json
apps/showcase/src/coi-serviceworker.js

Cross-origin isolation service worker in order to be able to deploy the training on GitHub pages.
Source of this script: https://github.com/gzuidhof/coi-serviceworker/tree/master

feat: coi-serviceworker to deploy training in GitHub pages

---

eslint.config.mjs
nx.json
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.config.__extension__.template
tools/github-actions/audit/eslint.local.config.mjs
tools/github-actions/cascading/eslint.local.config.mjs
tools/github-actions/get-npm-tag/eslint.local.config.mjs
tools/github-actions/new-version/eslint.local.config.mjs

Fix configuration of eslint to work for windows environment (absolute file paths and quotes in nx.json)

fix: eslint configuration for windows

---

README.md

Add badges for vscode and chrome extensions

doc: add badges for vscode and chrome extensions

---

packages/@o3r/design/src/core/design-token/design-token-specification.interface.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/tsconfig.spec.json

fix(design): stroke type to limit to valid values
See standard on https://tr.designtokens.org/format/#stroke-style

fix(design): stroke type to limit to valid values

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

Enhance breaking change rules
- :rocket: Feature resolves #2141

doc: enhance breaking change rules

---

packages/@o3r/analytics/eslint.local.config.mjs
packages/@o3r/analytics/plugins/webpack/build-metrics/build-stats.plugin.ts
packages/@o3r/analytics/schematics/analytics-to-component/index.ts
packages/@o3r/analytics/src/contracts/events-contracts.ts
packages/@o3r/analytics/src/directives/track-events/base-track-events.ts
packages/@o3r/analytics/src/services/event-track/event-track.service.spec.ts
packages/@o3r/analytics/src/services/event-track/event-track.service.ts
packages/@o3r/analytics/src/stores/event-track/event-track.actions.ts
packages/@o3r/analytics/src/stores/event-track/event-track.reducer.spec.ts
packages/@o3r/analytics/src/stores/event-track/event-track.reducer.ts
packages/@o3r/analytics/src/stores/event-track/event-track.selectors.spec.ts
packages/@o3r/analytics/src/stores/event-track/event-track.state.ts
packages/@o3r/apis-manager/eslint.local.config.mjs
packages/@o3r/apis-manager/src/apis-manager/api-factory.service.ts
packages/@o3r/apis-manager/src/apis-manager/api-manager.ts
packages/@o3r/application/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/application/schematics/ng-update/index.ts
packages/@o3r/application/src/devkit/application-devtools.console.service.ts
packages/@o3r/application/src/devkit/application-devtools.message.service.ts
packages/@o3r/artifactory-tools/schematics/ng-add/index.ts
packages/@o3r/artifactory-tools/src/cli/artifact-cleaner.ts
packages/@o3r/artifactory-tools/src/cli/pr-artifact-cleaner.ts
packages/@o3r/azure-tools/schematics/ng-add/index.ts
packages/@o3r/azure-tools/src/cli/comment-pr.ts
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.config.__extension__.template

Manual fix of ESLint errors for @o3r/analytics, @o3r/apis-manager, @o3r/application, @o3r/artifactory-tools, @o3r/azure-tools

fix: manual fix of eslint errors on packages @o3r/{a}*

---

apps/showcase/src/app/rules-engine/rules-engine.component.ts
apps/showcase/src/app/rules-engine/rules-engine.template.html

fix(accessibility): import the full module to have all accessibilities features

---

.vscode/settings.json

fix: vscode watch mode options

---

apps/vscode-extension/src/intellisense/configuration.ts
packages/@ama-sdk/core/src/fwk/date.ts
packages/@ama-sdk/core/src/plugins/api-key/api-key.spec.ts
packages/@ama-sdk/core/src/plugins/json-token/json-token.spec.ts
packages/@ama-terasu/cli/src/modules/base-yargs.ts
packages/@ama-terasu/core/eslint.local.config.mjs
packages/@ama-terasu/schematics/eslint.local.config.mjs
packages/@o3r/amaterasu/amaterasu-api-spec/eslint.local.config.mjs
packages/@o3r/amaterasu/amaterasu-api-spec/src/create-extension.command.ts
packages/@o3r/amaterasu/amaterasu-dodo/eslint.local.config.mjs
packages/@o3r/amaterasu/amaterasu-dodo/src/index.ts
packages/@o3r/amaterasu/amaterasu-otter/eslint.local.config.mjs
packages/@o3r/amaterasu/amaterasu-sdk/src/create-typescript.command.ts
packages/@o3r/configuration/eslint.local.config.mjs
packages/@o3r/configuration/src/devkit/configuration-devtools.console.spec.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.message.spec.ts
packages/@o3r/configuration/src/services/configuration/configuration.base.service.spec.ts
packages/@o3r/configuration/src/stores/configuration/configuration.reducer.spec.ts
packages/@o3r/core/schematics/component/container/index.spec.ts
packages/@o3r/core/schematics/ng-add/updates-for-v8/cms-adapters/update-builders-names.ts
packages/@o3r/core/schematics/ng-add/updates-for-v8/generators/update-generators-names.ts
packages/@o3r/core/schematics/ng-update/v8.2/import-map.ts
packages/@o3r/core/src/store/async/async.operators.ts
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/json-dependency-versions-harmonize.ts
packages/@o3r/eslint-plugin/src/rules/typescript/o3r-categories-tags/o3r-categories-tags.ts
packages/@o3r/logger/src/services/fullstory-logger-client/fullstory-logger-client.ts
packages/@o3r/logger/src/services/logrocket-logger-client/logrocket-logger-client.ts
packages/@o3r/logger/src/services/smartlook-logger-client/smartlook-logger-client.ts
packages/@o3r/store-sync/src/sync-storage/storage-sync.spec.ts

fix(eslint): fix remaining eslint issue after config changes

---

migration-guides/ESLINT_FLAT_CONFIG.md
packages/@o3r/eslint-config/src/rules/typescript/stylistic.cjs

docs(eslint): stylistic difference with eslintrc

---

packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.spec.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.spec.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.ts
packages/@o3r/rules-engine/testing/mocks/onerulesetvalid-onerule-nocond.mock.ts

fix: linked components should take validity range into account

---

.vscode/settings.json

Reduce VsCode CPU usage caused by watcher

fix: reduce VsCode CPU usage caused by watcher

---

.github/workflows/code-check.yml
README.md
codecov.yml
jest.config.ut.js
nx.json
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.ut.js.template

Ignore generated files in CodeCov
Add badge with reports into readme.md
Report UT results to CodeCov

feat: ignore files in CodeCov + UTs reporting

---

packages/@ama-sdk/schematics/package.json

chore: missing upgrade harmonize dependency

---

docs/rules-engine/README.md
docs/rules-engine/how-to-use/dedicated-component-ruleset.md

* :octocat: Pull Request #2400

docs: on demand rulesets take validity range into account

---

apps/showcase/package.json
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.html
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.scss
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.ts
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.scss
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/training-step/training-step-pres.component.html
apps/showcase/src/components/training/training-step/training-step-pres.component.ts
apps/showcase/src/components/training/training.component.html
apps/showcase/src/components/training/training.component.ts
package.json
yarn.lock

https://fpaul-1a.github.io/otter/#/sdk-training#9

feat(training): resizable areas

---

tools/github-actions/release/action.yml

Use the path where the composite action is saved instead of relative path

fix(github-actions-release): action local path fix

---

.github/workflows/it-tests.yml

chore: remove IT coverage

---

packages/@o3r-training/training-tools/package.json

fix(training): wrong training-tools exports

---

packages/@o3r/rules-engine/src/services/rules-engine.service.it.spec.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.spec.ts
packages/@o3r/rules-engine/src/stores/rulesets/rulesets.selectors.ts
packages/@o3r/rules-engine/testing/mocks/onerulesetvalid-onerule-nocond.mock.ts

fix: rulesets with linked components with validity range on 9.6

---

apps/showcase/src/components/training/code-editor-control/code-editor-control.component.ts

fix(training): accessibility of tabs in code editor controls

---

packages/@ama-sdk/swagger-builder/package.json
packages/@ama-sdk/swagger-builder/src/core/utils.spec.ts
packages/@ama-sdk/swagger-builder/src/core/utils.ts
packages/@ama-sdk/swagger-builder/tsconfig.spec.json
yarn.lock

chore: remove dependency to pascal-case
* :bug: #26

chore: remove dependency to pascal-case

---

CONTRIBUTING.md

doc: update nx cloud remote cache instruction

---

apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/services/webcontainer/webcontainer-runner.ts
apps/showcase/src/services/webcontainer/webcontainer.service.ts

https://fpaul-1a.github.io/otter/#/sdk-training#8

fix(training): unstable transitions between exercises and solutions

---

packages/@ama-sdk/create/README.md
packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/README.md
packages/@o3r/create/src/index.ts

Add `--yarn` option to create scripts

feat: add `--yarn` option to create scripts

---

SECURITY.md

Update releasing and support policy as discussed within the responsible team.

docs: update releasing and support policy

---

packages/@o3r/schematics/schematics/ng-add/index.ts
tools/@o3r/build-helpers/scripts/patch-package-json-main.mjs

Fix lost from https://github.com/AmadeusITGroup/otter/pull/2324

fix: o3r schematics import

---

codecov.yml

chore: allow code cov threshold

---

.github/CODEOWNERS
.yarnrc.yml
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

chore: update code-owners to refer all CMS JsonSchemas
chore: harmonize dependencies

chore: update code-owners

---

packages/@o3r-training/showcase-sdk/project.json

fix: add private tag for nx for o3r-training/showcase-sdk package

---

eslint.config.mjs
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.config.__extension__.template

https://eslint.org/docs/latest/use/configure/ignore#ignoring-files

fix(eslint): do not set files if ignores is set

---

apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts

Stop propagation of save event on the editor.

feat(training): stop propagation of save event on the editor

---

apps/showcase/src/components/training/training-step/training-step-pres.component.html
yarn.lock

Repair yarn.lock and adapt padding on instructions

fix: repair build and fix design

---

.github/workflows/code-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml

feat: add NX_PARALLEL environment variable

feat: add NX_PARALLEL environment variable

---

.vscode/settings.json

fix: vscode watcher issue with ts upgrade
chore: align dependencies

fix: vscode watcher issue with ts upgrade

---

tools/github-actions/release/action.yml

fix(tools): path to release script in github action

fix(tools): path to release script

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/pom.xml
tools/github-actions/new-version/packaged-action/LICENSE.txt

Simplify pom.xml for static code analyser and dependency checkers

chore: remove reference in pom.xml version

---

packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts

feat(design): add description to the exploded tokens

feat(design): add description to the exploded tokens

---

apps/chrome-devtools/package.json
apps/github-cascading-app/package.json
yarn.lock

fix: add missing devDependencies

fix: add missing dev dependency

---

package.json
packages/@o3r/components/package.json
packages/@o3r/rules-engine/package.json
yarn.lock

fix: jsonpath-plus audit update

---

.vscode/settings.json

chore: add auto generated yarn ignored files

chore: add auto generated yarn ignored files

---

packages/@o3r/design/package.json
yarn.lock

Increase peerDependencies supported range to prepare ng19 migration

chore(design): increase peerDependencies supported range

---

.yarnrc.yml
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

Renovate missed some deps in https://github.com/AmadeusITGroup/otter/pull/2617
Fixing them here.

chore: align missing deps for typescript-eslint

---

.yarnrc.yml
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

chore: dependency alignment

---

packages/@o3r/schematics/package.json
yarn.lock

We are still supporting ESLint 8.57 😄 

fix(deps): align peer deps for eslint

---

nx.json
packages/@o3r/styling/project.json

Small fix as a follow up of this comment: https://github.com/AmadeusITGroup/otter/pull/2642#discussion_r1909677921 

fix: styling compile inputs and named input for assets

---

packages/@o3r/design/src/core/design-token/parsers/design-token.parser.spec.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

fix(design): rendering of the typography design token

fix(design): rendering of the typography design token

---

.vscode/settings.json

chore: fix vscode rg issue on mac

---

apps/github-cascading-app/README.md
apps/github-cascading-app/src/cascading/cascading-probot.ts

fix(github-cascading-app): multi config warning message
docs(github-cascading-app): specify the considered configuration

fix(github-cascading-app): multi config warning message

---

packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/src/index.ts

feat: add message and explicit exit in create scripts
* :rocket: Feature resolves #2690

feat: add message and explicit exit in create scripts

---

.renovaterc.json5
docs/renovate/readme.md
tools/renovate/managers/github-node-version.json5

feat(pipeline): set pipeline version to node LTS version
* :rocket: Feature resolves #2697

feat(pipeline): set pipeline version to node LTS version

---

tools/renovate/managers/github-node-version.json5

fix: Renovate node version regex

fix: Renovate node version regex

---

.github/markdown-external-links.config.json

chore: ignore petstore basepath link
* :bug: Fix #2684

chore: ignore petstore basepath link

---

migration-guides/12.0.md

Migration guide for the deleted items from v12 and the deprecated items for v13.
@AmadeusITGroup/otter_admins Should I add the deprecated items for v14 as well?

feat: v12 migration guide

---

tools/@o3r/workspace-helpers/scripts/report-deprecates.mjs

fix(workspace-helpers): report deprecates npmjs url

fix(workspace-helpers): report deprecates npmjs url

---

packages/@o3r/workspace/schematics/ng-add/helpers/commit-hooks/index.ts

fix(workspace): add husky in dev workspace dependency

fix(workspace): add husky in dev workspace dependency

---

packages/@o3r/eslint-config/eslint.local.config.mjs
packages/@o3r/eslint-config/src/rules/typescript/import.cjs
tools/github-actions/new-version/packaged-action/LICENSE.txt

fix(eslint): yarn pnp support for import rules

---

packages/@o3r/eslint-config/schematics/index.it.spec.ts

fix(#2730): reactivate test for linter

---

.github/workflows/code-check.yml
.github/workflows/it-tests.yml
.yarn/sdks/eslint/bin/eslint.js
.yarn/sdks/eslint/lib/api.js
.yarn/sdks/eslint/lib/unsupported-api.js
.yarn/sdks/typescript/bin/tsc
.yarn/sdks/typescript/bin/tsserver
.yarn/sdks/typescript/lib/tsc.js
.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/sdks/typescript/lib/typescript.js
tools/github-actions/setup/action.yml

GitHub cache action is deprecated and needs to be upgraded.
Fix publish of release 10.4

fix: upgrade deprecated cache action

---

.yarnrc.yml
apps/showcase/package.json
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
package.json
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

chore: upgrade ngx-monaco-tree

---

nx.json

:rocket: Feature resolves #2746

feat: use new nx cache

---

apps/chrome-devtools/testing/setup-jest.ts
apps/showcase/testing/setup-jest.ts
docs/testing/UNIT_TESTS_SETUP.md
packages/@o3r/analytics/testing/setup-jest.ts
packages/@o3r/apis-manager/testing/setup-jest.ts
packages/@o3r/application/testing/setup-jest.ts
packages/@o3r/components/testing/setup-jest.ts
packages/@o3r/configuration/testing/setup-jest.ts
packages/@o3r/core/testing/setup-jest.ts
packages/@o3r/dynamic-content/testing/setup-jest.ts
packages/@o3r/forms/testing/setup-jest.ts
packages/@o3r/localization/testing/setup-jest.ts
packages/@o3r/logger/testing/setup-jest.ts
packages/@o3r/mobile/testing/setup-jest.ts
packages/@o3r/routing/testing/setup-jest.ts
packages/@o3r/rules-engine/testing/setup-jest.ts
packages/@o3r/store-sync/testing/setup-jest.ts
packages/@o3r/testing/schematics/ng-add/templates/project/testing/setup-jest.ts.template
packages/@o3r/testing/testing/setup-jest.ts
packages/@o3r/third-party/testing/setup-jest.ts
packages/@o3r/workspace/schematics/library/templates/jest/testing/setup-jest.ts.template
packages/@o3r/workspace/testing/setup-jest.ts

fix: jest setup for angular component testing

fix: jest setup for angular component testing

---

.github/workflows/main.yml
docs/renovate/readme.md
packages/@o3r/pipeline/schematics/ng-add/templates/github/__dot__github/actions/setup/action.yml
tools/github-actions/setup/action.yml

Migrate Node version to 22
* :rocket: Features
* #2621
* #2807

chore: migrate to Node LTS 22

---

README.md

docs: update link for rxjs

---

migration-guides/12.0.md

fix: migration guide for cascading-action to cascading app

---

apps/palette-generator/README.md
packages/@o3r/store-sync/README.md

Images in the palette generator readme were too large.

docs: image size for palette generator readme

---

.github/workflows/audit.yml
.github/workflows/codeql.yml
.github/workflows/main.yml
packages/@o3r/pipeline/schematics/ng-add/templates/github/__dot__github/workflows/main.yml

Activate main workflow on all PR

feat(pipeline): activate main workflow on all pr

---

packages/@o3r/create/README.md
packages/@o3r/create/src/index.it.spec.ts
packages/@o3r/testing/schematics/ng-add/index.ts

fix: o3r create with preset all and cms

---

packages/@ama-mfe/ng-utils/package.json

fix(publication): specify the access public for @ama-mfe/ng-utils

---

packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.ts

fix(resize): add 1px to the scrollheight as it is rounded

---

packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts

fix: enhance response exception if response.text() fails

---

packages/@ama-mfe/messages/README.md
packages/@ama-mfe/ng-utils/README.md
packages/@ama-mfe/ng-utils/src/navigation/README.md
packages/@ama-mfe/ng-utils/src/resize/README.md
packages/@ama-mfe/ng-utils/src/theme/README.md

Enrich npm documentation and service README.md
:rocket: Feature resolves #2898

chore: document @ama-mfe

---

packages/@ama-mfe/messages/package.json
packages/@ama-mfe/ng-utils/package.json
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.ts
packages/@ama-mfe/ng-utils/testing/babel.config.js
packages/@ama-mfe/ng-utils/testing/jest.config.ut.js
yarn.lock

chore: upgrade @amadeus-it-group/microfrontends to v0.0.3

---

docs/renovate/readme.md
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json.template
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/templates/__dot__renovaterc.json.template
tools/renovate/README.md

fix(renovate): add `v` prefix to tag versions
docs(renovate): recommend the version lock

fix(renovate): add `v` prefix to tag versions

---

packages/@ama-mfe/ng-utils/README.md
packages/@ama-mfe/ng-utils/src/managers/index.ts
packages/@ama-mfe/ng-utils/src/managers/utils.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.ts
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.ts
packages/@ama-mfe/ng-utils/src/theme/theme.producer.service.ts

Reduce boilerplate when registering producer
* :rocket: Feature resolves #2930

feat(#2930): reduce boilerplate when registering producer

---

apps/palette-generator/project.json

fix(palette-generator): add cache to palette generator application

fix(palette-generator): add cache to palette generator application

---

packages/@o3r/style-dictionary/README.md
packages/@o3r/style-dictionary/schematics/index.it.spec.ts
packages/@o3r/style-dictionary/schematics/ng-add/templates/config.__configExtension__
packages/@o3r/style-dictionary/src/filters/target-file.filter.mts
packages/@o3r/style-dictionary/src/formats/css-formatters/default.formatter.mts
packages/@o3r/style-dictionary/src/formats/css-formatters/gradients.formatter.mts
packages/@o3r/style-dictionary/src/formats/css-formatters/gradients.formatter.spec.ts
packages/@o3r/style-dictionary/src/formats/css-formatters/interface.formatter.mts
packages/@o3r/style-dictionary/src/formats/css-formatters/private.formatter.mts
packages/@o3r/style-dictionary/src/formats/css-formatters/private.formatter.spec.ts
packages/@o3r/style-dictionary/src/formats/css.format.mts
packages/@o3r/style-dictionary/src/formats/css.format.spec.ts
packages/@o3r/style-dictionary/src/formats/metadata.format.mts
packages/@o3r/style-dictionary/src/transforms/unit.transform.mts
packages/@o3r/style-dictionary/testing/mocks/dictionaries/gradient-token-ref.json
packages/@o3r/style-dictionary/testing/mocks/dictionaries/gradient-token.json

fix(style-dictionary): for corner case values
fix(style-dictionary): fallback file for token not matching rules
feat(style-dictionary): add support for gradient tokens

fix(style-dictionary): for corner case values

---

apps/showcase/src/assets/trainings/sdk/steps/api-manager/solution/app.config.ts
docs/logger/LOGS.md
packages/@o3r/apis-manager/src/apis-manager/api-manager.module.ts
packages/@o3r/apis-manager/src/apis-manager/api-manager.token.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.message.spec.ts
packages/@o3r/logger/src/services/logger/logger.module.ts
packages/@o3r/logger/src/services/logger/logger.spec.ts

As Angular move to standalone component,
I propose Provider instead of module with `.forRoot()`

feat: propose provider instead of module .forRoot()

---

SECURITY.md

Update the documentation with the versions that we currently support.
Dates based on Angular versioning: https://angular.dev/reference/releases

feat: update supported versions in documentation

---

packages/@o3r/style-dictionary/README.md

docs(style-dictionary): fix readme

---

apps/showcase/src/app/configuration/configuration.template.html

fix(showcase): configuration override toggle

---

tools/renovate/managers/renovate-otter-presets.json5

fix: support .renovaterc.json5

---

.github/workflows/code-check.yml
nx.json

ci: fix eslint cache

---

packages/@ama-mfe/ng-utils/package.json
packages/@ama-mfe/ng-utils/src/connect/connect.directive.spec.ts
packages/@ama-mfe/ng-utils/src/connect/connect.directive.ts
packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.spec.ts
packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.ts
packages/@ama-mfe/ng-utils/src/ng-package.json
packages/@ama-mfe/ng-utils/src/theme/theme.consumer.service.spec.ts
packages/@ama-mfe/ng-utils/src/theme/theme.consumer.service.ts
packages/@ama-mfe/ng-utils/src/theme/theme.helpers.spec.ts
packages/@ama-mfe/ng-utils/src/theme/theme.helpers.ts
packages/@ama-mfe/ng-utils/src/theme/theme.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/theme/theme.producer.service.ts
packages/@o3r/logger/package.json
yarn.lock

feat(ama-mfe-utils): integrate logger mechanism
* :rocket: Feature resolves #2887

feat(ama-mfe-utils): integrate logger mechanism

---

tools/github-actions/create-branch-e2e-screenshots/action.yml
tools/github-actions/update-e2e-screenshots/action.yml

feat(e2e): add logging in the github action to update the e2e screenshots

---

tools/github-actions/update-e2e-screenshots/action.yml

fix: missing s

---

packages/@o3r/core/src/store/async/async-entity.adapter.spec.ts
packages/@o3r/core/src/store/async/async-entity.adapter.ts

fix: always update global status for requestIds

---

packages/@o3r/apis-manager/src/apis-manager/api-factory.service.ts
packages/@o3r/apis-manager/src/apis-manager/api-manager.ts

fix: allow to get api with a particular config

---

docs/core/START_NEW_APPLICATION.md
packages/@o3r/core/README.md
packages/@o3r/create/README.md

docs: add warnings regarding `git bash`
* 📄 Docs:
* #2692
* #3015

docs: add warnings regarding `git bash`

---

packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/ng-add/helpers/commit-hooks/index.spec.ts
packages/@o3r/workspace/schematics/ng-add/helpers/commit-hooks/index.ts
packages/@o3r/workspace/schematics/ng-add/schema.json
packages/@o3r/workspace/schematics/ng-add/schema.ts

Fix a typo causing the commit to fail for a new Otter app

fix: typo on lint-staged

---

packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json

chore: update generator dependencies version

chore: update generator dependencies version

---

package.json

chore: reduce of 1s the postinstall script

chore: reduce of 1s the postinstall script

---

codecov.yml

fix: codecov config to reduce false positive and add palette generator

fix: codecov config to reduce false positive and add palette generator

---

apps/palette-generator/manifest.json

chore: change app ID to be published to Amadeus Store

chore: change app ID to be published to Amadeus Store

---

apps/showcase/tsconfig.app.json
packages/@ama-sdk/schematics/migration.json
packages/@ama-sdk/schematics/schematics/ng-update/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v12.1/clean-packagejson-exports.spec.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v12.1/clean-packagejson-exports.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@ama-sdk/schematics/testing/mocks/updates/v12/shell-package.json
packages/@ama-sdk/schematics/testing/mocks/updates/v12/shell-package.results.json
packages/@o3r-training/showcase-sdk/package.json
packages/@o3r-training/training-sdk/package.json

fix(sdk-generator): to support the module resolution bundler
Includes:
* 🐛 Fix resolves #3022

fix(sdk-generator): to support the module resolution bundler

---

packages/@o3r/core/package.json
tools/github-actions/update-e2e-screenshots/action.yml
tools/github-actions/update-e2e-screenshots/readme.md

feat: support multiple reports for the github action to update e2e screenshots

---

packages/@ama-mfe/ng-utils/README.md
packages/@ama-mfe/ng-utils/src/connect/connect.providers.ts
packages/@ama-mfe/ng-utils/src/host-info/host-info.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.ts
packages/@ama-mfe/ng-utils/src/utils.ts

feat(ama-mfe): remove host info token

---

tools/renovate/group/design-factory.json

fix(renovate): grouping for DF dependencies

fix(renovate): grouping for DF dependencies

---

.renovaterc.json5
nx.json
packages/@ama-mfe/messages/package.json
packages/@ama-mfe/ng-utils/package.json
packages/@ama-mfe/ng-utils/src/messages/error.sender.ts
tools/renovate/group/angular.json
tools/renovate/group/mfe.json
tools/renovate/otter-project.json
yarn.lock

chore(mfe): upgrade microfrontends packages + fix typings issue

---

apps/showcase/e2e-playwright/playwright-config.ts
apps/showcase/e2e-playwright/sanity/lighthouse-sanity.e2e.ts
apps/showcase/e2e-playwright/sanity/visual-sanity.e2e.ts
apps/showcase/e2e-playwright/scenarios/component-replacement-page-scenario.e2e-playwright-spec.ts
apps/showcase/e2e-playwright/scenarios/configuration-page-scenario.e2e-playwright-spec.ts
apps/showcase/e2e-playwright/scenarios/dynamic-content-page-scenario.e2e-playwright-spec.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.ts.template
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/sanity/__sanity@dasherize__.e2e.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/scenarios/__name@dasherize__.e2e-playwright-spec.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/utils/base-scenario.ts
packages/@o3r/testing/schematics/playwright/sanity/templates/__name@dasherize__.e2e.ts
packages/@o3r/testing/schematics/playwright/scenario/templates/__name@dasherize__.e2e-playwright-spec.ts

feat(testing): set base-url in playwright config

---

.github/workflows/main.yml

feat: add node compile cache to build process

feat: add node compile cache to build process

---

.gitignore
.vscode/mcp.json

chore: add mcp default config for NX suggestion

chore: add mcp default config for NX suggestion

---

packages/@o3r/testing/schematics/ng-add/playwright/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.ts.template

When adding Playwright via the Otter Testing generator, we should also start the local server

feature: testing generator starts local server for pw

---

tools/github-actions/create-branch-e2e-screenshots/action.yml
tools/github-actions/update-e2e-screenshots/action.yml

ci: fix logs in update e2e screenshots

---

tools/renovate/group/typescript.json

fix(renovate): typescript grouping including eslint dependency
See PR: https://github.com/AmadeusITGroup/otter/pull/3165

fix(renovate): typescript grouping including eslint dependency

---

packages/@o3r/analytics/schematics/index.it.spec.ts
packages/@o3r/apis-manager/schematics/index.it.spec.ts
packages/@o3r/components/schematics/index.it.spec.ts
packages/@o3r/configuration/schematics/index.it.spec.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/design/schematics/index.it.spec.ts
packages/@o3r/eslint-config-otter/schematics/index.it.spec.ts
packages/@o3r/eslint-config/schematics/index.it.spec.ts
packages/@o3r/extractors/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/index.it.spec.ts
packages/@o3r/pipeline/schematics/index.it.spec.ts
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/stylelint-plugin/schematics/index.it.spec.ts
packages/@o3r/styling/schematics/index.it.spec.ts
packages/@o3r/testing/schematics/index.it.spec.ts
packages/@o3r/third-party/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/index.it.spec.ts

Compute the relative path correctly for int test for all OS

test: cross os relative paths for int tests

---

.yarn/sdks/eslint/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json

chore: align dependencies

---

.github/markdown-external-links.config.json
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json

* :bug: Fix https://github.com/AmadeusITGroup/otter/issues/3186

ci: retry on 429 for external links

---

packages/@o3r/rules-engine/package.json
packages/@o3r/style-dictionary/src/formats/css.format.mts
packages/@o3r/style-dictionary/src/helpers/config-deflatten.helpers.mts
packages/@o3r/style-dictionary/src/helpers/sort-by-path.sort.helpers.mts
packages/@o3r/style-dictionary/src/helpers/sort-by-path.sort.helpers.spec.ts
yarn.lock

feat(style-dictionary): add better sorting for variables
* :rocket: Feature resolves #3192

feat(style-dictionary): add better sorting for variables

---

apps/intellij-extension/.gitignore
apps/intellij-extension/gradle/wrapper/gradle-wrapper.properties

chore: upgrade gradle

---

packages/@o3r/core/README.md
packages/@o3r/core/schematics/shared/presets/recommended.preset.ts
packages/@o3r/create/src/index.it.spec.ts

`@o3r/testing` should not be part of the recommended preset.

feat: o3r/testing should not be recommended

---

.yarn/sdks/eslint/package.json
.yarnrc.yml
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json

chore: add swc to nx to reduce pnp module resolutions

chore: add swc to nx to reduce pnp module resolutions

---

packages/@ama-sdk/core/README.md

chore(ama-sdk-core): remove deprecated in doc

chore(ama-sdk-core): remove deprecated in doc

---

migration-guides/13.0.md

doc(migration): add Protractor removal warning

doc(migration): add Protractor removal warning

---

package.json
yarn.lock

fix: yarn audit critical on form-data

---

migration-guides/13.0.md

Update the migration guide with removed items and instructions for ng update.

docs: update migration guide v13 with removed items

---

.vscode/mcp.json
tools/@o3r/mcp/README.md
tools/@o3r/mcp/package.json
tools/@o3r/mcp/src/instructions/best-practices.ts
tools/@o3r/mcp/src/mcp-server.ts
tools/@o3r/mcp/src/tools/best-practices.ts

Fallback https://github.com/AmadeusITGroup/otter/pull/3402/files as we need to copy the resources before running the mcp server

fix(mcp): fix run local mcp

---

nx.json
package.json
yarn.lock

chore: clean nx config

---

apps/showcase/package.json
packages/@ama-styling/style-dictionary/README.md
packages/@ama-styling/style-dictionary/package.json
packages/@ama-styling/style-dictionary/src/filters/target-file.filter.mts
packages/@ama-styling/style-dictionary/src/filters/target-file.filter.spec.ts
packages/@o3r/style-dictionary/package.json
packages/@o3r/style-dictionary/src/filters/target-file.filter.mts
packages/@o3r/style-dictionary/src/filters/target-file.filter.spec.ts
yarn.lock

chore: upgrade style-dictionary dependency

chore: upgrade style-dictionary dependency

---

apps/showcase/src/app/localization/localization.spec.ts
apps/showcase/src/app/rules-engine/rules-engine.spec.ts
apps/showcase/src/components/showcase/localization/localization-pres.spec.ts
apps/showcase/src/components/showcase/rules-engine/rules-engine-pres.spec.ts
nx.json

fix: linter issues

---

.github/workflows/main.yml

fix: allow nx caching on next branch

fix: allow nx caching on next branch

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java

This reverts commit e116c1500ef16d65cc7d1182500edbae1c919b74.

Revert "bugfix(ama-sdk): force json response when supported"

---

packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts
packages/@o3r/components/package.json
packages/@o3r/core/package.json
packages/@o3r/design/builders/generate-css/index.ts
packages/@o3r/design/builders/generate-jsonschema/index.ts
packages/@o3r/design/builders/generate-style/index.ts
packages/@o3r/localization/builders/helpers/localization.generator.ts
packages/@o3r/localization/package.json
packages/@o3r/rules-engine/builders/rules-engine-extractor/index.ts
packages/@o3r/rules-engine/package.json
packages/@o3r/styling/package.json
packages/@o3r/test-helpers/package.json
packages/@o3r/test-helpers/src/utilities/virtual-fs.ts
yarn.lock

chore: upgrade unionfs and unify globby imports

---

packages/@o3r/pipeline/schematics/ng-add/index.spec.ts
packages/@o3r/pipeline/schematics/ng-add/index.ts
packages/@o3r/pipeline/schematics/ng-add/schema.json
packages/@o3r/pipeline/schematics/ng-add/schema.ts
packages/@o3r/pipeline/schematics/ng-add/templates/github/__dot__github/workflows/main.yml

feat(#3290): add option for repository default branch name

---

.github/ISSUE_TEMPLATE/1-O3R-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/2-AMA-SDK-ISSUE-FORM.yaml

fix(#3228): replace eslint-config-otter by eslint-config and add missing ones

---

packages/@o3r/test-helpers/package.json
packages/@o3r/test-helpers/src/utilities/package-manager.ts
yarn.lock

feat(#3264): retrieve automatically the list of workspaces

---

packages/@o3r/extractors/schemas/migration.metadata.schema.json

fix: migration metadata schema

---

apps/showcase/package.json
package.json
tools/github-actions/audit/packaged-action/index.js
tools/github-actions/get-npm-tag/packaged-action/index.js
tools/github-actions/new-version/packaged-action/index.js
tools/github-actions/release/packaged-action/index.cjs
tools/github-actions/yarn-errors-reporter/packaged-action/index.js
yarn.lock

chore(deps): update ngx-monaco-tree to v20.1.0

---

apps/vscode-extension/package.json
apps/vscode-extension/src/chat/index.ts
apps/vscode-extension/src/extension.ts
yarn.lock

feat(vscode): use available tools linked to otter or angular to reply

---

.github/workflows/stale-issue-pr.yml

Mark and close stale issues and PRs using [actions/stale](https://github.com/actions/stale)

chore: mark and close stale issues and prs

---

.github/workflows/stale-issue-pr.yml

chore: add workaround issue as stale exception

chore: add workaround issue as stale exception

---

.github/workflows/stale-issue-pr.yml

fix: increase operations limit for stale issue workflow
