.github/workflows/publish.yml
nx.json
packages/@o3r/configuration/project.json
packages/@o3r/mobile/project.json
packages/@o3r/styling/project.json
packages/@o3r/styling/tsconfig.build.composite.json
packages/@o3r/styling/tsconfig.builders.json
packages/@o3r/testing/project.json

Remove incorrect outputs and dependency on project.json
Only package with non standard structure should have custom outputs and dependsOn properties
Remove the reference in o3r/styling/tsconfig.builders.json to the src folder (composite build)
o3r/styling builders have a dependency over the compiled package and should not try to compile it themselves

fix: schematics cache

---

packages/@ama-sdk/generator-sdk/src/generators/java-client-core/templates/swagger-codegen-java-client/src/main/resources/javaClient/README.mustache
packages/@ama-sdk/generator-sdk/src/generators/java-client-core/templates/swagger-codegen-java-client/src/main/resources/javaClient/pom.mustache
packages/@ama-sdk/generator-sdk/src/generators/java-client-core/templates/swagger-codegen-java-client/src/main/resources/javaClient/settings.mustache
packages/@ama-sdk/generator-sdk/src/generators/java-resteasy-client-core/templates/swagger-codegen-java-resteasy-client/src/main/resources/javaRestEasyClient/README.mustache
packages/@ama-sdk/generator-sdk/src/generators/java-resteasy-client-core/templates/swagger-codegen-java-resteasy-client/src/main/resources/javaRestEasyClient/settings.mustache

JFrog artifacts are no longer supported, use the new Azure repository

fix: remove deprecated jfrog url

---

packages/@ama-sdk/generator-sdk/project.json

Prevent adding other files than **.jar** to /templates/target folders for java generators

fix: sdk generators packaging

---

packages/@o3r/logger/src/services/logger/logger.service.ts
packages/@o3r/rules-engine/src/devkit/rules-engine-devtools.module.ts
packages/@o3r/rules-engine/src/devkit/rules-engine-devtools.service.ts

provide rules engine devtools service in root to have one instance in app root and lazy loaded features

fix: rules engine devtools service in root; logger service clients calls

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-class.extractor.ts

Issue:
When migrating to O3rComponent, getComponentType function calls getComponentStructure with the type surrounded by extra quotes (ex: "'Page'"). That results in defaulting to COMPONENT type.
The goal of the fix is to sanitize the extracted type, to have getComponentStructure working as expected.

fix: sanitize component type

---

packages/@o3r/components/src/stores/placeholder-template/placeholder-template.state.ts
packages/@o3r/rules-engine/src/services/rules-engine.effect.spec.ts
packages/@o3r/rules-engine/src/services/rules-engine.effect.ts

Today the placeholder supports facts variables : 
```
{
"template": "<p>My fact : <%= myFact %>",
"vars": {
"myFact ": {
"value": "myFact ",
"type": "fact"
}
}
}
```
The goal is to add support to an optional field, path, that will be used as a json path to extract a slice of a complex object:
```
{
"template": "<p>My cart data : <%= cart %>",
"vars": {
"cart": {
"value": "cart",
"type": "fact",
"path": "$.airOffers[*].offerItems[*].air.bounds[*].destinationLocation.countryCode"
}
}
}
```

feat: support jsonPath in placeholders

---

packages/@o3r/dev-tools/package.json
yarn.lock

The `src/cli/pcloudy.connection.js` CLI does not exist on `@o3r/dev-tools` package, only on `@o3r/mobile` one. This bin has to be removed.

fix(dev-tools): remove pcloudy bin from dev-tools package

---

packages/@o3r/localization/src/tools/localization.service.ts
packages/@o3r/testing/src/localization/localization-mock.ts

When using our default localization configuration, the supported language list is empty with english as a fallback language
We should not log messages in the case the requested language match the fallback
We should also count english as a supported language not to systematically compute the fallback language when requesting it

fix: reduce logging in unit test

---

docs/rules-engine/how-to-use/integration.md
docs/rules-engine/how-to-use/placeholders.md
packages/@o3r/components/src/stores/index.ts
packages/@o3r/components/src/stores/placeholder-request/index.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.actions.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.module.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.reducer.spec.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.reducer.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.selectors.spec.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.selectors.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.state.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.sync.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.actions.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.module.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.reducer.spec.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.reducer.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.selectors.spec.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.selectors.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.state.ts
packages/@o3r/components/src/stores/placeholder-template/placeholder-template.sync.ts
packages/@o3r/components/src/tools/placeholder/placeholder.component.ts
packages/@o3r/components/src/tools/placeholder/placeholder.module.ts
packages/@o3r/components/src/tools/placeholder/placeholder.spec.ts
packages/@o3r/rules-engine/src/fixtures/jest/rules-engine.service.fixture.jest.ts
packages/@o3r/rules-engine/src/services/rules-engine.effect.spec.ts
packages/@o3r/rules-engine/src/services/rules-engine.effect.ts
packages/@o3r/rules-engine/src/services/rules-engine.service.ts

__Previous Behavior__:
Today the current placeholder mechanism only allow to fetch a single URL to retrieve and display the template.
A common usage is to set an action as a result of a rule, and the RulesEngineService will trigger an action on the placeholder store.
The store contains a 1-1 mapping between placeholderId and url, and the fetch of the url + the rendering of the template is handled by the PlaceholderTemplateResponseEffect. The rendered template is set in the store, and is retrieved by the PlaceholderComponent that watch for a specific placeholderId.
__Issue__:
The issue with the current behavior is that as soon as we want to display a second message in the same placeholder, it forces to create a new template containing the 2 messages, and a a third one containing only the …

feat: support multiple templates in placeholders

---

.github/workflows/test-publish.yml
packages/@o3r/core/schematics/index.it.spec.ts

Persist the cache generated by yarn on the install of the test-app generated by the it tests
The cache should be created once per month and the same instance should be reused by all the build

feat: add cache for yarn for test-app on it tests

---

packages/@ama-sdk/core/src/plugins/simple-api-key-authentication/simple-api-key-authentication.request.ts
packages/@ama-sdk/core/src/plugins/simple-api-key-authentication/simple-api-key-authentication.spec.ts

Adapt the plugin to recent changes on the gateway to use the same override context model between different authentication modes.

fix: simple auth plugin - change office ID override parameter name

---

CONTRIBUTING.md
README.md

chore: fix new logo ratio on published documentation

---

packages/@o3r/core/schematics/module/templates/base/ng-package.json.template

Apply subentries fix on generated module. 
Move ng-package into the source folder to take the src folder as the root of the subentries instead of the package folder.
Include the scripts to target the src ng-package.json

fix: generators templates

---

packages/@ama-sdk/generator-sdk/src/generators/core/templates/swagger-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache

fix: generate request metadata default value to in SDK
- :bug: Fixes #286

fix: generate request metadata default value to in SDK

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts
packages/@o3r/components/builders/component-extractor/index.ts

Support nested configuration defined outside the configuration file.
Limitations : 
- import from the file where we have the definition
- import from one of the libraries specified in the builder configuration

feat: support external nested config

---

packages/@ama-sdk/core/src/fwk/mocks/alf-mock-adapter.ts
packages/@ama-sdk/core/src/fwk/mocks/base-mock-adapter.ts
packages/@ama-sdk/core/src/fwk/mocks/helpers.ts

Adding a last way to filter out several matches in the `packages/@ama-sdk/core/src/fwk/mocks/helper.ts` > `getPath` method, based on the HTTP method of the matching results.
- :bug: Fixes #296

fix: mock helper getPath - adding an HTTP method constraint when several matches

---

packages/@o3r/schematics/src/rule-factories/update-imports/update-imports-with-scope.ts
packages/@o3r/schematics/src/rule-factories/update-imports/update-ts-imports.ts
packages/@o3r/schematics/src/utility/loaders.ts
packages/@o3r/styling/schematics/ng-add/updates-of-old-otter-scope/imports/mocks/new.scss.result
packages/@o3r/styling/schematics/ng-add/updates-of-old-otter-scope/imports/mocks/old.scss

- ability to run scss update schematics on partially migrated code
- ng update helper functions can take into account all files in project

fix: enhance helpers for ng update schematics

---

.renovaterc.json

Add `release/*-next` branches in the Renovate update rules

feat: add release/*-next branches in the Renovate update rules

---

.github/workflows/pr-labels.yml
tools/@o3r/build-helpers/scripts/pr-labels.mjs

Fix the error in cascading PR when there is no immediate git log

fix: avoid error when not log history in -1

---

packages/@o3r/configuration/src/services/configuration/configuration.base.service.ts

The override of a component configuration can be done several time a flow with the same value
This happens if extension is done at component initialization. This is actually a common use case

fix: reduce logging noise on configuration

---

packages/@o3r/logger/src/services/logger/logger.service.ts
packages/@o3r/logger/src/services/logger/logger.spec.ts

Allow the dynamic registeration of LoggerClient to avoid issues with complex loggers (potential circular dependencies).

fix: register complex client at runtime

---

packages/@ama-sdk/core/schematics/ng-add/mocks/angular.mocks.json
packages/@ama-sdk/generator-sdk/collection.json
packages/@o3r/components/builders.json
packages/@o3r/components/testing/mocks/angular.mocks.json
packages/@o3r/core/builders.json
packages/@o3r/core/collection.json
packages/@o3r/core/migration.json
packages/@o3r/core/package.json
packages/@o3r/core/schematics/fixture/helpers.ts
packages/@o3r/core/testing/mocks/angular.mocks.json
packages/@o3r/localization/builders.json
packages/@o3r/rules-engine/builders.json
packages/@o3r/schematics/src/utility/loaders.ts
packages/@o3r/styling/builders.json
packages/@o3r/styling/collection.json
packages/@o3r/testing/migration.json
packages/@o3r/testing/schematics/ng-update/v9-0/index.ts
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/angular.mocks.json.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.result.ts.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.ts.template
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.spec.ts
packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.ts
packages/@o3r/testing/src/core/angular/component-fixture.ts
packages/@o3r/testing/src/core/component-fixture.ts
packages/@o3r/testing/src/core/helpers.ts
packages/@o3r/testing/src/core/playwright/component-fixture.ts
packages/@o3r/testing/src/core/protractor/component-fixture.ts
packages/@o3r/testing/testing/mocks/angular.mocks.json
packages/@o3r/testing/tsconfig.json

fix: throwOnUndefined to work with playwrigh
feat: add promise support to throwOnUndefined
Add support of Promise to `throwOnUndefined` to avoid breaking change of the fix
- :bug: Fixes 1441

fix: throwOnUndefined to work with playwrigh

---

packages/@o3r/dev-tools/src/utils/check-peer-deps.ts
packages/@o3r/schematics/package.json
packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts

Removing dependency of schematics to the dev-tools to avoid ESM / CommonJs clash
- :bug: Fixes #332

fix: remove the dependency of schematics to dev-tools

---

packages/@ama-terasu/cli/src/helpers/module.helper.ts
packages/@ama-terasu/cli/src/helpers/version.helper.ts
packages/@ama-terasu/cli/src/modules/base-yargs.ts

The issue was because node is keeping a cache of the `require.resolve` parsed folder.
Because of that, the dependency added at runtime are not returned by `require.resolve` and unfortunately Node does not give access to its cache.
The workaround is to use `fs` to resolve the package position main script position

fix: resolve new package with fs instead of node resolver

---

packages/@o3r/components/schematics/ng-add/index.ts
packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
packages/@o3r/schematics/src/utility/collection.ts
packages/@o3r/schematics/src/utility/index.ts
packages/@o3r/schematics/src/utility/loaders.ts
packages/@o3r/testing/schematics/ng-add/index.ts

Add Otter Schematics collections in the `ng g --help` output

feat: add otter schematics collection to ngCli at ngAdd time

---

packages/@o3r/core/schematics/module/templates/base/package.json.template
packages/@o3r/core/schematics/rule-factories/playwright/index.ts
packages/@o3r/testing/package.json
packages/@o3r/testing/src/core/playwright/element.ts
yarn.lock

`playwright` is only a devDep for `@o3r/testing`
When install after `@playwright/test` it cause the following issue when running `playwright` command.
```shell
Please install @playwright/test package to use Playwright Test.
npm install -D @playwright/test
```
- :bug: Fixes

fix: playwright integration

---

packages/@o3r/analytics/README.md
packages/@o3r/apis-manager/README.md
packages/@o3r/application/README.md
packages/@o3r/components/README.md
packages/@o3r/configuration/README.md
packages/@o3r/core/README.md
packages/@o3r/dev-tools/README.md
packages/@o3r/dynamic-content/README.md
packages/@o3r/eslint-config-otter/README.md
packages/@o3r/eslint-plugin/README.md
packages/@o3r/extractors/README.md
packages/@o3r/forms/README.md
packages/@o3r/localization/README.md
packages/@o3r/logger/README.md
packages/@o3r/mobile/README.md
packages/@o3r/routing/README.md
packages/@o3r/rules-engine/README.md
packages/@o3r/schematics/README.md
packages/@o3r/storybook/README.md
packages/@o3r/stylelint-plugin/README.md
packages/@o3r/styling/README.md
packages/@o3r/testing/README.md
packages/@o3r/third-party/README.md

Turn relative path to full path for the Otter Logo.
This fix the issue on [npmjs.org](https://www.npmjs.com/package/@o3r/core):

fix: logo URL in npmjs

---

packages/@o3r/schematics/project.json

Add missing package.json in schematics build builder's output

fix: add missing package.json in schematics build builder's output

---

.github/workflows/publish.yml

Fix the deployment of the cascading github app to deploy only the latest version of the app

fix: publish only latest cascading version

---

packages/@o3r/schematics/project.json

Remove incorrect cache output.
Task build-builders is in charge of compiling the typescripts and should only cache javascript files
Task prepare-build-builders does not impact the package.json file
Thus both task can rely on nx.json output
- :bug: Missing files in published @o3r/schematics

fix: correctly cache o3r/schematics schematics

---

packages/@ama-sdk/schematics/schematics/index.it.spec.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/schematics/schematics/ng-add/index.ts

When using `ng add @o3r/core` on an app, we are currently adding a devDependency to `@o3r/build-helpers` which is private and not published
Also fix yarn global caching issues when running in local
Also fix issue with `mkdir -p` not working as expected on Windows

fix: ng-add core add dev dependencies from the lib

---

.github/workflows/test-publish.yml
.verdaccio/.gitignore
.verdaccio/README.md
.verdaccio/conf/config.yaml
README.md
package.json

In case of failure on the it-tests, we'll now publish an artifact containing the storage of verdaccio, so we can download it and run the docker image locally with the same state as the CI

ci: publish verdaccio state in the PR in case of failure

---

packages/@ama-sdk/core/src/fwk/mocks/alf-mock-adapter.ts
packages/@ama-sdk/core/src/fwk/mocks/base-mock-adapter.ts
packages/@ama-sdk/core/src/fwk/mocks/mock-adapter.ts
packages/@ama-sdk/core/src/plugins/mock-intercept/mock-intercept.request.ts
packages/@ama-sdk/core/src/plugins/mock-intercept/mock-intercept.spec.ts

This PR adds the capability for the `BaseMockAdaper`  to accept a Promise that resolves to an array of `PathObject` in addition to accepting a simple array. This would enable the tree-shaking of the relatively big list of `PathObject` for production environments whilst still allowing for the mock adapter to take effect when enabled.
- :rocket: Feature [#(498)](https://github.com/AmadeusITGroup/otter/issues/498)

feat: enhance the BaseMockAdapter class to accept a function that returns a promise that resolves to PathObject[]

---

packages/@o3r/dynamic-content/src/stores/index.ts

export assets-path-override store module from dynamic-content package

fix: export assets-path-override store module

---

packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts
packages/@o3r/testing/src/core/protractor/angular-materials/autocomplete-material.ts

Using mat option tagname instead of class as the class changed with MDC 
- :bug: Fixes #520 

fix: Use tagname for mat-option in fixtures

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache

* Current behavior fails when we put a native type as return type of an api request, generating a revive for it
* Check the right property to determine whether to call the revive or not

fix: sdk generator - support native return types

---

packages/@o3r/testing/schematics/add-functions-to-fixture/helpers.ts
packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
packages/@o3r/testing/schematics/fixture-to-component/index.ts

Fixture methods are generated with deprecated `throwOnUndefined`
Fix also some text alignment

fix: fixtures generation

---

packages/@o3r/store-sync/src/sync-storage/interfaces.ts
packages/@o3r/store-sync/src/sync-storage/storage-sync.spec.ts
packages/@o3r/store-sync/src/sync-storage/storage-sync.ts

This PR introduces a fix for the issue: state not syncing with storage for feature modules
- :bug: Fixes #(https://github.com/AmadeusITGroup/otter/issues/534)
The basic difference between syncing a state in the root app module via StoreModule.forRoot versus in a feature through StoreModule.forFeature is the fact that in the former, the syncStateUpdate method receives the entire State where each feature is described by key-value pairs (eg: {cart: {items: []} checkout: {methods: []}}), whereas in the latter, the syncStateUpdate method receives the respective feature slice state (eg: {items: []} for cart and {methods: []} for checkout).
PFA the screenshots describing the same:
**Syncing in the app module**
**Syncing in the feature module**
Therefore, the latter scenario was not handled as it …

fix: state not syncing with storage for feature modules

---

.github/workflows/main.yml
.github/workflows/publish-pr.yml
.github/workflows/publish.yml
tools/github-actions/download-build-output/action.yml
tools/github-actions/upload-build-output/action.yml

Currently, for external contributions, the workflow is not able to access secrets variables, so the job `publish-pr` is failing
One solution is to create another workflow triggered by `workflow_run`:`completed` that handle the publication

ci: publish-pr on external workflow

---

packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
packages/@o3r/components/builders/component-extractor/index.ts

exclude only incompatible properties and not the full config
- :rocket: Feature #583

feat: #583: exclude only incompatible properties and not the full config

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/schematics/package.json
packages/@o3r/dev-tools/src/cli/version-harmonize.ts
yarn.lock

* Change ~ by ^ on schematics peer dep to allow more flexibility for users, a minor should not break the schematics
* get rid of useless dep on angular cli for generator sdk schematics package

fix: carret on peer dep and remove useless dep

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/index.mustache

size is the Java property for list length, not length

fix: do not export empty type on index with models

---

packages/@o3r/localization/src/tools/localization.service.spec.ts
packages/@o3r/localization/src/tools/localization.service.ts

The idea is to check if the specified language in the `LocalizationConfiguration` is defined in the supported locales and then set it as the default language of the `TranslateService` if supported.
- :bug: Fixes #(608) https://github.com/AmadeusITGroup/otter/issues/608

fix: Localization service sets the fallback language as the default language ignoring the language specified in the configuration

---

.github/workflows/code-check.yml
.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/test-publish.yml

disable nx cache on release branches, to prevent any issues on published packaged linked to input/output of nx configuration (force the failure instead)
It's sad but it seems that there is no clean way to reuse env variable defined in the main workflow in reusable ones (cf: https://github.com/orgs/community/discussions/26671#discussioncomment-3931817)

fix: disable nx cloud for release branches

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/helpers/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/base/enums.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/base/patterns.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/core/patterns.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/custom/enums.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/custom/patterns.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/api-mock.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/mock-factory/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/operation-adapter.ts

Add missing export in shell from sdk generator

fix: sdk generator - missing export in base shell

---

packages/@ama-sdk/core/src/fwk/api.helper.spec.ts
packages/@ama-sdk/core/src/fwk/api.helpers.ts
packages/@ama-sdk/core/src/fwk/clients/api-beacon-client.ts
packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/core/src/fwk/core/base-api-constructor.ts

If the API returns a success status code not described in the specification, fallback to the first defined success response code
- :bug:

fix: fallback on missing status code from API response

---

nx.json
packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@o3r/rules-engine/schematics/facts-service/index.spec.ts

Add `schematics` folder to inputs of nx task `test` to make sure the cache won't be reused when a file on schematics has been updated

ci: add schematics folder to unit tests nx-inputs

---

packages/@o3r/mobile/package.json
packages/@o3r/store-sync/package.json
packages/@o3r/store-sync/src/core/interfaces.ts
packages/@o3r/store-sync/src/core/storage-sync.ts
packages/@o3r/store-sync/src/sync-storage/interfaces.ts
packages/@o3r/store-sync/src/sync-storage/storage-sync.ts
packages/@o3r/store-sync/tsconfig.build.json
yarn.lock

Only synchronize with the localstorage states that do not match the version already stored.
Keep an internal representation of the state to avoid extra read operations that would slow the application

feat: do not synchronize untouched state with the localstorage [perf]

---

packages/@o3r/configuration/schemas/configuration.metadata.schema.json

Improve JSON schema for the config in order to improve the CMS UI thanks to widgets configuration
Here is an example of a generated config compatible with the update:
```
{
"name": "myProperty",
"description": "my description",
"type": "string",
"value": "default-value",
"label": "Label!",
"required": true,
"widget": {
"type": "STRING",
"parameters": {
"pattern": "[a-zA-Z0-9]+",
"arrayExample": ["val1", "val2"]
}
}
},
```

feat: Update JSON schema (config) for widget configuration + required field

---

packages/@o3r/create/package.json
packages/@o3r/create/src/index.ts
yarn.lock

Propagate the argument to the ng add otter schematic
- :rocket: Feature #723

feat: propagate the argument to the ng add otter schematic

---

packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
packages/@o3r/core/schematics/sdk/index.ts
packages/@o3r/core/schematics/sdk/schema.json
packages/@o3r/core/schematics/sdk/schema.ts

When creating an sdk inside a monorepo, add the possibility to generate the sdk based on specs passed via a new input.

feat: option to generate the sdk at sdk creation inside monorepo

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
yarn.lock

Fix some peer requirements
```shell
➤ YN0002: │ @ama-sdk/core@npm:9.3.0-alpha.25 [0ac57] doesn't provide @angular/cli (pfb8c0), requested by @o3r/schematics
➤ YN0002: │ @ama-sdk/core@npm:9.3.0-alpha.25 [0ac57] doesn't provide rxjs (p98433), requested by @o3r/schematics
➤ YN0002: │ @ama-sdk/core@npm:9.3.0-alpha.25 [e3e22] doesn't provide @angular/cli (p9b54a), requested by @o3r/schematics
➤ YN0002: │ @ama-sdk/core@npm:9.3.0-alpha.25 [e3e22] doesn't provide rxjs (p93e4b), requested by @o3r/schematics
```

chore: fix some peer dep warnings

---

.github/workflows/it-tests.yml
.verdaccio/conf/config-without-docker.yaml
.verdaccio/conf/config.yaml
package.json
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular.ts

- fix an issue when running it-tests on yarn, sometimes the internal packages (@o3r, @ama-sdk,..) were included in the cache
- add angular cache from it-tests to the cache artifact reused between builds
- removed uplink feature from verdaccio to make sure we always target local packages (also make the local publish faster)

ci: it-tests improvements

---

packages/@o3r/core/schematics/component/container/index.spec.ts
packages/@o3r/core/schematics/component/container/index.ts
packages/@o3r/core/schematics/component/presenter/index.spec.ts
packages/@o3r/core/schematics/component/presenter/index.ts
packages/@o3r/core/schematics/page/index.ts
packages/@o3r/core/schematics/rule-factories/component/analytics.ts
packages/@o3r/core/schematics/rule-factories/component/common.ts
packages/@o3r/core/schematics/rule-factories/component/configuration.ts
packages/@o3r/core/schematics/rule-factories/component/context.ts
packages/@o3r/core/schematics/rule-factories/component/fixture.ts
packages/@o3r/core/schematics/rule-factories/component/localization.ts
packages/@o3r/core/schematics/rule-factories/component/rules-engine.ts
packages/@o3r/core/schematics/rule-factories/component/theming.ts
packages/@o3r/core/testing/mocks/package.mocks.json

perf: make component generators rely on tree instead of file system

---

packages/@o3r/rules-engine/schemas/rulesets.schema.json

fix: ruleset json schema did not allow array values for operators rhs

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/core/project.json
packages/@ama-sdk/core/tsconfig.build.json

fix: do not export ama-sdk-core as es module by default

---

packages/@o3r/localization/src/tools/localized-currency.pipe.ts

Keep the same signatures exposed for the transform function of otter Currency pipe as the angular Currency pipe.
For that, a duplication of the third signature is needed, because this one is a superset of the others, but in angular Currency pipe it is exposed too.
- :bug: Fixes #293

fix: keep angular signatures for currency pipe

---

packages/@o3r/stylelint-plugin/package.json
packages/@o3r/testing/package.json
yarn.lock

- Remove jest-preset-stylint from the peer dependencies of @o3r/stylelint-plugin as it is only used for testing of the module (kept as devDependencies)
- Set pixelmatch and pngjs as optional in @o3r/testing as there are only used in the @o3r/testing/visual-test subpackage

fix: invalid peer dependencies

---

packages/@o3r/core/schematics/sdk/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts

before
`const getJestConfig = require('..\../jest.config.ut').getJestConfig;`
now                                   
`const getJestConfig = require('../../jest.config.ut').getJestConfig;`

fix: jest config extends path

---

packages/@ama-sdk/core/package.json
packages/@ama-sdk/core/schematics/ng-add/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@o3r/mobile/src/capacitor/storage/rehydrater.module.ts
yarn.lock

@o3r/schematics is only required to install @ama-sdk/core via the ng-add command and should not be a mandatory dependency but an optional peer dependency

fix: remove mandatory @o3r/schematics dependency on @ama-sdk/core

---

packages/@o3r/styling/package.json
packages/@o3r/styling/scss/theming/otter-theme/_functions.scss
packages/@o3r/styling/scss/theming/otter-theme/_material.scss

fix(styling): un-deprecate miss deprecated function
fix(styling): sass export paths
- :bug: Fixes #889

fix(styling): sass export paths

---

packages/@o3r/components/builders/component-extractor/helpers/component/component-class.extractor.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
packages/@o3r/components/schemas/component.metadata.schema.json
packages/@o3r/components/src/core/component.output.ts
packages/@o3r/extractors/src/utils/index.ts
packages/@o3r/extractors/src/utils/localization.ts
packages/@o3r/localization/builders/helpers/localization.generator.ts

Add mapping between localization key and component to allow contextualization in CMS
Example of component class metadata

feat(extractor): add mapping between localization key and component (localizationKeys)

---

packages/@o3r/styling/package.json
yarn.lock

The purpose is to simplifying the usage of the Sass helper without requiring Otter Core

fix(styling): turn @o3r/core dependency to optional

---

packages/@o3r/components/src/stores/placeholder-template/placeholder-template.selectors.ts
packages/@o3r/components/src/tools/placeholder/placeholder.component.ts
packages/@o3r/components/src/tools/placeholder/placeholder.interface.ts
packages/@o3r/components/src/tools/placeholder/placeholder.spec.ts

Add message events to inform third parties of placeholder updates
- :rocket: 18720

feat: post message events upon placeholder load

---

.gitignore
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/core/schematics/rule-factories/generic-updates/index.ts
packages/@o3r/core/schematics/sdk/index.ts

- updates on _gitignore_ when package manager is yarn
- sdk generator in monorepo to not touch yarn config

fix: ignore files when generating with yarn

---

apps/chrome-devtools/src/app-devtools/component-panel/component-panel-pres.component.ts
apps/chrome-devtools/src/services/ruleset-history.service.ts
apps/showcase/src/app/app.component.ts
packages/@o3r/dynamic-content/src/services/dynamic-content/dynamic-content.service.ts

The default `refCount: false` on shareReplay never closes the observable stream even if all subscriptions are properly unsubscribed
In most cases we don't want to keep it open

fix: use refcount for sharereplay when relevant

---

packages/@o3r/localization/builders/helpers/localization.generator.ts
packages/@o3r/localization/builders/localization-extractor/index.ts

fix(loc-extractor): do not resolve libraries files (empty libraries)

---

packages/@o3r/schematics/schematics/ng-add/index.ts

Fix following error:
```
×  nx run schematics:compile
Compiling TypeScript files for project "schematics"...
error TS5055: Cannot write file 'c:/git_clones/otter-public/packages/@o3r/schematics/dist/src/index.d.ts' because it would overwrite input file.
Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file 'c:/git_clones/otter-public/packages/@o3r/schematics/dist/src/interfaces/angular-workspace.d.ts' because it would overwrite input file.
Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file …
```

fix: o3r schematics build fails because it uses its own dist as input

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

Ensures that no reviver is generated for inner enums.
https://github.com/AmadeusITGroup/otter/issues/771

fix: sdk generated with inner enums

---

packages/@o3r/application/schemas/functional-content.metadata.schema.json
packages/@o3r/configuration/schemas/configuration.metadata.schema.json

Add a description for the properties named "required" for configuration and functional content metadata schemas

feat: add description for "required" properties in config/fc schemas

---

apps/showcase/src/app/app.component.ts

fix(showcase): unset dynamicpath when not in dynamic-content page

---

.github/workflows/publish-pr.yml
.github/workflows/publish.yml

Fix publish-pr when targeting a base branch other than `main`

ci: checkout base branch for publish-pr

---

packages/@o3r/rules-engine/src/engine/ruleset-executor.ts
packages/@o3r/rules-engine/src/services/rules-engine.service.it.spec.ts
packages/@o3r/rules-engine/testing/mocks/oneruleset-tworules-any-and-all.mock.ts

We can stop evaluating conditions as soon as one is false in an 'ALL' condition (as soon as one true for 'ANY' condition)
This avoid unnecessary errors when combining `isDefined` with another operator that expects the input fact to be defined for example
E.g.
```json
{
"elementType": "RULE_BLOCK",
"blockType": "IF_ELSE",
"condition": {
"all": [
{
"lhs": {
"type": "FACT",
"value": "outboundDate"
},
"operator": "isDefined"
},
{
"lhs": {
"type": "FACT",
"value": "outboundDate"
},
"operator": "duringSummer"
}
]
}
```
this is currently throwing an error that should not be thrown when `outboundDate` is undefined
`Error: Invalid left operand : undefined`

fix(rules-engine): avoid evaluating conditions when not needed

---

packages/@ama-sdk/core/src/plugins/bot-protection-fingerprint/bot-protection-fingerprint.request.ts
packages/@ama-sdk/core/src/plugins/bot-protection-fingerprint/bot-protection-fingerprint.spec.ts

Errors can be caught in angular error handling and logged properly
Logging in sdk should be enhanced in a dedicated feature

fix: log antibot exceptions as errors

---

packages/@ama-sdk/core/.npmignore
packages/@o3r/core/.npmignore
tools/@o3r/build-helpers/scripts/prepare-publish.mjs

Copy .npmignore into the dist folder
- :bug: Fixes #1006

fix(publish): copy npmignore into the dist folder

---

packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts
packages/@o3r/workspace/schematics/sdk/index.ts

fix: yarnrc was not generated in the same location as the templates

---

.renovaterc.json

We won't be updating `zone.js` and `bootstrap` on Otter 9
This will be put back on Otter 10

ci(renovate): exclude packages that wont be updated on main

---

packages/@o3r/workspace/schematics/application/index.ts

Fix error:
> Schematic "@o3r/core:ng-add" not found in collection "@o3r/workspace".
when running ` ng g create application` 

fix: create application not working

---

packages/@o3r/workspace/schematics/application/schema.json

Fix following issue:
> npm create @o3r test
> cd test
> npm exec ng g application test-app -- --standalone=false
> Error: Unknown argument: standalone

fix: additional properties not working for new application or component

---

docs/linter/eslint-plugin/rules/no-multiple-type-configuration-property.md
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/typescript/no-multiple-type-configuration-property/no-multiple-type-configuration-property.spec.ts
packages/@o3r/eslint-plugin/src/rules/typescript/no-multiple-type-configuration-property/no-multiple-type-configuration-property.ts
packages/@o3r/eslint-plugin/src/rules/typescript/o3r-widget-tags/o3r-widget-tags.ts
packages/@o3r/eslint-plugin/src/rules/utils.ts

Linter to detect invalid config property type.
Every property in [StrictConfiguration](https://github.com/AmadeusITGroup/otter/blob/main/packages/%40o3r/core/src/core/interfaces/configuration.ts#L27) can be for example `string` or `number` but not the both at the same time. 
It cannot be check with TypeScript, so I propose a linter for that.

feat(config): linter to detect invalid config property type

---

packages/@o3r/configuration/src/services/configuration/configuration.base.service.spec.ts
packages/@o3r/configuration/src/services/configuration/configuration.base.service.ts
packages/@o3r/configuration/src/stores/configuration/configuration.selectors.ts
packages/@o3r/configuration/src/stores/configuration/configuration.state.ts

Improve performance by not recomputing configuration if not impacted
- :rocket: Feature #1087

feat(config): improve performance by not recomputing configuration if not impacted

---

apps/showcase/project.json
apps/showcase/src/components/showcase/configuration/configuration-pres.config.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts
packages/@o3r/components/builders/component-extractor/index.ts
packages/@o3r/components/builders/component-extractor/schema.json
packages/@o3r/components/builders/component-extractor/schema.ts

Today categories are defined on each interface, listing for each one a mapping between the key and the displayed value.
It means that even if those categories are used application wise, they needs to be copy/pasted on all the config interfaces that uses it.
Define global categories in the extractor options.

feat(config): support global configuration categories

---

.github/workflows/publish-pr.yml

The logs only contain the version number on the first attempt

ci: fix publish-pr failing on rerun

---

.github/workflows/publish-pr.yml
tools/github-actions/download-build-output/action.yml

Publish a new artifact for each run attempt or a PR
The latest successful build will be used to populate the dist before publish
So if we re-run only a test for example, a new artifact will be published with the same content as the previous

ci: publish a new artifact when re-running the workflow

---

.yarnrc.yml

By default, any third party dependency can execute arbitrary code during the install process (with `postinstall` script)
We only want to allow that if needed for packages that we can trust
It can be re-activated for a specific package using `dependenciesMeta`
(It does not impact the `postinstall` scripts of the workspace which are considered safe)

fix: set enableScripts to false by default

---

.renovaterc.json

Activate Renovate [lockfileMaintenance](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance) once per week
- :rocket: Feature resolves #971

feat(renovate): activate lockfileMaintenance once per week

---

docs/dev-tools/DEV_TOOLS.md
packages/@o3r/dev-tools/README.md
packages/@o3r/dev-tools/src/cli/version-harmonize.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/.eslintrc.js.template

feat: setup new version-harmonize in linter rules
Update documentation of the ESLint rule replacing the `version-harmonize`.
- :rocket: Feature #960

feat: update version-harmonize documentation

---

apps/showcase/src/components/showcase/configuration/configuration-pres.config.ts
docs/configuration/CONFIGURATION_SUPPORTED_EXTRACTOR.md
packages/@o3r/components/src/core/component.output.ts
packages/@o3r/extractors/migration.json
packages/@o3r/extractors/package.json
packages/@o3r/extractors/schematics/ng-update/v10-0/configuration-extractor-categories/configuration-extractor-categories.spec.ts
packages/@o3r/extractors/schematics/ng-update/v10-0/configuration-extractor-categories/configuration-extractor-categories.ts
packages/@o3r/extractors/schematics/ng-update/v10-0/configuration-extractor-categories/mocks/angular.mocks.json.template
packages/@o3r/extractors/schematics/ng-update/v10-0/configuration-extractor-categories/mocks/config.mocks.result.ts.template
packages/@o3r/extractors/schematics/ng-update/v10-0/configuration-extractor-categories/mocks/config.mocks.ts.template
packages/@o3r/extractors/schematics/ng-update/v10-0/index.ts
packages/@o3r/extractors/src/utils/config-doc.spec.ts
packages/@o3r/extractors/src/utils/config-doc.ts
packages/@o3r/styling/package.json
yarn.lock

Today we use the xml format to specify categories in the configuration extractor.
Support JSDoc description as well for categories, to ensure consistency.
:rocket: Feature linked to #1119

feat(config): support jsdoc for categories declaration

---

.eslintignore
.eslintrc.js
.vscode/settings.json
.yarnrc.yml
docs/linter/eslint-plugin/rules/json-dependency-versions-harmonize.md
docs/linter/eslint-plugin/rules/yarnrc-package-extensions-harmonize.md
package.json
packages/@o3r/eslint-plugin/package.json
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/json-dependency-versions-harmonize.ts
packages/@o3r/eslint-plugin/src/rules/json/utils.ts
packages/@o3r/eslint-plugin/src/rules/yaml/utils.ts
packages/@o3r/eslint-plugin/src/rules/yaml/yarnrc-package-extensions-harmonize/yarnrc-package-extensions-harmonize.spec.ts
packages/@o3r/eslint-plugin/src/rules/yaml/yarnrc-package-extensions-harmonize/yarnrc-package-extensions-harmonize.ts
packages/@o3r/styling/package.json
packages/@o3r/workspace/package.json
yarn.lock

Provides a linter rule to align yarn package extensions versions with monorepo's one
- :rocket: Feature resolves #933

feat(eslint-plugin): yarnrc version harmonize

---

packages/@o3r/components/tsconfig.build.json
packages/@o3r/components/tsconfig.builders.json

Clean up component tsconfig file list

fix(component): clean up tsconfig file list

---

packages/@o3r/rules-engine/src/engine/ruleset-executor.ts

Deprecate executor's prepareRuleset function.
It can be removed in v11 as this function is not made to be used outside of the class (and would not have any effect if done)
- :rocket: Feature resolves #1044

fix(rules-engine): deprecate executor's prepareRuleset function

---

apps/showcase/src/app/app.component.html
apps/showcase/src/app/configuration/configuration.template.html
apps/showcase/src/app/dynamic-content/dynamic-content.template.html
apps/showcase/src/app/rules-engine/rules-engine.component.ts
apps/showcase/src/app/rules-engine/rules-engine.template.html
apps/showcase/src/components/showcase/basic/basic-pres.template.html
apps/showcase/src/components/showcase/configuration/configuration-pres.template.html
apps/showcase/src/components/showcase/dynamic-content/dynamic-content-pres.template.html
apps/showcase/src/components/showcase/localization/localization-pres.template.html
apps/showcase/src/components/showcase/rules-engine/rules-engine-pres.template.html
apps/showcase/src/components/showcase/sdk/sdk-pres.template.html
apps/showcase/src/components/utilities/in-page-nav/in-page-nav-pres.template.html
apps/showcase/src/styles.scss

Fixes deployed here https://fpaul-1a.github.io/otter

fix(showcase): lighthouse accessibility report

---

packages/@o3r/dev-tools/migration.json
packages/@o3r/dev-tools/package.json
packages/@o3r/dev-tools/schematics/ng-update/index.ts
packages/@o3r/dev-tools/src/cli/git-release-management.ts

Finishing touches for deprecation of `@o3r/dev-tools`

feat: update of @o3r/dev-tools deprecation

---

docs/rules-engine/operators.md
packages/@o3r/rules-engine/src/engine/operator/operator.helpers.spec.ts
packages/@o3r/rules-engine/src/engine/operator/operator.helpers.ts
packages/@o3r/rules-engine/src/engine/operator/operators/array-based.operators.ts
packages/@o3r/rules-engine/src/engine/operator/operators/basic.operators.spec.ts
packages/@o3r/rules-engine/src/engine/operator/operators/basic.operators.ts

Currently it is not possible to have in the conditions something like the following: 
> **stringFact** matches **pattern**
Where "stringFact" is whatever string and "pattern" is a regular expression like "/^8[0-9]{3}/"
- :rocket: Feature #1120

feat: matches basic operator

---

packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/plugins/core/fetch-plugin.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

Stop and restart the timeout fetch plugin in case a specific event interrumpts the fetch request. 
Add event emitter to pause the timeout if an imperva captcha has been detected.

feat: captcha support on sdk plugins

---

packages/@o3r/application/package.json
packages/@o3r/components/builders/component-extractor/index.ts
packages/@o3r/components/package.json
packages/@o3r/configuration/package.json
packages/@o3r/localization/builders/localization-extractor/index.ts
packages/@o3r/localization/package.json
packages/@o3r/rules-engine/package.json
packages/@o3r/styling/package.json

Fix issue with builders requiring JSON schemas that are not exported in the package.json
> Error: Package subpath './schemas/localization.metadata.schema.json' is not defined by \"exports\"

fix: it-tests

---

packages/@o3r/schematics/package.json
packages/@o3r/schematics/src/rule-factories/eslint-fix/index.ts
yarn.lock

Currently `eslint` command is run by the schematics even if not installed.
So a check is added before applying the logic to run the `eslint` command.

fix(schematics): do not run eslint if not installed

---

package.json
yarn.lock

Removing @o3r/workspace build on post install (as the task are now handled by the linter only)
Before:
After:

feat: reduce postinstall time

---

apps/showcase/src/app/app.component.spec.ts
apps/showcase/src/app/app.component.ts
apps/showcase/src/app/app.module.ts
apps/showcase/src/main.ts
packages/@o3r/application/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/components/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/configuration/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.console.service.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.console.spec.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.interface.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.token.ts
packages/@o3r/core/src/core/devkit/devtools.interface.ts
packages/@o3r/localization/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/localization/src/devkit/localization-devkit.interface.ts
packages/@o3r/localization/src/devkit/localization-devtools.console.service.ts
packages/@o3r/localization/src/devkit/localization-devtools.service.ts
packages/@o3r/localization/src/devkit/localization-devtools.token.ts
packages/@o3r/rules-engine/schematics/ng-add/helpers/devtools-registration.ts
packages/@o3r/schematics/src/rule-factories/dev-tools/devtools-registration.spec.ts
packages/@o3r/schematics/src/rule-factories/dev-tools/devtools-registration.ts

Expose an api on window for the contextualization functionalities

feat(contextualization): expose api on window

---

.github/workflows/it-tests.yml

In the current state, the run of it-tests on `[windows-latest, yarn]` is slow and fails most of the time (related to concurrent access to the disk)
This specific combination does not bring a lot of value since we already cover `[linux, yarn]` and `[windows, npm]`, so I propose to disable it, at least until we find a way to make it reliable 

ci: disable it-tests for windows-latest,yarn

---

packages/@o3r/application/migration.json
packages/@o3r/application/package.json
packages/@o3r/application/schemas/cms.schema.json
packages/@o3r/application/schematics/ng-add/helpers/cms-registration.ts
packages/@o3r/application/schematics/ng-add/helpers/templates/cms.json.template
packages/@o3r/application/schematics/ng-add/index.ts
packages/@o3r/application/schematics/ng-add/ng-update/index.ts
packages/@o3r/application/schematics/ng-add/ng-update/v10.0/update-cms-config.ts
packages/@o3r/design/src/core/design-token/design-token.spec.ts
packages/@o3r/styling/schemas/style.metadata.schema.json

Add the JSON Schema for the styling metadata and the cms.json file
Creation of the `cms.json` file by the `ngAdd` of the `@o3r/application` package.
- :rocket: Feature resolves #1042

feat: add schema for CMS.json and Style metadata

---

packages/@o3r/application/schematics/ng-add/helpers/cms-registration.ts
packages/@o3r/core/schematics/rule-factories/store/index.ts

The fix regarding the absolute path for the `templates` seems to be linked to https://github.com/angular/angular-cli/issues/17921

fix: v10 IT tests

---

packages/@o3r/workspace/schematics/ng-add/project-setup.ts

- :bug: Fixes #1189
In `@o3r/workspace` ng-add script, `addWorkspacesToProject` is adding the `workspaces` field to the root `package.json`.
We should execute this step last, after adding all other dependencies, otherwise yarn gets confused and doesn't know where to add the dependencies (to the root or to a workspace).

fix(schematics): o3r create command not working for yarn 1

---

.github/workflows/code-check.yml
.github/workflows/it-tests.yml

dorny/test-reporter doesn't support artifact v4
https://github.com/AmadeusITGroup/otter/issues/1198

ci: downgrade upload-artifact to v3

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

To avoid reviving non object models in the revivers, the generator checks the nonObjectDefinition vendor of the property. This means that the property is based on a model which is not an object and therefore cannot be revive, the revival will be skipped.
As a reviver should handle both the model properties and the ones inherited from the parents, it is based on the allVars property which was forgotten prior to this PR. 
Today, we do not add the correct vendor on the allVar property used in the templates but rely on the isEnumRef and isEnum property of the models. Unfortunately, they are false in case of Maps and Arrays.
Add nonObjectModel vendor to the allVars properties and remove the logic to detect enum within Map and Array as it is faulty.
An additional fix cleans the unused import to …

fix: #1232 Enum revivers and unused imports

---

package.json
packages/@ama-sdk/core/schematics/ng-add/index.spec.ts
packages/@ama-sdk/core/schematics/ng-add/index.ts
packages/@o3r/apis-manager/schematics/ng-add/index.ts
packages/@o3r/core/package.json
packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/core/schematics/ng-add/project-setup/index.ts
packages/@o3r/extractors/schematics/ng-add/index.ts
packages/@o3r/schematics/schematics/ng-add/index.ts
packages/@o3r/store-sync/schematics/ng-add/index.ts
packages/@o3r/storybook/schematics/ng-add/index.ts
packages/@o3r/test-helpers/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/workspace/package.json
packages/@o3r/workspace/schematics/ng-add/index.ts
packages/@o3r/workspace/schematics/ng-add/project-setup.ts

Today, with `yarn 1`
```shell
yarn create @o3r my-workspace
cd my-workspace
yarn ng g application my-app
```
we get:
```shell
✔ Packages installed successfully.
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
✖ Package install failed, see above.
The Schematic workflow failed. See above.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

fix: ng g application with yarn 1

---

.verdaccio/.gitignore
jest.config.js
packages/@o3r/core/package.json
packages/@o3r/core/schematics/component/presenter/index.ts
packages/@o3r/core/schematics/component/schema.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/core/schematics/rule-factories/component/design-token.ts
packages/@o3r/core/schematics/shared/presets/all.preset.ts
packages/@o3r/design/collection.json
packages/@o3r/design/schematics/design-token-to-component/index.spec.ts
packages/@o3r/design/schematics/design-token-to-component/index.ts
packages/@o3r/design/schematics/design-token-to-component/schema.json
packages/@o3r/design/schematics/design-token-to-component/schema.ts
packages/@o3r/design/schematics/design-token-to-component/templates/__fileName__.template
packages/@o3r/design/schematics/generate-css/schema.json
packages/@o3r/design/schematics/ng-add/index.ts
packages/@o3r/design/schematics/ng-add/schema.json
packages/@o3r/design/schematics/ng-add/schema.ts
packages/@o3r/workspace/package.json

Add generation of the Design token file with the component when the package is added to the project
- :rocket: Feature #1249

feat: add design token file to component generation

---

packages/@o3r/analytics/src/fixtures/jasmine/ng-package.json
packages/@o3r/analytics/src/fixtures/jest/ng-package.json
packages/@o3r/analytics/src/ng-package.json
packages/@o3r/apis-manager/ng-package.json
packages/@o3r/application/ng-package.json
packages/@o3r/components/src/ng-package.json
packages/@o3r/components/src/rules-engine/ng-package.json
packages/@o3r/configuration/src/fixtures/jasmine/ng-package.json
packages/@o3r/configuration/src/fixtures/jest/ng-package.json
packages/@o3r/configuration/src/ng-package.json
packages/@o3r/configuration/src/rules-engine/ng-package.json
packages/@o3r/core/ng-package.json
packages/@o3r/dynamic-content/src/fixtures/jasmine/ng-package.json
packages/@o3r/dynamic-content/src/fixtures/jest/ng-package.json
packages/@o3r/dynamic-content/src/ng-package.json
packages/@o3r/dynamic-content/src/rules-engine/ng-package.json
packages/@o3r/forms/ng-package.json
packages/@o3r/localization/src/ng-package.json
packages/@o3r/localization/src/rules-engine/ng-package.json
packages/@o3r/logger/src/ng-package.json
packages/@o3r/logger/src/services/fullstory-logger-client/ng-package.json
packages/@o3r/logger/src/services/logrocket-logger-client/ng-package.json
packages/@o3r/logger/src/services/smartlook-logger-client/ng-package.json
packages/@o3r/routing/src/ng-package.json
packages/@o3r/rules-engine/src/fixtures/jasmine/ng-package.json
packages/@o3r/rules-engine/src/fixtures/jest/ng-package.json
packages/@o3r/rules-engine/src/ng-package.json
packages/@o3r/store-sync/ng-package.json
packages/@o3r/styling/ng-package.json

Fix one build issue of https://github.com/AmadeusITGroup/otter/pull/1243
Linked to https://github.com/ng-packagr/ng-packagr/commit/5ff4afde43b4984bf7f64ce991dfe255b1fb9373

fix: fix wrong ng-packagr schema for secondary entry points

---

apps/showcase/package.json
packages/@o3r/core/package.json
packages/@o3r/workspace/package.json
yarn.lock

ngrx-local-storage bumped ng version to 17 in their 16.1 minor
https://github.com/btroncone/ngrx-store-localstorage/releases/tag/v16.1.0
this brings peer deps issues as in o3r v9.x we have ng 16
Result: block the minor version of ngrx-local-storage peer dep

fix: ngrx-local-storage strict range

---

packages/@o3r/artifactory-tools/README.md
packages/@o3r/artifactory-tools/src/cli/artifact-cleaner.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.console.service.ts
packages/@o3r/configuration/src/devkit/configuration-devtools.service.ts
packages/@o3r/configuration/src/services/configuration/configuration.base.service.spec.ts
packages/@o3r/dev-tools/README.md
packages/@o3r/extractors/src/utils/common.ts
tools/github-actions/cascading/action.yml
tools/github-actions/cascading/src/cascading.ts

Similarly to https://github.com/AmadeusITGroup/otter/issues/1190, the goal is to cleanup references to RefX.
There are still references in the:
To be discussed if those references are to be kept or not.

fix: cleanup refx refs

---

packages/@ama-sdk/core/package.json

Add typings for deep import path for classic node module resolution

fix(sdk-core): add typings for deep import

---

.github/workflows/code-check.yml

Disable the link URL checks because they are mainly due to new breaking changes on main branch.

chore: disable link checks

---

packages/@o3r/telemetry/src/builders/index.ts
packages/@o3r/telemetry/src/schematics/index.ts
packages/@o3r/telemetry/src/sender/index.ts

Avoid awaiting the metric report call
- :bug: Fixes #1201

fix(metric): avoid awaiting the metric report call

---

apps/showcase/package.json
apps/showcase/update-screenshots.cjs

Provide a script to generate visual-testing screenshots regardless of operating system

test: add script to update screenshots

---

packages/@o3r/analytics/schematics/index.it.spec.ts
packages/@o3r/apis-manager/schematics/index.it.spec.ts
packages/@o3r/components/schematics/index.it.spec.ts
packages/@o3r/configuration/schematics/index.it.spec.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/extractors/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/index.it.spec.ts
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/styling/schematics/index.it.spec.ts
packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular-with-o3r-core.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-angular.ts
packages/@o3r/test-helpers/src/utilities/angular.ts
packages/@o3r/test-helpers/src/utilities/git.ts
packages/@o3r/test-helpers/src/utilities/index.ts
packages/@o3r/testing/schematics/index.it.spec.ts

test: add checks based on git diff in it tests

---

packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/scss/theming/_functions.scss
packages/@o3r/styling/scss/theming/_mixins.scss
packages/@o3r/styling/scss/utils/_functions.scss

fix: resolve css subentry path in extract-style

---

packages/@o3r/testing/src/core/playwright/component-fixture.ts
packages/@o3r/testing/src/core/playwright/element.ts

Resolve the element in throwOnUndefined
Remove user simulated behaviour and replace it with playwright's standard methods
- :bug: throwOnUndefined does not resolve with element
- :bug:  setValue inconsistent behaviour

fix: playwright fixtures issues

---

packages/@o3r/core/package.json
packages/@o3r/rules-engine/src/engine/ruleset-executor.ts

Follow up on #1044 
The comment mentions that it should be removed in v10. 
If it's too early we can do it in v12.

fix: remove deprecated prepareRuleset method

---

docs/telemetry/README.md
packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/src/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@o3r/extractors/package.json
packages/@o3r/extractors/src/core/wrapper.ts
packages/@o3r/schematics/src/utility/wrapper.ts
packages/@o3r/telemetry/schematics/ng-add/index.ts
packages/@o3r/telemetry/src/builders/index.ts
packages/@o3r/telemetry/src/environment/index.ts
packages/@o3r/telemetry/src/schematics/index.spec.ts
packages/@o3r/telemetry/src/schematics/index.ts
yarn.lock

- question to activate telemetry
- documentation
- :rocket: Feature #1201

feat(metrics): question to activate telemetry + documentation

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/src/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@o3r/create/src/index.ts

This PR fixes the following problem: in case a sub process started by `npm create @ama-sdk` or `npm create @o3r` fails (i.e. exiting with a non-zero code, for example, if the spec file given to the sdk generator does not exist, or if there is a dependency conflict when doing `npm install` as it was the case recently), the `npm create` command itself was hiding the error and exiting with 0.

fix(create): fail and show error if sub-process exits with non-zero code

---

packages/@o3r/test-helpers/src/test-environments/create-test-environment-blank.ts

Small PR to not call `yarn set version` from it-tests that use npm.
Note that `setPackagerManagerConfig` already takes care of setting yarn version in case yarn is used.

test: remove yarn-related command from npm it-tests

---

packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts

It's a small bugfix to avoid deleting @o3rCategory property.
The else clause was used whenever the category was defined locally.
| Local category | Global category | Before fix | After fix |
|---|---|---|---|
| FALSE | FALSE | category deleted | category deleted |
| FALSE | TRUE | category kept | category kept |
| TRUE | TRUE | category deleted | **category kept** |
| TRUE | FALSE | category deleted | **category kept** |

fix: avoid deleting property if category defined locally

---

packages/@o3r/telemetry/src/schematics/index.spec.ts
packages/@o3r/telemetry/src/schematics/index.ts

We should not wait for tasks to complete because if there are none the schematics will fail.
maybe we can open an issue to ask [executePostTasks](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/schematics/src/engine/engine.ts#L380) to not throw an error when we do `lastValueFrom` if there are no tasks pending

fix(telemetry): do not wait for tasks

---

packages/@o3r/create/package.json
packages/@o3r/create/src/index.ts
packages/@o3r/design/package.json
packages/@o3r/test-helpers/src/utilities/package-manager.ts
yarn.lock

As most npm users do not enable the legacy-peer-deps option (it is not enabled by default), it is important run npm it-tests without it.

test: remove legacy-peer-deps with npm in it-tests

---

packages/@o3r/localization/src/devkit/localization-devtools.console.service.ts

When we had too many localization keys to update the application was freezing.
If we use `setTranslation` once instead of `set` for every keys it's much more faster.
(improvement from ~20ms per key to less than 100ms for all keys)

fix(devkit): improve localization override performances

---

packages/@o3r/localization/src/devkit/localization-devtools.console.service.ts

Issue happens only when switching back to a language already loaded.

fix(devkit): remove call to appRef.tick because refresh is already handled by setTranslation

---

packages/@o3r/schematics/src/rule-factories/ng-add/dependencies.ts
packages/@o3r/workspace/schematics/library/index.spec.ts
packages/@o3r/workspace/schematics/library/index.ts

Fix the generation of `library` by avoiding call twice the `ng-add` schematics from `@o3r/core`

fix: schematic generating library

---

packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts

fix: missing peer deps in eslint-config-otter

---

.yarn/sdks/eslint/package.json
tools/github-actions/audit/package.json
tools/github-actions/cascading/package.json
tools/github-actions/get-npm-tag/package.json
tools/github-actions/new-version/package.json
yarn.lock

Follow up on #1424
The name is missing for Github Action packages.
According to the NPM doc, the [name is required](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields).

fix: missing package name for gh actions

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.generator.ts
packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/openapitools.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/openapitools.json.template
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
packages/@ama-sdk/showcase-sdk/package.json

Possibility of generating typescript SDK without revivers when they are not necessary.
Configuration in `openapitools.json` and combination of provided options.
- :rocket: Feature [#(1337)](https://github.com/AmadeusITGroup/otter/issues/1337)

feat: configure light SDK with openapitools.json and options

---

packages/@ama-sdk/create/src/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/dependencies.ts
packages/@o3r/schematics/src/utility/wrapper.ts

Ask only once to install telemetry when creating an sdk
- :bug: Fixes #1408

fix(telemetry): ask only once to install telemetry when creating an sdk

---

.github/actions/setup-java/action.yml

Bumping to v5 https://github.com/stCarolas/setup-maven/releases/tag/v5 that runs on Node 20.

chore: bump stCarolas/setup-maven GH Action

---

packages/@ama-sdk/core/src/clients/api-angular-client.ts

The angular client in `@ama-sdk/core` creates an abort controller, but there is no way to abort the request, so that part of the code is useless and should be removed. Also the correct way to abort a request with [httpClient.request](https://angular.io/api/common/http/HttpClient#request) is to unsubscribe from the observable (and not to pass a signal to the request method).

fix(ama-sdk-core): removing useless abort controller in angular client

---

packages/@o3r/test-helpers/src/test-environments/create-test-environment-blank.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-otter-project.ts
packages/@o3r/test-helpers/src/utilities/create-with-lock.ts

As shown [here](https://github.com/AmadeusITGroup/otter/actions/runs/8176333422/job/22356066726?pr=1460#step:12:66) it is possible for a race condition to happen while creating the `it-tests` folder. This PR removes the `useLocker` option in `createWithLock` to force the usage of the locker (and hopefully avoid such race conditions).

fix(test-helpers): remove useLocker option in createWithLock

---

nx.json
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/json-dependency-versions-harmonize.spec.ts
packages/@o3r/eslint-plugin/src/rules/json/json-dependency-versions-harmonize/json-dependency-versions-harmonize.ts

Add `resolutions` field support to version harmonize
- :rocket: Feature resolves #1448

feat(eslint-plugin): add resolutions field support to version harmonize

---

migration-guides/10.0.md

Add migration details for pipe rename (even if the migration is handled by the `ng update` script).
- :rocket: Feature #1253

docs: v10 migration guide for pipe rename

---

packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/plugins/core/request-plugin.ts

Adds the ability to abort requests in `@ama-sdk/core` (and any request of an SDK generated by the Otter SDK generator) by passing an [abort signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) in metadata. It is implemented both for the fetch and the angular client.

feat(ama-sdk-core): abort requests by passing an abort signal in metadata

---

staticwebapp.config.json

Currently on the compodoc, if we target a page that does not exist, we land on a broken page
https://docs.otter.digitalforairlines.com/THIS/LINK/IS/BROKEN.html
We should land on a 404 page

docs(compodoc): prevent broken fallback on 404

---

apps/chrome-devtools/src/app-devtools/component-panel/component-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/component-panel/component-panel-pres.template.html
packages/@o3r/components/src/devkit/components-devkit.interface.ts
packages/@o3r/components/src/devkit/components-devtools.message.service.ts

fix(chrome-ext): display a specific message when component selection is not available

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/src/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/schema.json
packages/@ama-sdk/schematics/schematics/typescript/shell/schema.ts

When running `npm create @ama-sdk typescript my-package`, I would intuitively expect a `my-package` package to be created in `my-package` folder.
What currently happens is the creation of the `@sdk/my-package` package inside the `sdk/my-package` folder. Why is this `sdk` scope added? I suggest in this PR to remove the `sdk` default scope.

feat(ama-sdk-create): allow creation without a scope

---

packages/@o3r/rules-engine/builders/rules-engine-extractor/helpers/rules-engine.extractor.ts

An issue was raised regarding duplicated operators in the rules.operators.metadata.json file, so the proposed fix is to filter the operators before adding them in the file

fix: duplicates of operators in rules-engine

---

apps/vscode-extension/src/intellisense/design-token.ts
apps/vscode-extension/tsconfig.json

Add caching to the parsed design token files mechanism
- :rocket: Feature resolves #1490

fix(vscode): add caching to the parsed design token files

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

Build is failing due to the extra parenthesis in the reviveModel functions.

fix: remove extra ) in sdk templates

---

.renovaterc.json5
.vscode/settings.json
docs/renovate/readme.md
packages/@ama-sdk/schematics/schematics/ng-update/typescript/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v10.1/add-presets-renovate.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json
packages/@o3r/workspace/migration.json
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/templates/__dot__renovaterc.json.template
packages/@o3r/workspace/schematics/ng-update/index.ts
packages/@o3r/workspace/schematics/ng-update/v10.1/add-presets-renovate.ts
tools/renovate/base.json
tools/renovate/design-factory.json
tools/renovate/otter-project.json
tools/renovate/sdk-spec-upgrade.json
tools/renovate/sdk.json

Split and export renovate presets
- :rocket: Feature resolves #1483

feat: split and export renovate presets

---

packages/@o3r/rules-engine/builders/rules-engine-extractor/helpers/rules-engine.extractor.interfaces.ts
packages/@o3r/rules-engine/builders/rules-engine-extractor/helpers/rules-engine.extractor.ts
packages/@o3r/rules-engine/builders/rules-engine-extractor/index.ts
packages/@o3r/rules-engine/package.json
yarn.lock

Currently schema files are being created for all facts that have non-standard types or are of type enum. The goal is to only create schema files for facts of type object.

feat: only create schema file for facts of type object

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@o3r/analytics/schematics/index.it.spec.ts
packages/@o3r/apis-manager/schematics/index.it.spec.ts
packages/@o3r/components/schematics/index.it.spec.ts
packages/@o3r/configuration/schematics/index.it.spec.ts
packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/create/src/index.it.spec.ts
packages/@o3r/design/schematics/index.it.spec.ts
packages/@o3r/extractors/schematics/index.it.spec.ts
packages/@o3r/localization/schematics/index.it.spec.ts
packages/@o3r/rules-engine/schematics/index.it.spec.ts
packages/@o3r/styling/schematics/index.it.spec.ts
packages/@o3r/test-helpers/package.json
packages/@o3r/test-helpers/src/jest-environment/index.ts
packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/public_api.ts
packages/@o3r/testing/schematics/index.it.spec.ts
yarn.lock

Use a jest custom environment to be able to use the jest lifecycle events to clean the workspace only if the test succeeds

test: use jest custom environment for it-tests

---

packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/testing/mocks/MOCK_DATE_UTILS_swagger.yaml

Add a new use case to make sure non light sdk will not throw errors after generation
- :bug: Add test cases for https://github.com/AmadeusITGroup/otter/pull/1537

chore: enhance testing on sdk generation with or without reviver

---

packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
packages/@o3r/eslint-config-otter/typescript.cjs

fix(eslint-config): use jest rule only if jest dependency is found

---

.github/workflows/publish.yml
apps/vscode-extension/.vscodeignore
apps/vscode-extension/package.json
apps/vscode-extension/project.json
tools/@o3r/build-helpers/package.json
tools/@o3r/build-helpers/scripts/clear-package-json-dev-dependencies.mjs
yarn.lock

Fix the publishing issue because of the add of dependencies to the VsCode extension
- :rocket: Feature resolves #362 
- failing publish (v10.1.0): https://github.com/AmadeusITGroup/otter/actions/runs/8536550129/job/23386791485

fix(vscode-extension): publishing mechanism

---

tools/renovate/base.json
tools/renovate/design-factory.json
tools/renovate/otter-project.json
tools/renovate/sdk-spec-upgrade.json
tools/renovate/sdk.json

The ` extends: ["config:recommended"]` includes ` group:monorepos` which override our rules for Angular and Nx
We need to include it only once in the base preset
Also ` config:base` seems to be an old name for `config:recommended` and should no longer be needed

ci(renovate): fix config-recommended overriding o3r rules

---

docs/components/PLACEHOLDERS.md
packages/@o3r/components/schemas/placeholder-template.schema.json
packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.spec.ts
packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.state.ts

Currently, localization strings used in placeholders support variables. However there are some limitations for some use cases like usage of JSONPath in fact variables. This can be solved thanks to a `parameters` mapping for localization variables. 
``en-GB.json``
```json
{
"o3r-greet-key": "Welcome back, { firstName } { lastName }!"
}
```
``ruleset.json``
```json
{
"vars": {
"greetKey": {
"type": "localisation",
"value": "o3r-greet-key",
"parameters": {
"firstName": "firstNameVar",
"lastName": "lastNameVar"
}
},
"firstNameVar": {
"type": "fact",
"value": "user",
"path": "$.firstName"
},
"lastNameVar": {
"type": "fact",
"value": "user",
"path": "$.lastName"
}
},
"template": "<div><%= greetKey %></div>"
}
```

feat: parameters for localization vars in placeholders

---

.github/ISSUE_TEMPLATE/1-O3R-ISSUE-FORM.yaml

`components` option is missing from the Github issue creation template.

chore: components not present in gh issue template

---

docs/components/PLACEHOLDERS.md

In the placeholder documentation we should refer to `template.json` rather than `ruleset.json`

docs: template.json for placeholders

---

.renovaterc.json5
tools/renovate/otter-project.json
tools/renovate/sdk-spec-upgrade.json
tools/renovate/sdk.json

ci(renovate): add grouping for otter dependencies in presets

---

packages/@o3r/core/src/store/async/async-entity.adapter.ts
packages/@o3r/core/src/store/async/async.interfaces.ts
packages/@o3r/core/src/store/types.ts

feat: support number type for id in entity store

---

.renovaterc.json5
tools/renovate/base.json

- No need to override the default timezone on base preset
- The `schedule` rule should be opt-in to prevent people from thinking the renovate config doesn't work because it doesn't create pull-requests

fix(renovate): remove schedule rule from base preset

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.ts

The openapi version is here to make sure the generator will not run with an invalid version.
It should not be ignore in any cases as this is a safegard.

fix: allow override of openapi version

---

packages/@o3r/testing/schematics/ng-add/playwright/index.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/scenarios/__name@dasherize__.e2e-playwright-spec.ts
packages/@o3r/testing/schematics/playwright/scenario/templates/__name@dasherize__.e2e-playwright-spec.ts

The test assertions are no longer dependent on the project's name. However a basic assertion is still performed.
Also, adding `test-results` folder to `.gitignore`.
- :bug: Fixes #1632

fix: playwright tests on new otter app

---

packages/@ama-sdk/create/README.md
packages/@ama-sdk/create/src/index.ts

Currently running `npm create @ama-sdk typescript test --debug` triggers an exception on spawnSync ENOENT
This is because --debug enables --dry-run by default on angular schematics
We are not currently supporting dry-run mode for generators because we are running shell commands during generation so the files need to be present on disk
To use debug mode, we need to be able to override the `--dry-run` parameter

fix(sdk-create): cannot create an sdk with debug mode

---

packages/@o3r/core/schematics/component/container/index.ts
packages/@o3r/core/schematics/ng-add/utils/linter/index.ts
packages/@o3r/testing/schematics/index.it.spec.ts
packages/@o3r/testing/schematics/ng-add/fixture/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.ut.js.template

fix: jest test not running on new otter webapp

---

.github/markdown-external-links.config.json

Bundlephobia links are seen as broken (false positive). https://github.com/AmadeusITGroup/otter/issues/1510
https://github.com/AmadeusITGroup/otter/actions/runs/8683478379/job/23809543790
The proposal is to ignore them from the MD check.

fix: ignore bundlephobia from md link check

---

.yarnrc.yml
packages/@ama-sdk/create/src/index.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/code-generator/code-generator.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/openapitools.json.template
packages/@ama-sdk/schematics/testing/MOCK_swagger.json
yarn.lock

Support of URL and JSON based specification.

fix(ama-sdk): support of URL as spec-path input

---

apps/chrome-devtools/package.json
apps/chrome-devtools/src/app-devtools/theming-panel/color.helpers.ts
apps/chrome-devtools/src/app-devtools/theming-panel/color.pipe.ts
apps/chrome-devtools/src/app-devtools/theming-panel/common.ts
apps/chrome-devtools/src/app-devtools/theming-panel/theming-panel-pres.component.ts
apps/chrome-devtools/src/app-devtools/theming-panel/theming-panel-pres.template.html
apps/showcase/src/style/design-token.app.json
apps/showcase/src/style/design-token.figma.json
docs/styling/THEME.md
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/scss/theming/otter-theme/_material.scss
packages/@o3r/styling/scss/theming/otter-theme/_theme.scss
packages/@o3r/styling/src/devkit/styling-devkit.interface.ts
yarn.lock

- :rocket: Features 
- #1492 
- #1494

feat(chrome-ext): palette generator

---

packages/@o3r/testing/schematics/ng-add/fixture/index.ts

fix: remove jasmine from tsconfig types when adding jest

---

packages/@o3r/core/schematics/ng-add/utils/linter/index.ts
packages/@o3r/eslint-config-otter/.eslintrc.js
packages/@o3r/eslint-config-otter/package.json
packages/@o3r/eslint-config-otter/project.json
packages/@o3r/eslint-config-otter/schematics/index.it.spec.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/index.spec.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/__dot__eslintignore.template
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/project/__dot__eslintrc.js.template
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/project/tsconfig.eslint.json
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/tsconfig.eslint.json
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/workspace/__dot__eslintignore.template
packages/@o3r/eslint-config-otter/schematics/ng-add/linter/templates/workspace/__dot__eslintrc.js.template
packages/@o3r/eslint-config-otter/testing/jest.config.it.js
packages/@o3r/eslint-plugin/tsconfig.spec.json
packages/@o3r/schematics/src/utility/monorepo.ts
packages/@o3r/workspace/schematics/application/index.ts
packages/@o3r/workspace/schematics/library/rules/rules.ng.ts
packages/@o3r/workspace/schematics/library/templates/ng/tsconfig.eslint.json.template
packages/@o3r/workspace/schematics/ng-add/helpers/linter.ts
packages/@o3r/workspace/schematics/rule-factories/project-configs.ts
yarn.lock

fix: lint does not work on new Otter webapp

---

packages/@ama-sdk/create/src/index.ts
packages/@o3r/create/src/index.ts

Fix the following issue on Windows when path contains spaces (e.g. 'C:\Program Files')
```
npm create -yes @ama-sdk typescript @sdk/buggggg
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

fix(create): issue when nodejs path contains spaces

---

packages/@ama-sdk/schematics/schematics/typescript/core/helpers/path-extractor.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/helpers/path-extractor.ts

fix: sdk-generator - support basepath in operation adapter regexp

---

packages/@o3r/schematics/src/utility/monorepo.ts

The `isStandaloneRepository` is no longer used. Since it's an exported method, deprecating it for now and removing in next major.

chore: deprecate isStandaloneRepository

---

.github/workflows/it-tests.yml
package.json
packages/@ama-sdk/create/src/index.it.spec.ts
packages/@o3r/create/src/index.it.spec.ts
packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-otter-project.ts

Using a timestamp in the version that we use to publish on Verdaccio ensures that we always target the latest published version with no cache

test: use timestamp in the version used for verdaccio

---

packages/@o3r/localization/builders/helpers/localization.generator.ts
packages/@o3r/localization/schemas/localization.schema.json
packages/@o3r/localization/schematics/localization-to-component/templates/__name__.localization.json

Add localization.json files JSON Schema
- :rocket: Feature resolves #1702

feat(localization): add schema for localization.json files

---

packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/schematics/src/rule-factories/eslint-fix/index.ts
packages/@o3r/schematics/src/tasks/eslint/index.ts

Fix EslintFix schematics task to run on NPM correctly
- :bug: Fixes resolves #1658

fix(schematics): esintFix task to run on NPM correctly

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts

Rollback default spec file name created when generating the SDK to swagger-spec.yaml.

fix(schematics-sdk): rollback default spec file name to swagger-spec.yaml

---

packages/@o3r/core/src/store/async/async-entity.adapter.ts
packages/@o3r/core/src/store/types.ts

- the list of **ids** in the entities store was restricted to: **string[] | number[]**
- the pb is that when passing an array of strings, tsc is complaining about the fact that a _string_ is not assignable to a _number_, because it cannot fulfill both conditions (the opposite is the same). That's why I changed the type to (string | number)[] to be restrictive only to the element and not to the entire array.

fix: ids type in entity store

---

.github/ISSUE_TEMPLATE/1-O3R-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/2-AMA-SDK-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/3-AMA-TERASU-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/4-APPLICATION-ISSUE-FORM.yaml

When a new issue is created using the template, the `triage` tag should be added so that it helps us filtering in order to set a priority.

feat: github issues created from template have triage tag

---

packages/@o3r/core/schematics/service/index.ts

Change path resolver from path.resolve to path.join  as the tree.exists is unable to resolve the absolute path generated by path.resolve
- :bug: Fixes #1778

fix(o3r): replaced path.resolve with path.join for better path resolution

---

packages/@o3r/rules-engine/package.json

Add Missing schematics templates for Rules Engine package
- :bug: Fix resolves #1793

fix(rules-engine): missing schematics templates

---

packages/@o3r/configuration/schematics/ng-add/index.ts
packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/core/schematics/rule-factories/component/common.ts
packages/@o3r/core/schematics/shared/presets/all.preset.ts
packages/@o3r/core/schematics/shared/presets/cms.preset.ts
packages/@o3r/design/schematics/ng-add/index.ts
packages/@o3r/localization/schematics/ng-add/index.ts
packages/@o3r/rules-engine/schematics/ng-add/index.ts
packages/@o3r/schematics/src/rule-factories/ng-add/schematics-register.ts
packages/@o3r/styling/schematics/ng-add/index.ts
packages/@o3r/testing/schematics/ng-add/index.ts
packages/@o3r/workspace/schematics/ng-add/helpers/npm-workspace.ts

Today, during the `ng add`, schematic parameters are added on all projects present in the workspace. 
It should be added only for one given project.

fix: schematics params should be added only for one project

---

packages/@o3r/localization/src/tools/localization-translate.pipe.ts

Unsubscribes from active key change on destroy  
- :bug: Fixes #1827

fix: memory leak from subscription

---

packages/@ama-sdk/schematics/migration.json
packages/@ama-sdk/schematics/schematics/migrate/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/index.ts
packages/@ama-sdk/schematics/schematics/ng-update/typescript/v10.3/update-openapiversion.ts
packages/@o3r/schematics/src/utility/monorepo.ts

Ng update script to help the migration to @ama-sdk/schematics 10.3
As projects generated via the @ama-sdk/create command, the update is exposed as a schematics.
Unfortunately, it will not allow the update of several version in one command and needs the 10.3 version of ama-sdk/schematics to already be installed to be run.

feat: ng-update script for migration to openapitools 7.4

---

packages/@ama-sdk/core/cli/update-spec-from-npm.cts
packages/@ama-sdk/core/src/utils/generators.ts
packages/@ama-sdk/core/src/utils/index.ts
packages/@ama-sdk/create/README.md
packages/@ama-sdk/create/src/index.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts
packages/@ama-sdk/swagger-builder/src/core/formatters/json-formatter.ts
packages/@ama-sdk/swagger-builder/src/core/formatters/split-yaml-formatter.ts
packages/@ama-sdk/swagger-builder/src/core/formatters/yaml-formatter.ts
packages/@o3r/workspace/schematics/sdk/index.ts

fix: default specs filename on sdk generation

---

packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json.template

In generated SDK, ` .renovaterc.json` file should match the recommendation defined here: https://github.com/AmadeusITGroup/otter/blob/main/tools/renovate/README.md#otter-sdk

fix(sdk): generate the correct renovate config for sdk

---

docs/configuration/CONFIGURATION_SUPPORTED_EXTRACTOR.md
docs/configuration/OVERVIEW.md
packages/@o3r/configuration/README.md

Update documentation on configuration

feat: update configuration doc

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template

fix: missing linter dep in generated sdk

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template

- bump and align swc versions with the ones from main branch
- remove o3r-set-version from a standlone sdk generated as it is meant for workspaces

fix: bump swc versions and remove o3r-set-version in sdk generator 

---

packages/@ama-sdk/core/src/plugins/timeout/timeout.fetch.ts
packages/@ama-sdk/core/src/plugins/timeout/timeout.spec.ts

fix: timeout plugin should not break on null messages

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json.template
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/templates/__dot__renovaterc.json.template
tools/renovate/base.json

`stabilityDays` is now named `minimumReleaseAge`
I propose to remove it entirely from our config since it was set to the default value anyway

chore: remove stability-days from renovate config

---

packages/@o3r/test-helpers/src/prepare-test-env.ts
packages/@o3r/test-helpers/src/test-environments/create-test-environment-otter-project.ts
packages/@o3r/test-helpers/src/utilities/package-manager.ts

- No need to create yarn config when doing the create since we always use npm, this prevent some race condition issues 
- No need to copy the `.git` folder of the base app, this prevent some files being incorrectly versioned if committed before the setup of `.gitignore`

test: fix it-tests not running in local

---

packages/@o3r/apis-manager/tsconfig.doc.json
packages/@o3r/application/tsconfig.doc.json
packages/@o3r/artifactory-tools/tsconfig.doc.json
packages/@o3r/azure-tools/tsconfig.doc.json
packages/@o3r/components/tsconfig.doc.json
packages/@o3r/configuration/tsconfig.doc.json
packages/@o3r/core/tsconfig.doc.json
packages/@o3r/design/tsconfig.doc.json
packages/@o3r/dev-tools/tsconfig.doc.json
packages/@o3r/dynamic-content/tsconfig.doc.json
packages/@o3r/eslint-plugin/tsconfig.doc.json
packages/@o3r/extractors/tsconfig.doc.json
packages/@o3r/forms/tsconfig.doc.json
packages/@o3r/localization/tsconfig.doc.json
packages/@o3r/logger/tsconfig.doc.json
packages/@o3r/mobile/tsconfig.doc.json
packages/@o3r/routing/tsconfig.doc.json
packages/@o3r/rules-engine/tsconfig.doc.json
packages/@o3r/schematics/tsconfig.doc.json
packages/@o3r/storybook/tsconfig.doc.json
packages/@o3r/stylelint-plugin/tsconfig.doc.json
packages/@o3r/styling/tsconfig.doc.json
packages/@o3r/testing/tsconfig.doc.json
packages/@o3r/third-party/tsconfig.doc.json

The `tsconfig.doc` paths were extending from an unexisting file.

fix: paths for tsconfig doc files

---

packages/@o3r/schematics/src/rule-factories/ng-add/ng-add.helpers.ts
packages/@o3r/schematics/src/utility/dependencies.ts

Follow up on https://github.com/AmadeusITGroup/otter/pull/1903
In v11 `ngAddPeerDependencyPackages` is removed as unused.

fix: remove unused ngAddPeerDependencyPackages

---

tools/renovate/tasks/sdk-regenerate.json

Fix following error:
```
Command failed: yarn run schematics @ama-sdk/schematics:migrate -- --from=10.4.0-rc.1 --to=10.4.0-rc.9
[1m[31mError: Schematic input does not validate against the Schema: {}[39m[22m
[1m[31mErrors:[39m[22m
[1m[31m[39m[22m
[1m[31m  Data path "" must have required property 'from'.[39m[22m
```
The double dashes `--` should only be used for npm

fix(renovate): error while migrating ama-sdk version for an sdk

---

migration-guides/11.0.md
packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-beacon-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/core/src/utils/generic-api.ts
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@ama-sdk/showcase-sdk/src/api/pet/pet-api.ts
packages/@ama-sdk/showcase-sdk/src/api/store/store-api.ts
packages/@ama-sdk/showcase-sdk/src/api/user/user-api.ts

Remove the deprecated `prepareOptions` method.

fix: remove deprecated prepareOptions

---

package.json

Fixing some publish warnings.
```shell
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish "repository" was changed from a string to an object
npm warn publish "repository.url" was normalized to "git+https://github.com/AmadeusITGroup/otter.git"
```
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository

chore: update package.json repository

---

.github/workflows/publish.yml

Today, if one of the tasks in `publish:extension` fails, the upload of chrome-extension is skipped

ci: upload chrome extension artifact even if vscode fails

---

packages/@ama-sdk/core/src/fwk/api.helpers.ts

In the case of simple response for a valid status code (for example number or string), the reviver is undefined.
We should not log this scenario

fix: do not log error for undefined reviver for string response

---

migration-guides/11.0.md
packages/@ama-sdk/create/src/index.it.spec.ts
packages/@ama-sdk/create/testing/mocks/MOCK_DATE_UTILS_swagger.yaml
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/project.json
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md
packages/@ama-sdk/showcase-sdk/readme.md

Use `x-local-timezone` as an opt-in mechanism to use utils.Date and utils.DateTime .
Set sdk `isStringified` option for dates as true by default
- :rocket: Feature #1808

feat(sdk-generator): turn x-local-timezone mandatory for utils.Date

---

migration-guides/11.0.md
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/apis.mustache
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/enums.mustache
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/fixture.jest.mustache
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/interfaces.mustache

Add the support of multi Api Tag via the duplication of the Api Class.
- :bug: Fixes resolves #855 
- 🍒 Cherry-pick of #1739

fix(schematic-sdk): support the multi tag in SDK's APIs

---

packages/@o3r/workspace/schematics/ng-add/helpers/npm-workspace.ts

The angular schematic generates a `package.json` with version `0.0.0`. We should align the version with the rest of the workspaces (`0.0.0-placeholder`).

fix(create): version for root package.json should be 0.0.0-placeholder

---

packages/@o3r/styling/builders/style-extractor/index.ts
packages/@o3r/styling/scss/theming/otter-theme/_functions.scss
packages/@o3r/styling/scss/theming/otter-theme/_material.scss
packages/@o3r/styling/src/devkit/styling-devtools.message.service.ts

Do not remove css variable name from metadata extracted as it is used in the devtools
Do not fail on third party css scripts
Do not create variable for css var details

fix: missing css variables in chrome dev-tool

---

packages/@o3r/localization/src/devkit/localization-devtools.service.ts

Devtool state reload fails because the update localization message is sent before the reload of the language.

fix: wait for language to be loaded before update

---

tools/renovate/tasks/sdk-regenerate.json

- renovate replaces the args in the template which will be sent to handlebars
- prepare the string equals string in the check of the node runner

fix: migrate ama-sdk in renovate template

---

packages/@o3r/workspace/package.json
packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/ng-add/helpers/npm-workspace.ts
packages/@o3r/workspace/schematics/ng-add/project-setup.ts
packages/@o3r/workspace/schematics/ng-add/schema.json
packages/@o3r/workspace/schematics/ng-add/schema.ts
packages/@o3r/workspace/src/cli/set-version.cts

The goal is to add lerna at the root when creating an Otter project so that we can easily run the commands for all projects locally and on the CI with both npm and yarn.

feat: add lerna at the root of a new otter project

---

packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts

Before we were not even updating the development one because `workspaceProject.architect.build.configurations.options` does not exist. It should have been `workspaceProject.architect.build.configurations.development` instead. 
I propose we override the main `outputPath` and not just for production.
before
```json
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"outputPath": "dist/webapp",
},
"configurations": {
"production": {
....
"outputPath": "apps/webapp/dist"
},
"development": {
...
}
},
"defaultConfiguration": "production"
},
```
after
```json
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"outputPath": "apps/webapp/dist",
},
"configurations": {
"production": {
....
},
"development": {
... …
```

fix: correct dist path for dev builds on otter webapps

---

.renovaterc.json5

Setup Renovate to update open-api generator version
Example of run https://github.com/fpaul-1A/otter/pull/94/files

chore: renovate setup for openapi generator

---

.github/workflows/first-pr.yml

Adding missing permissions for first pr comment workflow
[Failed workflow](https://github.com/AmadeusITGroup/otter/actions/runs/10388255377/job/28764058469)
[Needed permissions](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment)

fix: missing permissions for first pr comment workflow

---

.github/workflows/pr-labels.yml

Avoid label setting on cascading pull request.

feat(cascading): avoid label setting on cascading pull request

---

packages/@o3r/configuration/src/services/configuration/configuration.base.service.ts

getConfig returns an observable of any.
To solve @typescript-eslint/no-unsafe-assignment eslint rule, getConfig can be made generic.

fix: added generic to getConfig

---

packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/testing/mocks/spec-chunk2.yaml
packages/@ama-sdk/schematics/testing/mocks/spec-chunk3/spec-chunk3.yaml
packages/@ama-sdk/schematics/testing/mocks/spec-chunk4/spec-chunk4.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/spec-chunk1.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/spec-with-updated-paths.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/split-spec.yaml

When we copy the spec file before generating the SDK we are breaking the local relative paths referenced in the file.
The proposed change is to copy all the referenced files inside the SDK in a folder `./spec-local-references/` to have them versioned.
We also update the local references in the spec to look for these files.
- :bug: Fixes #2014 

fix: copy specs local file refs

---

.github/workflows/pr-labels.yml

Add all the necessary permissions to add a label on a PR
[doc](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue)
https://github.com/AmadeusITGroup/otter/actions/runs/10487211477/job/29047084682?pr=2080
- :rocket: Feature #711

fix: missing permissions for pr labels workflow

---

packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/testing/mocks/spec-chunk2.yaml
packages/@ama-sdk/schematics/testing/mocks/spec-chunk3/spec-chunk3.yaml
packages/@ama-sdk/schematics/testing/mocks/spec-chunk4/spec-chunk4.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/spec-chunk1.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/spec-with-updated-paths.yaml
packages/@ama-sdk/schematics/testing/mocks/split-spec/split-spec.yaml

Cherry Pick fix of https://github.com/AmadeusITGroup/otter/pull/2046
- :bug: Fixes #2014

fix(ama-sdk/schematics): refs resolution failure

---

docs/api-sdk/SDK_MODELS_HIERARCHY.md
packages/@ama-sdk/core/src/fwk/Reviver.ts
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/reviver.mustache

feat(sdk): add the capability to clear dictionary field
- :bug: Fixes #1802

feat(sdk): add the capability to clear dictionary field

---

packages/@o3r/eslint-config-otter/rules/typescript/eslint-typescript.cjs

fix(eslint): turn no-require rule to warn to keep compatibility
- :octocat: Pull Request: #2076

fix(eslint): turn no-require rule to warn to keep compatibility

---

packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/sdk/index.ts
packages/@o3r/workspace/schematics/sdk/schema.json

compute the scope first while generating a new sdk
- :bug: Fixes #2124

fix(#2124): compute the scope first while generating a new sdk

---

.github/workflows/code-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml

Since Yarn 4, hardened mode is enable by default on GitHub public pull requests.
This can considerably slow down the yarn install
See https://yarnpkg.com/features/security#hardened-mode
As recommended, we just need to run it once

ci: enable yarn hardened mode only once for the workflow

---

packages/@o3r/rules-engine/README.md

docs: remove broken link for examples of custom operators

---

eslint.shared.config.mjs
packages/@o3r/core/schematics/ng-add/utils/linter/index.ts
packages/@o3r/eslint-config/index.spec.ts
packages/@o3r/eslint-config/schematics/index.it.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/eslint/index.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/eslint/index.ts
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/project/eslint.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/project/eslint.local.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.local.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.shared.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/index.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/index.ts
packages/@o3r/eslint-config/schematics/ng-add/schema.json
packages/@o3r/eslint-config/schematics/ng-add/schema.ts
packages/@o3r/eslint-config/schematics/ng-add/tsconfig/index.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/tsconfig/index.ts
packages/@o3r/eslint-config/schematics/ng-add/tsconfig/templates/tsconfig.eslint.json.template
packages/@o3r/eslint-config/schematics/ng-add/vscode/index.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/vscode/index.ts

`ng-add` of the `@o3r/eslint-config` package
> [!NOTE]
> This PR is not targetting `main`.
> I will create a PR for `main` once everything below will be merged on
`feat/migrate-eslint-9-flat-config`
Will be done in others PRs:

feat(eslint): ng-add eslint-config

---

CODE_OF_CONDUCT.md

There is an official email address that can be used to contact Amadeus OpenSource organization, may it be for abuse reports or other subject.
This PR proposes to update Otter Code of Conduct accordingly.

feat: update cod enforcement contact

---

eslint.config.mjs
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.config.__extension__.template

Set relative path instead of absolute path in the merge config

fix(eslint): set relative path instead of absolute path in the merge config

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/spec/api-mock.mustache

Rollback `api-mock.ts` to use deprecate fetch client from core.
This change will be part of #2117.
- 🔗  Related to: #2117

fix(sdk-core): rollback api-mock.ts to use deprecate fetch client from core

---

.github/workflows/main.yml

Only node and checkout are needed for computing the new version. No need to install.

ci: no install needed for new version computation

---

packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.ts

a log is triggered for all the action blocks which does not scale if there are many rulesets

fix: reduce number of log for rules engine action

---

packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts
packages/@ama-sdk/schematics/testing/mocks/split-spec/spec-chunk1.yaml

When creating an SDK with a local spec file with references to other local files, the following were not supported:
- Relative path not starting with a `.`
- Relative path with no quotes in CRLF (`\r` remains in the extracted path)
- Additional spaces before or after the unquoted path for some reasons

fix(sdk): relative local ref in specs are not always handled correctly

---

packages/@o3r/extractors/src/core/comparator/metadata-comparison.helper.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts

**Context:** Migration scripts with npm implementation (also used for yarn1)
With the current implementation, when looking for a previous version, we will get the latest **published** version that match the range.
What we want is the most recent version according to semver.

fix: migration scripts not checking latest semver version with npm

---

packages/@o3r/rules-engine/builders/rules-engine-extractor/helpers/rules-engine.extractor.ts

Operators have exposed and supported type.
The first type is what to extract for the CMS and the second is to be used for type check in the code.
Left operand runtime type was overriding right operand metadata (idx = 2, hence > 1).
Now, only extract "ExposedTypes"

fix: use only exposed type to fill operators metadata

---

apps/showcase/.gitignore
apps/showcase/package.json
apps/showcase/project.json
apps/showcase/scripts/prepare-training-exercises/index.cjs
apps/showcase/src/app/app-routing.module.ts
apps/showcase/src/app/app.component.html
apps/showcase/src/app/app.component.ts
apps/showcase/src/app/app.module.ts
apps/showcase/src/app/sdk-training/index.ts
apps/showcase/src/app/sdk-training/sdk-training.component.ts
apps/showcase/src/app/sdk-training/sdk-training.spec.ts
apps/showcase/src/app/sdk-training/sdk-training.style.scss
apps/showcase/src/app/sdk-training/sdk-training.template.html
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.scss
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/index.ts
apps/showcase/src/components/training/training.component.html
apps/showcase/src/components/training/training.component.scss
apps/showcase/src/components/training/training.component.spec.ts
apps/showcase/src/components/training/training.component.ts
apps/showcase/src/services/webcontainer/webcontainer-runner.ts
apps/showcase/src/services/webcontainer/webcontainer.helpers.ts
apps/showcase/src/services/webcontainer/webcontainer.service.ts
apps/showcase/tsconfig.app.json
nx.json
packages/@o3r/training-tools/cli/extract-folder-structure/extract-folder-structure.cts

Preparation for the training content

feat: otter training - prepare training content

---

docs/linter/eslint-config.md
packages/@o3r/eslint-config/src/rules/template/otter.cjs
packages/@o3r/eslint-config/src/rules/typescript.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint-angular.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint-typescript.cjs
packages/@o3r/eslint-config/src/rules/typescript/eslint.cjs
packages/@o3r/eslint-config/src/rules/typescript/jest.cjs
packages/@o3r/eslint-config/src/rules/typescript/jsdoc.cjs
packages/@o3r/eslint-config/src/rules/typescript/stylistic.cjs
packages/@o3r/eslint-config/src/rules/typescript/unicorn.cjs

As discussed move all warnings into errors.
Open to discussion if some rules should become `off` instead of `errors`

feat(eslint): change all warnings into errors

---

packages/@o3r/components/builders/metadata-check/index.ts
packages/@o3r/extractors/src/core/comparator/metadata-comparator.interface.ts
packages/@o3r/extractors/src/core/comparator/metadata-comparison.helper.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/yarn2-file-extractor.helper.ts
packages/@o3r/localization/builders/metadata-check/index.ts
packages/@o3r/styling/builders/metadata-check/index.ts

There can be a discrepancy between the path to cms metadata between 2 version of an application.
However, we only specify one path when running the metadata-checks.
We can use the path to the metadata specified in `package.json` under `cmsMetadata` to find the files even if the option passed to the script doesn't match.

fix: metadata checks should look for cms-metadata in package.json for previous version

---

packages/@o3r/rules-engine/package.json
yarn.lock

fix: upgrade jsonpath-plus to non vulnerable version

---

tools/@o3r/build-helpers/project.json
yarn.lock

Fix lock file maintenance https://github.com/AmadeusITGroup/otter/pull/2279

chore: change nx config of build-builders to prevent circular dependency on 19.5.8

---

packages/@o3r/components/builders/metadata-check/helpers/config-metadata-comparison.helper.ts
packages/@o3r/extractors/src/core/comparator/metadata-comparator.interface.ts
packages/@o3r/extractors/src/core/comparator/metadata-comparison.helper.ts
packages/@o3r/localization/builders/metadata-check/helpers/localization-metadata-comparison.helper.ts
packages/@o3r/styling/builders/metadata-check/helpers/styling-metadata-comparison.helper.ts

fix: metadata checks fail when migration file contains an element without a before

---

packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md

Modify the header of the SDK readme file to clarify the version of the SDK spec and the version of OpenAPI used to generate the SDK.

fix: header of sdk readme file in schematics for clarity on versions

---

docs/routing/APP_SERVER_ROUTING.md

Previous documentation was incomplete: 
- the use case where the environment file provides the base href was missing
- the developer / production context definition was missing

chore: update routing documentation to describe forRoot setup

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/spec/api-mock.mustache
packages/@ama-sdk/showcase-sdk/src/spec/api-mock.ts

deprecate the default client api based mocks in SDK generated mocks
- :rocket: Feature #2117

deprecate(sdk-generator): default client api based mocks

---

package.json

The version placeholder is not updated in the `manifest.json` in the Chrome Extension package. 
The goal is to run the `set-version` script also over `manifest.json` files under `dist`, not only on `package.json`.

fix(chrome-devtools): set version in manifest.json

---

packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts

Extracted from #2344
This fix is fixing the apply of npm registry to npmrc files when multiple npmrc file are present (in case of SDK within a mono-repo)

fix(ama-sdk-create): registry patch in multiple npmrc

---

package.json

chore: support NX_PARALLEL as default parallel CPUs number
see Nx Variable list: https://nx.dev/reference/environment-variables

chore: support NX_PARALLEL as default parallel CPUs number

---

packages/@o3r/design/src/core/design-token/renderers/design-token.renderer.interface.ts

Fix typo in Design interface name (not used and introduced in this version)

fix(design): typo in interface name

---

packages/@o3r/localization/builders/localization/index.spec.ts
packages/@o3r/localization/schematics/localization-base/index.ts

Path generated in the angular.json in case of monorepo.

fix(localization): path generated in the angular.json in case of monorepo

---

packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.spec.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.ts

Remove Node requirement in core files of the Design Tool.
The purpose is to be able to run the design token generation in a non-Node environment

fix(design): remove Node requirement in core files

---

.nxignore
CONTRIBUTING.md
apps/chrome-devtools/project.json
apps/showcase/project.json
nx.json
packages/@ama-sdk/schematics/project.json
packages/@ama-sdk/showcase-sdk/project.json
packages/@o3r/analytics/project.json
packages/@o3r/components/project.json
packages/@o3r/configuration/project.json
packages/@o3r/dynamic-content/project.json
packages/@o3r/localization/project.json
packages/@o3r/logger/project.json
packages/@o3r/routing/project.json
packages/@o3r/rules-engine/project.json
packages/@o3r/storybook/project.json
packages/@o3r/test-helpers/project.json

Rework on Nx Cache for clarification and simplification
Add documentation regarding Nx PAT new process

chore: rework on Nx Cache and Doc

---

packages/@o3r/pipeline/schematics/ng-add/index.spec.ts
packages/@o3r/pipeline/schematics/ng-add/index.ts
tools/@o3r/build-helpers/scripts/write-git-hash.mjs

The version for Otter GitHub actions is incorrect.
Also, if a registry is already present in `.npmrc` but a value is passed to the ng add schematics, it should be updated.

fix(pipeline): action version and update npmRegistry

---

packages/@o3r/design/builders/generate-style/helpers/style-renderer-options.ts
packages/@o3r/design/builders/generate-style/schema.json
packages/@o3r/design/builders/generate-style/schema.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.spec.ts
packages/@o3r/design/src/core/design-token/renderers/design-token-style.renderer.ts
packages/@o3r/design/testing/mocks/design-token-theme.json

Add a way to sort variables based on provided RegExps

feat(design): add sorting way based on regexps

---

packages/@o3r/pipeline/schematics/ng-add/templates/github/__dot__github/workflows/main.yml

In the CI generated by `@o3r/pipeline`, the step ID was incorrect resulting in a wrong GitHub release name.

fix(pipeline): release name is correctly computed based on latest tag

---

apps/showcase/src/components/training/code-editor-control/code-editor-control.component.html
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.scss
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.ts
apps/showcase/src/components/training/code-editor-terminal/code-editor-terminal.component.ts

Add an indicator on the terminal output to know that some work is in progress
Working example: https://fpaul-1a.github.io/otter/#/sdk-training#4

feat(training): add load indicator on output

---

packages/@o3r/components/builders/metadata-check/index.it.spec.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/custom-npm-semver-resolver.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts
packages/@o3r/extractors/src/core/comparator/package-managers-extractors/yarn2-file-extractor.helper.ts
packages/@o3r/localization/builders/metadata-check/index.it.spec.ts
packages/@o3r/styling/builders/metadata-check/index.it.spec.ts

- Use `npm view <package> versions` instead of `npm view <package@range> version` to include the prerelease tags
- Extends the `NpmSemverResolver` used for yarn to include prerelease tags
* :bug: Fix resolves #2396

fix(2396): metadata checks should run on prerelease tags

---

apps/showcase/.eslintrc.js
apps/showcase/src/assets/trainings/sdk/steps/date-sdk-generation/exercise/open-api.yaml
apps/showcase/src/assets/trainings/sdk/steps/date-sdk-generation/instructions.html
apps/showcase/src/assets/trainings/sdk/steps/date/exercise/app.component.html
apps/showcase/src/assets/trainings/sdk/steps/date/exercise/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/date/instructions.html
apps/showcase/src/assets/trainings/sdk/steps/date/solution/app.component.ts

Otter SDK Training - SDK with Dates - Generation step and How to use step
NOTE: the app.component files are those that are added to the webcontainer (these are converted to a JSON format and then added to the webcontainer for the exercises)
Generation step:
Show solution:
How to use:
Show solution:

feat: otter sdk training - sdk with date generation and usage

---

.github/workflows/code-check.yml
.github/workflows/main.yml
.github/workflows/publish.yml
CONTRIBUTING.md
nx.json
package.json
yarn.lock

Setup Nx Cloud Id for PAT support
See https://nx.dev/ci/recipes/security/personal-access-tokens for details

chore: setup Nx Cloud Id for PAT support

---

.github/CODEOWNERS

Removing my ownership of the build.gradle.kts file to avoid blocking the merges for simple version change
Currently without this change I'm being requested to review PRs for just renovate version bumps

chore: exclude build.gradle.kts from OxyFlax codeowners setup for intellij-extension folder

---

packages/@o3r/extractors/src/core/comparator/metadata-files.helper.spec.ts
packages/@o3r/extractors/src/core/comparator/metadata-files.helper.ts

When running the metadata checks we use the version in the JSON migration file to compute the range that will be used to get the previous version.
E.g. version `11.1.0` will generate the range `<11.1.0` with `{includePrerelease: true}`
Unfortunately, this range include the prereleases of the current version `11.1.0-alpha.0`
We want to include the prerelease of the previous versions but not of the current
The solution is to add `-a` in the range to exclude them -> `<11.1.0-a`

fix: metadata checks run on the wrong prerelease

---

apps/showcase/src/app/app.component.html
apps/showcase/src/app/app.component.scss
apps/showcase/src/components/training/training.component.html

https://fpaul-1a.github.io/otter/#/sdk-training#0
https://fpaul-1a.github.io/otter/#/sdk-training#4

feat(training): update css of the showcase to reduce the unused space on screen

---

docs/localization/LOCALIZATION.md

fix: broken links in localization documentation
* :bug: Fix resolves #2392

fix: broken links in localization documentation

---

.github/workflows/it-tests.yml
codecov.yml

disable temporary IT test coverage publishing to CodeCov.
* :bug: related to #2455

fix: remove IT test coverage publishing to CodeCov

---

packages/@o3r/components/builders/metadata-check/helpers/config-metadata-comparison.helper.ts
packages/@o3r/components/builders/metadata-check/index.it.spec.ts
packages/@o3r/components/builders/metadata-check/schema.json
packages/@o3r/extractors/src/core/comparator/metadata-comparator.interface.ts
packages/@o3r/extractors/src/core/comparator/metadata-comparison.helper.ts
packages/@o3r/localization/builders/metadata-check/helpers/localization-metadata-comparison.helper.ts
packages/@o3r/localization/builders/metadata-check/index.it.spec.ts
packages/@o3r/localization/builders/metadata-check/schema.json
packages/@o3r/styling/builders/metadata-check/helpers/styling-metadata-comparison.helper.ts
packages/@o3r/styling/builders/metadata-check/index.it.spec.ts
packages/@o3r/styling/builders/metadata-check/schema.json

Add an optional check on migration files to detect unused migration items.
* :rocket: Feature resolves #2388

feat(2388): check relevance of migration files items on metadata checks

---

README.md
docs/core/START_NEW_APPLICATION.md
packages/@o3r/core/README.md

The documentation on creating a new Otter-based project is wrong.
It doesn't specify that the create command actually generates a monorepo structure. 

docs: create new otter project

---

apps/showcase/src/assets/trainings/sdk/steps/sdk-generation/instructions.md
apps/showcase/src/assets/trainings/sdk/steps/sdk-specs/instructions.md

Otter SDK Training - Generate your first SDK - Specifications step and command step

feat: otter sdk training - generate your first sdk specs and command

---

packages/@o3r/core/README.md
packages/@o3r/schematics/schematics/ng-add/index.ts
packages/@o3r/storybook/README.md
tools/github-actions/new-version/packaged-action/LICENSE.txt

@o3r/schematics is not fully installed and not accessible during ng-add
schematics run. A relative import allows to access the library during
the installation process.
The use of composite in tsconfig.builders.json (current setup) allow to make reference
to the dist/src folder without risking the override of the src build.
- :bug: Fixes #2334

fix: do not dynamically import @o3r/rules-engine during rules-engine install

---

.github/markdown-external-links.config.json
.github/markdown-links.config.json
CONTRIBUTING.md
apps/showcase/scripts/update-screenshots/readme.md

doc(showcase): add a readme to explain how to update the screenshots for visual testing

---

nx.json
packages/@o3r/components/package.json
packages/@o3r/components/project.json
packages/@o3r/design/package.json
packages/@o3r/design/project.json
packages/@o3r/rules-engine/package.json
packages/@o3r/rules-engine/project.json
packages/@o3r/telemetry/project.json
packages/@o3r/testing/project.json
tools/github-actions/audit/packaged-action/index.js
tools/github-actions/audit/tsconfig.build.composite.json
tools/github-actions/audit/tsconfig.json
tools/github-actions/cascading/packaged-action/index.js
tools/github-actions/cascading/tsconfig.build.composite.json
tools/github-actions/cascading/tsconfig.json
tools/github-actions/get-npm-tag/packaged-action/index.js
tools/github-actions/new-version/packaged-action/LICENSE.txt
tools/github-actions/new-version/packaged-action/index.js
tools/github-actions/release/packaged-action/index.cjs
tools/github-actions/release/tsconfig.build.composite.json
tools/github-actions/release/tsconfig.json

chore: clean Nx config

---

packages/@o3r/configuration/src/core/configuration.ts
packages/@o3r/configuration/src/tools/configuration.observer.ts
packages/@o3r/localization/src/tools/localization.service.ts

If translation or config is no longer subscribed to the value should be cleaned up
* :bug: Fix #2509

fix: clean unreferenced cached values of translations and configs

---

apps/showcase/src/components/training/code-editor-control/code-editor-control.component.html
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.scss
apps/showcase/src/components/training/code-editor-control/code-editor-control.component.ts
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.scss
apps/showcase/src/services/webcontainer/webcontainer-runner.ts

https://fpaul-1a.github.io/otter/#/sdk-training#1

feat(training): loading progress indicator

---

apps/showcase/e2e-playwright/sanity/lighthouse-sanity.e2e.ts

In the current setup, the Lighthouse performance metrics are not relevant, it depends too much on the running environment.

test(e2e): disable lighthouse performance checks due to instability

---

apps/showcase/src/app/placeholder/placeholder.component.ts
apps/showcase/src/app/rules-engine/rules-engine.component.ts
docs/rules-engine/how-to-use/custom-action.md
packages/@o3r/rules-engine/migration.json
packages/@o3r/rules-engine/schematics/ng-update/index.ts
packages/@o3r/rules-engine/schematics/ng-update/v11.6/use-register-action-handlers.spec.ts
packages/@o3r/rules-engine/schematics/ng-update/v11.6/use-register-action-handlers.ts
packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.ts

It's not a good practice to expose a `Set`.
I added a method `registerActionHandlers` to replace the usage of `actionHandlers.add(...)`.
It will be future proof if we want to do something else when an action handler is registered.

deprecate(rules-engine): actionHandlers will become protected in v13

---

apps/showcase/src/services/webcontainer/webcontainer-runner.ts

`withLatestFrom` doesn't emit if the promise is already resolved, need to use `combineLatestWith` instead

fix(training): terminal no longer working

---

apps/showcase/src/app/app.component.scss
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.scss
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/utilities/scroll-back-top/scroll-back-top-pres.style.scss
apps/showcase/src/styles.scss

https://fpaul-1a.github.io/otter/#/sdk-training#1
Before:

fix(training): monaco editor tooltips not fully visible

---

codecov.yml

chore: reduce codeCov warning

---

apps/chrome-devtools/project.json
apps/showcase/project.json
nx.json
package.json
packages/@o3r/components/project.json
packages/@o3r/rules-engine/project.json

Try to improve eslint run via nx and lint-staged

fix(eslint): use cache for lint-staged + change command to not use no-error-on-unmatched-pattern

---

apps/showcase/src/assets/trainings/sdk/program.json
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/apps/tutorial-app/src/app/app.component.html
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/apps/tutorial-app/src/app/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/apps/tutorial-app/src/app/app.config.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/base/flight/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/flight/flight.reviver.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/flight/flight.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/flight/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/instructions.md
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/.openapi-generator-ignore
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/base/flight/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/core/flight/flight.reviver.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/core/flight/flight.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/core/flight/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/core/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/solution/src/models/index.ts
packages/@ama-sdk/core/src/plugins/mock-intercept/README.md
packages/@o3r-training/training-sdk/open-api.yaml
packages/@o3r-training/training-sdk/src/api/dummy/dummy-api.jest.fixture.ts
packages/@o3r-training/training-sdk/src/api/dummy/dummy-api.ts

https://fpaul-1a.github.io/otter/#/sdk-training#8
Otter SDK Training - Model extension
NOTE: the exercise and solution files are combined with the existing training-sdk 

feat: otter sdk training - model extension

---

packages/@o3r-training/showcase-sdk/package.json
packages/@o3r-training/showcase-sdk/project.json

Remove the '@o3r-training/showcase-sdk' package from the published packages. It is not needed to be installed during the training and has no value outside the training.

fix: do not publish training package; not needed

---

apps/showcase/src/components/showcase/component-replacement/component-replacement-pres.config.ts
packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
packages/@o3r/configuration/migration.json
packages/@o3r/configuration/schematics/configuration-to-component/templates/__name__.config.ts.template
packages/@o3r/configuration/schematics/ng-update/v11-6/index.spec.ts
packages/@o3r/configuration/schematics/ng-update/v11-6/index.ts
packages/@o3r/localization/migration.json
packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
packages/@o3r/localization/schematics/add-localization-key/index.ts
packages/@o3r/localization/schematics/localization-to-component/templates/__name__.translation.ts.template
packages/@o3r/localization/schematics/ng-update/v11-6/index.spec.ts
packages/@o3r/localization/schematics/ng-update/v11-6/index.ts

feat(config): generate default config with readonly and as const

---

.vscode/extensions.json
.vscode/settings.json

feat: update recommended extensions
feat: add additional configs
List of additional extensions:
- [Gruntfuggly.todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)
- [jasonnutter.vscode-codeowners](https://marketplace.visualstudio.com/items?itemName=jasonnutter.vscode-codeowners)
- [bierner.emojisense](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)
- [bierner.markdown-emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji)
* :octocat: Pull Request #2440

feat: update recommended extensions

---

.github/.cascadingrc.json
apps/github-cascading-app/schemas/config.schema.json
apps/github-cascading-app/src/cascading/cascading.spec.ts
apps/github-cascading-app/src/cascading/cascading.ts
apps/github-cascading-app/src/cascading/interfaces.ts

Option to bypass non-latest minor branch on cascading bot

feat(cascading): option to bypass non-latest minor branch

---

packages/@o3r/eslint-config-otter/migration.json
packages/@o3r/eslint-config-otter/schematics/ng-update/index.ts
packages/@o3r/eslint-config-otter/schematics/ng-update/v11.6/update-configs/update-configs.spec.ts
packages/@o3r/eslint-config-otter/schematics/ng-update/v11.6/update-configs/update-configs.ts
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/yaml/yarnrc-package-extensions-harmonize/yarnrc-package-extensions-harmonize.spec.ts
packages/@o3r/eslint-plugin/src/rules/yaml/yarnrc-package-extensions-harmonize/yarnrc-package-extensions-harmonize.ts

feat(eslint-plugin): renamed exported recommended
fix(eslint-plugin): turn yaml parser really optional
deprecate(eslint-plugin): recommended exports based on types
- :rocket: Feature resolves #1487
- 🐛 Fix resolves #2482

feat(eslint-plugin): renamed exported recommended

---

apps/showcase/src/assets/trainings/sdk/program.json
apps/showcase/src/assets/trainings/sdk/steps/date-sdk-generation/exercise/open-api.yaml
apps/showcase/src/assets/trainings/sdk/steps/date/exercise/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/date/solution/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/base/flight/index.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/flight/flight.reviver.ts
apps/showcase/src/assets/trainings/sdk/steps/model-extension/exercise/libs/sdk/src/models/core/flight/flight.ts
apps/showcase/src/assets/trainings/sdk/steps/plugins/exercise/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/typescript-sdk/exercise/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/typescript-sdk/exercise/app.config.ts
apps/showcase/src/assets/trainings/sdk/steps/typescript-sdk/solution/app.component.ts
apps/showcase/src/assets/trainings/sdk/steps/typescript-sdk/solution/app.config.ts

Small fixes before big PR into main
Update "TODO" comments in the exercise files to have regularity between the steps

feat: otter training sdk - small fixes

---

packages/@ama-sdk/schematics/collection.json
packages/@ama-sdk/schematics/schematics/code-generator/swagger-java-generator/swagger-java.generator.ts
packages/@ama-sdk/schematics/schematics/java/client-core/index.ts
packages/@ama-sdk/schematics/schematics/java/client-core/swagger-codegen-java-client/README.md

Deprecate the java-sdk generator which is not compatible with OpenApi 3.

chore: deprecate outdate java-sdk generator

---

.vscode/settings.json

Add back search exclusion and TS options

fix: add search exclusion and TS options

---

.github/check-release-issue-template.md
.github/workflows/audit.yml
.github/workflows/check-all-releases.yml
.github/workflows/check-release.yml
.github/workflows/it-tests.yml

Weekly job that tests that all currently supported versions are still passing the audits and it-tests
Check on IT-tests are currently disabled by default for the weekly job because of instability and discrepancy between yarn3 and yarn4 
Example of run: https://github.com/fpaul-1A/otter/actions/runs/12199946300

ci: check releases

---

packages/@o3r/localization/schemas/localization.metadata.schema.json

There is no point validating the ref if we don't validate the key.

fix: remove pattern for ref property in localization.metadata.schema.json

---

apps/showcase/package.json
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/training.component.ts
apps/showcase/src/helpers/monaco-tree.helper.ts
apps/showcase/src/services/webcontainer/webcontainer-runner.ts
apps/showcase/src/services/webcontainer/webcontainer.helpers.ts
apps/showcase/src/services/webcontainer/webcontainer.service.ts
package.json
yarn.lock

Enable `Go to Definition` feature (Ctrl+click), auto complete and avoid errors on imports.
https://fpaul-1a.github.io/otter/#/sdk-training#1

feat(training): file navigation inside code editor

---

.github/CODEOWNERS
.gitignore

chore: add codeowners for CMS specifications
chore: add /bin folder to gitignore

chore: add codeowners for CMS specifications

---

apps/showcase/schemas/training-program.schema.json
apps/showcase/src/assets/trainings/sdk/program.json
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.spec.ts
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/training.component.ts
apps/showcase/src/services/webcontainer/webcontainer.service.ts
apps/showcase/testing/mocks/webcontainer-api.mock.ts

Project only contains the description of the exercise and does not reflect the trainee changes.
The file list should reflect the webcontainer state
Fixes also e2e tests and add a prefix for training directories to avoid name conflicts

fix: base code navigation on webcontainer instead of project initial value

---

.github/markdown-external-links.config.json

Links requires authentication and are valid
* :bug: Fix resolves #2599

docs: ignore nx links as invalid links

---

apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.scss
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/save-code-dialog/index.ts
apps/showcase/src/components/training/save-code-dialog/save-code-dialog.component.spec.ts
apps/showcase/src/components/training/save-code-dialog/save-code-dialog.component.ts
apps/showcase/src/components/training/save-code-dialog/save-code-dialog.template.html
apps/showcase/src/components/training/training-step/training-step-pres.component.html

Add persistence in `localStorage` of code modifications in a training step.
When the user refresh or come back on the training on which code modifications were made, we prompt a dialog to ask if he wants to keep the changes or discard them.
With this feature we think also to add a `Reset` or `Discard changes` button, it will be done in another PR, unless someone think it's a must inside this PR.

feat(training): persistence of code modifications

---

jest.config.ut.js
packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.ut.js.template

This PR fixes an issue when running tests if tsconfig.json contains more than one item in one of the paths arrays (which is the case when using otter generator for a library).
To reproduce the issue (I did it with Otter 11.5.3):
```sh
npm create @o3r myproject
cd myproject
npm exec ng g library
#? Name of the package of the new module? mylib
#? Which preset to use to start your application? BASIC - Minimum plugin list to install for a basic Otter application. (details on https://www.npmjs.com/package/@o3r/core#preset-basic)
npm exec ng g application
#? Name of the new application? myapp
#? Which preset to use to start your application? BASIC - Minimum plugin list to install for a basic Otter application. (details on https://www.npmjs.com/package/@o3r/core#preset-basic)
```
Then add a …

fix: jest.config.ut.js not processing array in tsconfig paths correctly

---

packages/@o3r/rules-engine/src/engine/helpers/filter-ruleset-event.operator.spec.ts
packages/@o3r/rules-engine/src/engine/helpers/filter-ruleset-event.operator.ts
packages/@o3r/rules-engine/src/services/runner/rules-engine.runner.service.spec.ts

Emit an empty array of actions to execute when no ruleset remains active during the executions of rules engine. 
Nowadays there is no emission so the already applied actions are not reset.
* :bug: Fix #2609

fix: reset actions emitted when no rulesets remains activated

---

packages/@o3r/core/builders/lib-build/index.ts
packages/@o3r/core/builders/run-script/index.ts

fix: linter issue with typescript-eslint 8.18

---

packages/@o3r/core/src/utils/deep-fill/deep-fill.spec.ts
packages/@o3r/core/src/utils/deep-fill/deep-fill.ts

Add the support of the `null` as deepFill object field value
* :bug: Fix resolves #2601

fix(core): add support for "null" type

---

packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts

use posix to compute path for `outputPath`
* :bug: Fix resolves #2630

fix(#2630): use posix to compute path for outputPath

---

apps/showcase/eslint.local.config.mjs
apps/showcase/src/components/showcase/configuration/configuration-pres.config.ts
docs/ab-testing/AB_TESTING.md
docs/linter/eslint-plugin/rules/o3r-restriction-key-tags.md
docs/linter/eslint-plugin/rules/o3r-widget-tags.md
packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
packages/@o3r/components/src/core/component.output.ts
packages/@o3r/configuration/schemas/configuration.metadata.schema.json
packages/@o3r/eslint-config-otter/rules/typescript/jsdoc.cjs
packages/@o3r/eslint-config/src/rules/typescript/jsdoc.cjs
packages/@o3r/eslint-plugin/src/index.ts
packages/@o3r/eslint-plugin/src/rules/typescript/o3r-restriction-key-tags/o3r-restriction-key-tags.spec.ts
packages/@o3r/eslint-plugin/src/rules/typescript/o3r-restriction-key-tags/o3r-restriction-key-tags.ts
packages/@o3r/extractors/src/utils/config-doc.spec.ts
packages/@o3r/extractors/src/utils/config-doc.ts
tools/github-actions/cascading/readme.md

As a developer I want to be able to flag a configuration property as sensitive.
It was decided to have an array of restriction, named `restrictionKeys` for each property, to support potential future use case with different level of restriction based on the role of the user configuring the property value.
This PR includes:
- the update of the metadata schema
- the extraction of `restrictionKeys` from the jsdoc tags `@o3rRestrictionKeys`
- a linter to limit the possible keys used with `@o3rRestrictionKeys`

feat(config): add support for restrictionKeys

---

.renovaterc.json5
packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/pom.xml

Fallback open api generator version to 7.9.0
because of this [issue](https://github.com/OpenAPITools/openapi-generator/issues/20135)

fix(ama-sdk): fallback open api generator version to 7.9.0

---

apps/vscode-extension/package.json
apps/vscode-extension/src/extension.ts
apps/vscode-extension/src/intellisense/configuration.ts
yarn.lock

Allow the VsCode extension to be loaded without espree detection 
This PR **is not** a proper fix of the lack of  espree dependency but unlock the extension run
* :bug: Fix (**partial**) #2580

fix(vscode): allow VsCode extension without espree detection

---

apps/showcase/src/components/training/code-editor-view/code-editor-view.component.html
apps/showcase/src/components/training/code-editor-view/code-editor-view.component.ts
apps/showcase/src/components/training/training-step/training-step-pres.component.html
apps/showcase/src/components/training/training-step/training-step-pres.component.ts
apps/showcase/src/components/training/training.component.html
apps/showcase/src/components/training/training.component.ts

If enabled, show terminal but deactivate code edition for exercise solutions
Set input as signal on training step

fneat(training): set solution as readonly

---

packages/@o3r/eslint-config/schematics/ng-add/eslint/index.spec.ts
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/project/eslint.local.config.__extension__.template
packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/workspace/eslint.shared.config.__extension__.template

Ease the usage of ESLint by providing default ignores when adding `@o3r/eslint-config`

fix(eslint): provide default ignores when adding @o3r/eslint-config

---

packages/@o3r-training/training-sdk/project.json

fix(training-sdk): remove the training SDK publishing flagged as `private`

fix(training-sdk): remove the training SDK publishing

---

packages/@o3r/pipeline/schematics/ng-add/templates/github/__dot__github/workflows/main.yml

The `release` step for a pipeline generated with `@o3r/pipelines` should wait for `build`, `unit-tests` and  `lint`.

fix: build and test before release

---

.github/workflows/e2e-tests.yml
.yarnrc.yml
apps/chrome-devtools/.gitignore
apps/chrome-devtools/e2e-playwright/playwright-config.sanity.ts
apps/chrome-devtools/e2e-playwright/playwright-config.ts
apps/chrome-devtools/e2e-playwright/sanity/install-sanity.e2e.ts
apps/chrome-devtools/e2e-playwright/scenarios/dummy-scenario.e2e-playwright-spec.ts
apps/chrome-devtools/e2e-playwright/test-with-extension.ts
apps/chrome-devtools/eslint.local.config.mjs
apps/chrome-devtools/package.json
apps/chrome-devtools/project.json
apps/chrome-devtools/scripts/set-manifest-version.cjs
apps/chrome-devtools/src/manifest.json
apps/chrome-devtools/tsconfig.eslint.json
apps/chrome-devtools/tsconfig.extension.json
apps/showcase/.gitignore
apps/showcase/tsconfig.eslint.json
codecov.yml
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

Set up e2e tests for chrome extensions.
For now, it just ensure that the installation of the extension on chrome is successful.
The goal would be to have visual testing with mocks on the extension panel to avoid regressions.

test(chrome-devtools): setup e2e tests for chrome extension

---

.github/workflows/code-check.yml
tools/renovate/managers/github-node-version.json5

fix: codecov version raising an exception on mend.io (see [mend.io dashboard](https://developer.mend.io/github/AmadeusITGroup/otter))
fix: renovate node version rule to activate on main branches

fix: renovate exception 

---

packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/library/index.spec.ts
packages/@o3r/workspace/schematics/library/rules/rules.ng.ts
packages/@o3r/workspace/schematics/library/templates/ng/tsconfig.lib.prod.json.template

fix(workspace): the tsconfig links to generate libraries
It fixes the following points:
- generate the tsconfig.build.json (mandatory for lib standalone publishing)
- remove the `dist/` path from the `tsconfig.base.json` which is leading to wrong path mapping when the library was locally built
- register properly the lib in both tsconfig files
- update the tsconfig.lib.prod.json to extend the correct tsconfig
* :bug: Fix resolves #2665

fix(workspace): the tsconfig links to generate libraries

---

packages/@o3r/extractors/src/core/wrapper.ts
packages/@o3r/pipeline/package.json
packages/@o3r/pipeline/schematics/index.it.spec.ts
packages/@o3r/schematics/src/utility/wrapper.ts

The `pipeline` package should be added as a dev dependency. 
We should reflect if this is the case for other packages as well.

fix: dev install for @o3r/pipeline

---

packages/@o3r/workspace/schematics/library/templates/nx/project.json.template

fix(workspace): update nx scope in generated executors

fix(workspace): update nx scope in generated executors

---

packages/@o3r/components/schemas/placeholder-template.schema.json
packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.spec.ts
packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.ts
packages/@o3r/components/src/stores/placeholder-request/placeholder-request.state.ts

Follow up for https://github.com/AmadeusITGroup/otter/pull/1587, removing deprecated `vars` used in placeholder templates.
Documentation has been already updated https://github.com/AmadeusITGroup/otter/commit/18470a5f5617e580959ffde5b1147b0ae69bfb46#diff-84b1c82a9c6fd7aaf05809ae0ad3020bdaf415d9b37ad73029fe22999ebfbb26

fix: remove deprecated vars for templates

---

packages/@o3r/design/src/core/design-token/parsers/design-token.parser.spec.ts
packages/@o3r/design/src/core/design-token/parsers/design-token.parser.ts

feat(design): add support of URL as token file input

feat(design): add support of URL as token file input

---

migration-guides/12.0.md

Fix the typo of the backslash in the URLs generated by the deprecated items script. 

fix: typos in URLS in v12 migration guide

---

migration-guides/12.0.md
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/spec/api-mock.mustache
packages/@o3r-training/showcase-sdk/src/spec/api-mock.ts
packages/@o3r-training/training-sdk/package.json
packages/@o3r-training/training-sdk/src/spec/api-mock.ts
packages/@o3r/testing/src/core/protractor/component-fixture.ts
yarn.lock

Cleanup of deprecated items in api-mock of showcase SDK and training SDK (and mustache file in @ama-sdk/schematics)

feat: clean up deprecated items in api-mock of SDKs and protractor testing

---

packages/@o3r/core/schematics/ng-add-create/index.ts
packages/@o3r/core/schematics/ng-add-create/templates/schematics/ng-add/index.ts.template
packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
packages/@o3r/workspace/schematics/index.it.spec.ts
packages/@o3r/workspace/schematics/library/rules/shared.ts

* :bug: Fix resolves #2714
* :bug: Fix resolves #2715

fix: build builder and schematics for o3r lib

---

packages/@o3r/workspace/schematics/ng-add/index.ts

fix(#2755): add the missing -- for arguments after npm command

---

.yarnrc.yml
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

chore: align typescript-eslint deps

---

packages/@o3r/schematics/src/rule-factories/ng-add/dependencies.ts

Perform the install if a dependency has an `ng-add` schematics *and* is not installed yet, even if the parent schematics has `skipInstall` to `true` (which is the default value).
* :bug: Fix resolves #2766

fix: enforce install if dependencies have ng add

---

package.json
packages/@o3r/design/schematics/extract-token/index.ts
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.spec.ts
packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
packages/@o3r/styling/builders/style-extractor/index.ts
packages/@o3r/styling/package.json
yarn.lock

Switch to sass-embedded package to use Dart Sass CLI, instead of sass package.
From my first tests, it seems the time it takes to extract styling variables is divided by 10.
Further analysis, comparing sass vs sass-embedded. We have multiple packages with different number of components inside.
In local, I observe a 91% improvement whatever the number of components, running extractions separately in sequence.
In the CI, performance gains have more variance : ranging from 67.8 up to 92.9% depending on the number of components.
This can be explained by varying workloads and extractors running in parallel on the agent.
* :bug: Fix resolves #2272

fix: improve performance of styling extractor

---

packages/@ama-sdk/core/src/fwk/date.spec.ts
packages/@ama-sdk/core/src/fwk/date.ts
packages/@ama-sdk/core/testing/global-timezone-setup.js
packages/@ama-sdk/core/testing/jest.config.ut.js

Changing timezone from 00 to 12 introduced a breaking change and does not  work for DateTime issue
Recompute timezone based on the difference between the prior timezone and the new date one

fix: adjust timezone based on new date timezone

---

packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/core/index.js

Clean up deprecated jar which was only used for JAVA generation

fix: remove unused and deprecated swagger-gen jar

---

tools/renovate/tasks/otter-ng-update.json

Fix an issue in renovate `otter-ng-update` preset when used with npm: 
`--` was missing in the command, so `ng update` options such as `--allow-dirty` were not taken into account.

fix(renovate): add missing `--` in `npm run ng update` command

---

tools/renovate/tasks/otter-ng-update.json

This mode makes the post upgrade command run for each dependency update, rather than once for all the updates in the branch. 
We need to set this mode because `ng update` does not allow the `--from=... --to=... --migrate-only` combination for many packages at the same time.

Renovate presets: run `otter-ng-update` post upgrade commands in mode executionMode=update

---

packages/@o3r/workspace/schematics/library/templates/ng/jest/tsconfig.spec.json.template

The angular lint builder does not support references and composite.
IDE supports navigation for spec files thanks to the project tsconfig.json
We do not need these references anymore

fix: fix ng lint for generated packages

---

packages/@o3r/eslint-config/schematics/ng-add/index.ts

Removing `@o3r/eslint-config` explicit dev dep for `@o3r/eslint-plugin` as it comes from its own package json.
Fixes the following scenario:
- create a new otter project with a fixed version
- add `@o3r/eslint-config` (with fixed otter version) 
Now: version is not fixed for `@o3r/eslint-plugin`
Expected: version is fixed for  `@o3r/eslint-plugin`

fix: eslint-config eslint-plugin dep

---

packages/@o3r/core/schematics/ng-add/utils/linter/index.spec.ts
packages/@o3r/core/schematics/ng-add/utils/linter/index.ts
packages/@o3r/workspace/schematics/rule-factories/linter.spec.ts
packages/@o3r/workspace/schematics/rule-factories/linter.ts

The regex for checking for flat config files was invalid.
This code is currently duplicated in workspace and core, is there a place where we can move it so that it can be reused? In schematics maybe?

fix: condition for using flat config

---

docs/renovate/readme.md

Provide more details on how to allow renovate post upgrade commands.

docs(renovate): update renovate doc on how to allow post upgrade commands

---

tools/renovate/base.json

Renovate should use `chore` when bumping deps rather than `fix`.

fix: renovate to use chore instead of fix

---

packages/@o3r/core/schematics/ng-add/index.ts
packages/@o3r/core/schematics/shared/presets/helpers.ts
packages/@o3r/create/src/index.it.spec.ts

Forward the options to modules when using presets.
How to reproduce:
```shell
npm create @o3r test-preset-cms-exact -- --preset cms --exact-o3r-version
```
Should have all deps fixed and it is not the case today.

fix: forward options for presets

---

.github/markdown-external-links.config.json

Adding an exception for markdown link checker for Figma plugins as they use a bot protection returning 403 for non-human users.
```shell
curl -I https://www.figma.com/community/plugin/929607085343688745/color-shades
HTTP/2 403 
server: CloudFront
date: Mon, 03 Mar 2025 15:03:31 GMT
content-type: text/html
content-length: 919
x-cache: Error from cloudfront
via: 1.1 f41688bac877227b82b3347b2428d266.cloudfront.net (CloudFront)
x-amz-cf-pop: FRA56-P12
alt-svc: h3=":443"; ma=86400
x-amz-cf-id: BEkxjBUsVFyzSVEuDhJb_GHpcdp58fmWSQ5Y97UodcSjwpWsBPrZjQ==
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
```
Bot protection doesn't affect other Figma links (i.e. https://help.figma.com/hc/en-us/articles/14506821864087-Overview-of-variables-collectio …

docs: markdown link check exception for Figma plugins

---

.github/workflows/e2e-tests.yml
.github/workflows/main.yml
apps/showcase/e2e-playwright/playwright-config.ts
apps/showcase/e2e-playwright/sanity/visual-sanity.e2e.ts
apps/showcase/scripts/update-screenshots/readme.md
docs/testing/VISUAL_TESTING_REPORTER.md
packages/@ama-sdk/client-angular/tsconfig.eslint.json
packages/@ama-sdk/client-beacon/tsconfig.eslint.json
packages/@ama-sdk/client-fetch/tsconfig.eslint.json
packages/@ama-sdk/schematics/package.json
packages/@o3r-training/training-sdk/tsconfig.eslint.json
packages/@o3r-training/training-tools/tsconfig.eslint.json
packages/@o3r/pipeline/tsconfig.eslint.json
packages/@o3r/testing/package.json
packages/@o3r/testing/src/visual-testing-reporter/index.ts
packages/@o3r/testing/tsconfig.build.json
tools/github-actions/create-branch-e2e-screenshots/LICENSE
tools/github-actions/create-branch-e2e-screenshots/action.yml
tools/github-actions/create-branch-e2e-screenshots/readme.md
tools/github-actions/get-npm-tag/eslint.local.config.mjs
tools/github-actions/new-version/eslint.local.config.mjs
tools/github-actions/release/eslint.local.config.mjs
tools/github-actions/release/tsconfig.eslint.json
tools/github-actions/update-e2e-screenshots/LICENSE
tools/github-actions/update-e2e-screenshots/action.yml
tools/github-actions/update-e2e-screenshots/readme.md

On PR event, create branch with updated screenshots if any and comment the PR to let the contributor know.
:rocket: Feature resolves #2701

feat(e2e): generate branch with the updated e2e screenshots

---

packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json.template
packages/@o3r/workspace/migration.json
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/index.ts
packages/@o3r/workspace/schematics/ng-add/helpers/renovate/templates/__dot__renovaterc.json.template
packages/@o3r/workspace/schematics/ng-update/index.ts
packages/@o3r/workspace/schematics/ng-update/v12.1/renovate-version.ts
tools/renovate/managers/renovate-otter-presets.json5
tools/renovate/otter-project.json

feat: specify renovate Otter preset versions
Missing:
* :rocket: Feature resolves #1829

feat: specify renovate Otter preset versions

---

.github/workflows/it-tests.yml

The `*-test-app` cache should only be written on main/releases branches once a month.
PR were never meant to create these caches.

ci: prevent pull requests to write cache for it tests

---

.renovaterc.json5
tools/renovate/README.md
tools/renovate/base.json
tools/renovate/branching-strategy/readme.md
tools/renovate/branching-strategy/release-branches.json
tools/renovate/branching-strategy/trunk-based.json
tools/renovate/group/angular.json
tools/renovate/group/design-factory.json
tools/renovate/group/typescript.json
tools/renovate/managers/github-node-version.json5
tools/renovate/otter-project.json
tools/renovate/sdk.json

feat(renovate): split trunk-base and release branches strategies
feat(renovate): register node-version update in base
* :rocket: Feature resolves #2722
* :rocket: Feature resolves #2712

feat(renovate): split trunk-base and release branches strategies

---

packages/@ama-sdk/client-angular/src/api-angular-client.ts
packages/@ama-sdk/client-beacon/src/api-beacon-client.ts
packages/@ama-sdk/client-fetch/src/api-fetch-client.ts
packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-beacon-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/api.helper.spec.ts
packages/@ama-sdk/core/src/fwk/api.helpers.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/core/src/fwk/core/base-api-constructor.ts
packages/@ama-sdk/core/src/fwk/index.ts
packages/@ama-sdk/core/src/fwk/param-serialization.spec.ts
packages/@ama-sdk/core/src/fwk/param-serialization.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@o3r-training/showcase-sdk/src/api/pet/pet-api.ts
packages/@o3r-training/showcase-sdk/src/api/store/store-api.ts
packages/@o3r-training/showcase-sdk/src/api/user/user-api.ts
packages/@o3r-training/showcase-sdk/src/spec/api-mock.ts
packages/@o3r-training/training-sdk/open-api.yaml
packages/@o3r-training/training-sdk/src/api/dummy/dummy-api.ts
packages/@o3r-training/training-sdk/src/spec/api-mock.ts

Support of exploded syntax for query and path parameters: https://swagger.io/docs/specification/v3_0/serialization/ 
This is an alternate solution to the existing PR https://github.com/AmadeusITGroup/otter/pull/2865 to avoid breaking changes.
**UPDATE:** I added a second commit that limits the path and query parameters to be of supported types (primitve, simple array of primitive values, and simple non-nested objects). If this is approved, I will squash the second commit into the first one.
#640 

feat: support exploded syntax in sdk

---

packages/@ama-mfe/ng-utils/src/theme/theme.consumer.service.spec.ts
packages/@ama-mfe/ng-utils/src/theme/theme.consumer.service.ts
packages/@ama-mfe/ng-utils/src/theme/theme.helpers.spec.ts
packages/@ama-mfe/ng-utils/src/theme/theme.helpers.ts

feat(ama-mfe-utils): download application local CSS when receiving message from host 
* :rocket: Feature resolves #2919

feat(ama-mfe-utils): download application local CSS

---

packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java

Add default values for specifications of version Swagger 2.0

feat: exploded syntax in sdk - otter default values for swagger2

---

packages/@ama-sdk/core/src/fwk/api.helpers.ts
packages/@ama-sdk/core/src/fwk/param-serialization.spec.ts
packages/@ama-sdk/core/src/fwk/param-serialization.ts

Fix the newly created `PrimitiveType` to support dates (`utils.Date` and `utils.DateTime`)

feat: exploded syntax in sdk - support dates

---

.github/workflows/it-tests.yml

Only run it-tests on `ubuntu/npm` when a pull-request target `main`

ci: limit it-tests on pull-requests to only ubuntu-npm

---

apps/showcase/e2e-playwright/sanity/lighthouse-sanity.e2e.ts

Currently, lighthouse is waiting 45s for the page to load but never detects it (on every test)
It doesn't seem to impact us since we are not using the `performance` audits, so I propose to reduce the timeout to 1s

ci: speed up execution of lighthouse tests

---

.github/workflows/code-check.yml
nx.json

Jest tries to parallelize the execution of tests by using all the available number of cores minus 1 (https://jestjs.io/docs/cli#--maxworkersnumstring)
However, Nx is already parallelizing the execution of tests (we've set it to 3 in parallel for the CI)

ci: speed up execution of unit tests

---

packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.spec.ts
packages/@o3r/components/src/rules-engine/placeholder.rules-engine.effect.ts

fix: placeholder should support rendering the same fact with different json path

---

packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.spec.ts
packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.ts

Since `v0.0.3` service messages don't arrive via `.messages$`, but have separate `.serviceMessages$`, so the check is not necessary

fix(ama-mfe-ng-utils): remove useless `isServiceMessage` check

---

packages/@ama-sdk/core/src/fwk/date.spec.ts
packages/@ama-sdk/core/src/fwk/date.ts

In `utils.Date` class, we expose a method `equals` to compare 2 dates.
Using this method when mocking the clock in Playwright will make the test fail due to the change in prototype.
The issue has been raised in Playwright https://github.com/microsoft/playwright/issues/35314, but it will probably not be fixed anytime soon.
I suggest to extract the method to a helper that can be used even with fake Dates

feat(sdk): extract compare date function from utils.date

---

packages/@ama-mfe/ng-utils/src/navigation/navigation.consumer.service.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.producer.service.ts
packages/@ama-mfe/ng-utils/src/utils.ts

We consider 3 ways to get the origin of the host
- `document.referrer` works on all browsers but fails on internal redirection (login for example)
- `location.ancestorOrigins` supports redirections but doesn't work on Firefox
- use a query parameter works in all scenarios but require an additional action to modify the URL of the iframe
* :rocket: Feature resolves #2918

feat(ama-mfe): get the url of the host using query parameter

---

.yarn/sdks/eslint/package.json
packages/@ama-sdk/schematics/package.json
packages/@o3r/core/package.json
packages/@o3r/dynamic-content/src/services/dynamic-content/dynamic-content.module.ts
packages/@o3r/eslint-config-otter/package.json

Fix the breaking change introduce by https://github.com/AmadeusITGroup/otter/pull/3000
As the pipe was not exported anymore by the module 
https://github.com/AmadeusITGroup/otter/pull/3000

fix: exports the pipe that was previously standalone to avoid introducing a breaking change

---

.github/ISSUE_TEMPLATE/1-O3R-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/2-AMA-SDK-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/3-AMA-TERASU-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/4-APPLICATION-ISSUE-FORM.yaml
.github/ISSUE_TEMPLATE/5-FEATURE-FORM.yaml

chore: use Github Type instead of label in task creation

chore: use Github Type instead of label in task creation

---

packages/@ama-mfe/ng-utils/README.md
packages/@ama-mfe/ng-utils/src/connect/connect.providers.ts
packages/@ama-mfe/ng-utils/src/host-info/host-info.pipe.spec.ts
packages/@ama-mfe/ng-utils/src/host-info/host-info.pipe.ts
packages/@ama-mfe/ng-utils/src/host-info/host-info.spec.ts
packages/@ama-mfe/ng-utils/src/host-info/host-info.ts
packages/@ama-mfe/ng-utils/src/host-info/index.ts
packages/@ama-mfe/ng-utils/src/navigation/navigation.consumer.service.ts
packages/@ama-mfe/ng-utils/src/public_api.ts
packages/@ama-mfe/ng-utils/src/theme/theme.helpers.ts
packages/@ama-mfe/ng-utils/src/utils.ts

Add `ama-mfe-host-app-id=<your id>` as a get parameter of the url of the iframes
- Add `provideHostInfo()` in `app.config.ts`
- Call `inject(MFE_HOST_INFO_TOKEN)` whenever needed to get the info about the hosting app

feat(ama-mfe): make the host application id available for embedded module

---

package.json
packages/@o3r/core/package.json

Run `yarn install` after the `postinstall` scripts.

chore: install with no scripts after postinstall

---

packages/@ama-sdk/client-angular/src/api-angular-client.ts
packages/@ama-sdk/client-beacon/src/api-beacon-client.ts
packages/@ama-sdk/client-fetch/src/api-fetch-client.ts
packages/@ama-sdk/core/src/clients/api-angular-client.ts
packages/@ama-sdk/core/src/clients/api-beacon-client.ts
packages/@ama-sdk/core/src/clients/api-fetch-client.ts
packages/@ama-sdk/core/src/fwk/api.helpers.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/core/src/fwk/core/base-api-constructor.ts
packages/@ama-sdk/core/src/fwk/param-serialization.ts
packages/@ama-sdk/core/src/plugins/additional-params/additional-params-sync.request.ts
packages/@ama-sdk/core/src/plugins/additional-params/additional-params.request.ts
packages/@ama-sdk/core/src/plugins/additional-params/additional-params.spec.ts
packages/@ama-sdk/core/src/plugins/core/request-plugin.ts
packages/@ama-sdk/core/src/plugins/si-token/si-token.request.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/LambdaHelper.java
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
packages/@o3r-training/showcase-sdk/src/api/pet/pet-api.ts
packages/@o3r-training/showcase-sdk/src/api/store/store-api.ts
packages/@o3r-training/showcase-sdk/src/api/user/user-api.ts
packages/@o3r-training/training-sdk/src/api/dummy/dummy-api.ts

When we previously implemented the exploded syntax for SDK parameter serialization, we removed the possibility of taking into account the query parameters that can be updated in the Request Plugins - which needs to be fixed. Here is a possible fix, which prepares the URL using the request plugins options (which could update the query parameters). 
Also, the parameter `queryParamSerialization` has been added to `RequestOptionsParameters`, which can be used in order to serialize the query parameter modifications that are potentially made. In another PR, I will add a method allowing to deserialize the parameters, which facilitates the modifications in the Request Plugins.

fix: sdk exploded syntax - take into account request plugin options

---

packages/@o3r/create/src/index.it.spec.ts

Temporarily deactivate test which block the merge of other bugfixes.
Issue is tracked in https://github.com/AmadeusITGroup/otter/issues/3113

fix: temporarily disable o3r create e2e to unblock release

---

packages/@o3r/create/src/index.ts

listr2/prompt-adapter-inquirer is a dependency brought by angular cli.
This package declares incorrectly its listr2 dependency which results in a failure in our o3r create schematic.
This fix should be removed once https://github.com/listr2/listr2/pull/719 is merged

fix: enforce listr2 resolution for yarn pnp in o3r/create

---

packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts
packages/@o3r/workspace/schematics/sdk/index.ts
packages/@o3r/workspace/schematics/sdk/rules/clean-standalone.rule.ts
packages/@o3r/workspace/schematics/sdk/rules/update-ts-paths.rule.ts

fix(sdk): generation of the SDK in a monorepo
"@angular-eslint/eslint-plugin": "",
"@angular-eslint/eslint-plugin-template": "",
"@angular-eslint/utils": "",
* :bug: Fix resolves #3094

fix(sdk): generation of the SDK in a monorepo

---

.yarn/sdks/eslint/package.json
.yarn/sdks/typescript/package.json
apps/chrome-devtools/package.json
apps/showcase/package.json
package.json
packages/@o3r/core/package.json
packages/@o3r/eslint-config-otter/package.json
yarn.lock

fix: unmatched peerDependencies

fix: unmatched peerDependencies

---

packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/api/.editorconfig.template
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/base/.editorconfig.template
packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/.editorconfig.template

feat(ama-sdk-schematics): ignore editorconfig rules for generated folders
* :rocket: Feature resolves #3106

feat(ama-sdk-schematics): ignore editorconfig rules

---

packages/@ama-mfe/messages/package.json
packages/@ama-mfe/messages/src/messages/navigation/navigation.versions.ts
packages/@ama-mfe/messages/src/messages/resize/resize.versions.ts
packages/@ama-mfe/messages/src/messages/theme/theme.versions.ts
packages/@ama-mfe/ng-utils/package.json
packages/@ama-mfe/ng-utils/src/connect/connect.providers.ts
packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.spec.ts
packages/@ama-mfe/ng-utils/src/managers/consumer.manager.service.ts
packages/@ama-mfe/ng-utils/src/managers/interfaces.ts
packages/@ama-mfe/ng-utils/src/managers/producer.manager.service.spec.ts
packages/@ama-mfe/ng-utils/src/managers/producer.manager.service.ts
packages/@ama-mfe/ng-utils/src/messages/error.sender.spec.ts
packages/@ama-mfe/ng-utils/src/messages/error.sender.ts
packages/@ama-mfe/ng-utils/src/messages/error/base.ts
packages/@ama-mfe/ng-utils/src/messages/error/error.versions.ts
yarn.lock

- bump `@amadeus-it-group/microfrontends` to `0.0.7`
- use `VersionedMessage` instead of `Message` as `version` field became optional in `Message`
- use `messageCheckStrategy: 'version'` as message `type` and `version` checks became opt-in.

Bump `@amadeus-it-group/microfrontends` to `0.0.7`

---

packages/@o3r/testing/schematics/playwright/sanity/index.spec.ts

Unit tests broken by https://github.com/AmadeusITGroup/otter/pull/3127
The PR passed due to an issue with `.nxignore` containing the template files

test(testing): fix o3r-testing unit tests

---

packages/@o3r/create/src/index.it.spec.ts
packages/@o3r/rules-engine/src/engine/debug/engine.debug.ts

Currently, every time the value of a fact changes, a full snapshot is sent.
To avoid a big overload, I propose to send it at max once every second.

fix(rules-engine): debug perfs linked to fact snapshots

---

packages/@o3r/components/src/tools/component-replacement/c11n.module.ts

In #3000, the `C11nDirective` has been removed from the exports of the `C11nModule` which is a breaking change. A fix has been delivered for the same issue for the `DynamicContentModule` here : #3065 . Doing the same in this PR for the `C11nModule`.
Issue #3162
PR #3000
:bug: Fix resolves #3162

fix: export C11nDirective in C11nModule to avoid breaking change (#3162)

---

docs/forms/FORM_STRUCTURE.md
docs/forms/FORM_VALIDATION.md
docs/forms/README.md

Fix the broken links in the forms documentation.
* :bug: Fix resolves #3168

fix: broken links in forms documentation

---

packages/@o3r/core/schematics/index.it.spec.ts
packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.ts.template

The Playwright server is already started via the config (https://github.com/AmadeusITGroup/otter/pull/3157) 
No need to start another server in the integration test.

fix: do not start server for pw in int tests

---

packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.ts

Send a resize message only when the change of the height is significant (bigger than DELTA_RESIZE)

fix: com protocol resize triggered when a significant height change

---

packages/@o3r/testing/src/tools/path-replacement/path-replacement.ts

adjustPath method relies on the fact that node throws an error when requiring an ESM module. In the catch block, the code module is transformed to CJS.
This method works until Node 20.18.3.
With Node 20.19.0, [require(esm) is now enabled by default](https://nodejs.org/fr/blog/release/v20.19.0#requireesm-is-now-enabled-by-default) and therefore, no errors are thrown and ESM module are not transformed to CJS anymore.
This PR is a candidate fix for this issue.
Before requiring the module, the type will be inferred. If ESM is detected, the module will be converted to CJS.
Fixes 🐛 #3047

fix: adjust path replacement script to work with node 20.19.0

---

packages/@o3r/style-dictionary/src/transform-groups/css-recommended.transform-group.mts

fix(style-dictionary): remove sizeRem from recommended transforms

fix(style-dictionary): remove sizeRem transform

---

.vscode/settings.json
packages/@ama-sdk/schematics/package.json
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java

fix(sdk): add support of [AnyType from AOS3](https://swagger.io/docs/specification/v3_0/data-models/data-types/#any-type)
```yaml
components:
schemas:
example:
type: object # or type: null
```

fix(sdk): add support of AnyType from OAS3

---

packages/@ama-sdk/core/src/fwk/param-deserialization.spec.ts
packages/@ama-sdk/core/src/fwk/param-deserialization.ts
packages/@ama-sdk/core/src/fwk/param-serialization.spec.ts
packages/@ama-sdk/core/src/fwk/param-serialization.ts
packages/@ama-sdk/schematics/README.md
packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache

Provide deserialization functions as a tool to deserialize query and path parameters.
This PR was created as a split of PR #3076 

feat: parameter deserialization

---

packages/@o3r/create/README.md

Migrate link of cli option to the new angular.dev website

fix(docs): update url angular cli options

---

.yarnrc.yml
packages/@ama-sdk/schematics/collection.json
packages/@o3r/analytics/collection.json
packages/@o3r/configuration/collection.json
packages/@o3r/core/collection.json
packages/@o3r/design/collection.json
packages/@o3r/localization/collection.json
packages/@o3r/rules-engine/collection.json
packages/@o3r/styling/collection.json
packages/@o3r/testing/collection.json
packages/@o3r/third-party/collection.json
packages/@o3r/workspace/collection.json

feat: add o3r prefix to generators
* :rocket: Feature resolves #3012

feat: add o3r prefix to generators

---

packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.spec.ts
packages/@ama-mfe/ng-utils/src/resize/resize.producer.service.ts

Cherry-picked from 
https://github.com/AmadeusITGroup/otter/pull/3248

cherry-pick: ama-mfe resize based on getClientBoundRect

---

packages/@o3r/components/src/devkit/components-devkit.interface.ts
packages/@o3r/components/src/devkit/components-devtools.message.service.ts
packages/@o3r/components/src/devkit/highlight/constants.ts
packages/@o3r/components/src/devkit/highlight/helpers.spec.ts
packages/@o3r/components/src/devkit/highlight/helpers.ts
packages/@o3r/components/src/devkit/highlight/highlight.service.ts
packages/@o3r/components/src/devkit/highlight/models.ts

🚀 Feature https://github.com/AmadeusITGroup/otter/issues/2532
- Set up groups (same message for the following configurations elementMinWidth, elementMinHeight, throttleInterval, maxDepth, chipsOpacity and autoRefresh)
```
window.postMessage({
type: 'otter',
to: 'app',
content: {
dataType: 'changeHighlightConfiguration',
groupsInfo: {
otter: {
backgroundColor: '#f4dac6',
color: 'black',
regexp: '^o3r',
displayName: 'o3r'
},
designFactory: {
backgroundColor: '#000835',
regexp: '^df',
displayName: 'df'
},
ngBootstrap: {
backgroundColor: '#0d6efd',
regexp: '^ngb',
displayName: 'ngb'
}
},
maxDepth: 6,
chipsOpacity: 0.8,
autoRefresh: true
}
});
```
- Activate highlight
```
window.postMessage({
type: 'otter',
to: 'app',
content: {
dataType: 'toggleHighlight',
isRunning: true
}
});
```
- You can …

feat: group and highlight components by tag name

---

apps/chrome-devtools/project.json
apps/showcase/project.json
packages/@ama-mfe/ng-utils/project.json
packages/@ama-sdk/client-angular/project.json
packages/@ama-terasu/schematics/project.json
packages/@o3r/analytics/project.json
packages/@o3r/apis-manager/project.json
packages/@o3r/application/project.json
packages/@o3r/components/project.json
packages/@o3r/configuration/project.json
packages/@o3r/core/project.json
packages/@o3r/dynamic-content/project.json
packages/@o3r/forms/project.json
packages/@o3r/localization/project.json
packages/@o3r/logger/project.json
packages/@o3r/mobile/project.json
packages/@o3r/routing/project.json
packages/@o3r/rules-engine/project.json
packages/@o3r/schematics/project.json
packages/@o3r/store-sync/project.json
packages/@o3r/styling/project.json
packages/@o3r/telemetry/project.json
packages/@o3r/test-helpers/project.json
packages/@o3r/testing/project.json
packages/@o3r/third-party/project.json
packages/@o3r/workspace/project.json

Nx look for tsconfig for angular project in the build script.
Add tsconfig for build target only for angular dependant projects.

feat: ease angular migration

---

.github/workflows/code-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/it-tests.yml
.github/workflows/main.yml
.github/workflows/publish.yml

For some reason, NX target a corrupted cache on some PRs which become impossible to merge
Allow a temporary deactivation to avoid stucked PRs

fix: add variables to temporarily deactivate nx cache

---

docs/analytics/TRACK_EVENTS.md
packages/@ama-sdk/client-fetch/src/plugins/abort/readme.md

See run [output](https://github.com/AmadeusITGroup/otter/actions/runs/17367799571/job/49297768570)
https://styledictionary.com/ was only temporary not accessible
* :bug: Fix resolves #3471

docs: fix broken links

---

packages/@o3r/eslint-config/src/rules/typescript/stylistic.cjs

https://eslint.style/rules/operator-linebreak#overrides

fix(eslint): wrong stylistic/operator-linebreak override

---

packages/@ama-sdk/core/src/fwk/api.helpers.ts
packages/@ama-sdk/core/src/fwk/core/api-client.ts
packages/@ama-sdk/core/src/fwk/core/base-api-constructor.ts
packages/@ama-sdk/core/src/fwk/param-deserialization.ts
packages/@ama-sdk/core/src/fwk/param-serialization.ts

Interfaces do not match the `[key: string]: any` type if they do not extend it.
Rework the type to allow interface to match the SupportedParamType

fix: supportedType for exploded syntax is too restrictive

---

packages/@ama-sdk/schematics/cli/files-pack.cts

For bundlers, the 'default' keyword should be the last one in the list of 'exports' in package.json file.
Update the script used for the sdks :)

fix(sdk gen): the default should be last in list of exports in packaage.json
